// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_DecalSet/AbstractDecalSet_Impl_.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
extern hl_type t$urho3d_DecalSet;
void urho3d_DecalSet_new(urho3d__DecalSet,hl_urho3d_graphics_decalset*);

hl_urho3d_graphics_decalset* urho3d__DecalSet_AbstractDecalSet_Impl___new() {
	hl_urho3d_graphics_decalset *r0;
	urho3d___Context__$Context_Impl_ r2;
	urho3d_context *r1;
	r2 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r1 = r2->context;
	r0 = Urho3D__graphics_decalset_create(r1);
	return r0;
}

urho3d__DecalSet urho3d__DecalSet_AbstractDecalSet_Impl__toDecalSet(hl_urho3d_graphics_decalset* r0) {
	urho3d__DecalSet r1;
	r1 = (urho3d__DecalSet)hl_alloc_obj(&t$urho3d_DecalSet);
	urho3d_DecalSet_new(r1,r0);
	return r1;
}

