// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_UIElement/UIElement_Impl_.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;

hl_urho3d_uielement* urho3d__UIElement_UIElement_Impl___new() {
	urho3d___Context__$Context_Impl_ r2;
	urho3d_context *r1;
	hl_urho3d_uielement *r0;
	r2 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r1 = r2->context;
	r0 = Urho3D__create_uielement(r1);
	return r0;
}

void urho3d__UIElement_UIElement_Impl__AddChild(hl_urho3d_uielement* r0,hl_urho3d_uielement* r1) {
	urho3d___Context__$Context_Impl_ r4;
	urho3d_context *r3;
	r4 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r3 = r4->context;
	Urho3D__ui_uielement_add_child(r3,r0,r1);
	return;
}

void urho3d__UIElement_UIElement_Impl__RemoveChild(hl_urho3d_uielement* r0,hl_urho3d_uielement* r1,int* r2) {
	urho3d___Context__$Context_Impl_ r6;
	urho3d_context *r5;
	int r3;
	if( r2 ) goto label$a4a987c_3_3;
	r3 = 0;
	goto label$a4a987c_3_4;
	label$a4a987c_3_3:
	r3 = *r2;
	label$a4a987c_3_4:
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	Urho3D__ui_uielement_remove_child(r5,r0,r1,r3);
	return;
}

