// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_TVariant/TVariant_Impl_.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
extern hl_type t$urho3d_RigidBody;
void urho3d_RigidBody_new(urho3d__RigidBody,hl_urho3d_physics_rigid_body*);

hl_urho3d_tvariant* urho3d__TVariant_TVariant_Impl___new() {
	hl_urho3d_tvariant *r0;
	r0 = Urho3D__create_tvariant();
	return r0;
}

int urho3d__TVariant_TVariant_Impl__get_int(hl_urho3d_tvariant* r0) {
	int r1;
	r1 = Urho3D__tvariant_get_int(r0);
	return r1;
}

double urho3d__TVariant_TVariant_Impl__get_float(hl_urho3d_tvariant* r0) {
	float r1;
	double r2;
	r1 = Urho3D__tvariant_get_float(r0);
	r2 = (double)r1;
	return r2;
}

double urho3d__TVariant_TVariant_Impl__get_single(hl_urho3d_tvariant* r0) {
	float r1;
	double r2;
	r1 = Urho3D__tvariant_get_float(r0);
	r2 = (double)r1;
	return r2;
}

hl_urho3d_variant* urho3d__TVariant_TVariant_Impl__get_variant(hl_urho3d_tvariant* r0) {
	hl_urho3d_variant *r1;
	r1 = Urho3D__math_tvariant_cast_to_variant(r0);
	return r1;
}

hl_urho3d_math_vector2* urho3d__TVariant_TVariant_Impl__get_vector2(hl_urho3d_tvariant* r0) {
	hl_urho3d_math_vector2 *r1;
	r1 = Urho3D__tvariant_get_vector2(r0);
	return r1;
}

hl_urho3d_math_tvector2* urho3d__TVariant_TVariant_Impl__get_tvector2(hl_urho3d_tvariant* r0) {
	hl_urho3d_math_tvector2 *r1;
	r1 = Urho3D__tvariant_get_tvector2(r0);
	return r1;
}

hl_urho3d_math_tintvector2* urho3d__TVariant_TVariant_Impl__get_tintvector2(hl_urho3d_tvariant* r0) {
	hl_urho3d_math_tintvector2 *r1;
	r1 = Urho3D__tvariant_get_tintvector2(r0);
	return r1;
}

hl_urho3d_core_object* urho3d__TVariant_TVariant_Impl__get_object(hl_urho3d_tvariant* r0) {
	hl_urho3d_core_object *r1;
	r1 = Urho3D__tvariant_get_object(r0);
	return r1;
}

hl_urho3d_scene_component* urho3d__TVariant_TVariant_Impl__get_component(hl_urho3d_tvariant* r0) {
	hl_urho3d_scene_component *r2;
	hl_urho3d_core_object *r1;
	urho3d___Context__$Context_Impl_ r4;
	urho3d_context *r3;
	r1 = Urho3D__tvariant_get_object(r0);
	r4 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r3 = r4->context;
	r2 = Urho3D__core_object_cast_to_component(r3,r1);
	return r2;
}

urho3d__RigidBody urho3d__TVariant_TVariant_Impl__GetRigidBody(hl_urho3d_tvariant* r0) {
	hl_urho3d_physics_rigid_body *r6;
	hl_urho3d_scene_component *r3;
	urho3d__RigidBody r7;
	hl_urho3d_core_object *r1;
	urho3d___Context__$Context_Impl_ r5;
	urho3d_context *r4;
	r1 = Urho3D__tvariant_get_object(r0);
	r5 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r4 = r5->context;
	r3 = Urho3D__core_object_cast_to_component(r4,r1);
	if( !r3 ) goto label$cdfe610_11_14;
	r5 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r4 = r5->context;
	r6 = Urho3D__physics_rigid_body_cast_from_component(r4,r3);
	if( !r6 ) goto label$cdfe610_11_12;
	r7 = (urho3d__RigidBody)hl_alloc_obj(&t$urho3d_RigidBody);
	urho3d_RigidBody_new(r7,r6);
	return r7;
	label$cdfe610_11_12:
	r7 = NULL;
	return r7;
	label$cdfe610_11_14:
	r7 = NULL;
	return r7;
}

hl_urho3d_scene_component* urho3d__TVariant_TVariant_Impl__GetComponent(hl_urho3d_tvariant* r0) {
	hl_urho3d_scene_component *r2;
	hl_urho3d_core_object *r1;
	urho3d___Context__$Context_Impl_ r4;
	urho3d_context *r3;
	r1 = Urho3D__tvariant_get_object(r0);
	r4 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r3 = r4->context;
	r2 = Urho3D__core_object_cast_to_component(r3,r1);
	return r2;
}

hl_urho3d_core_object* urho3d__TVariant_TVariant_Impl__GetObject(hl_urho3d_tvariant* r0) {
	hl_urho3d_core_object *r1;
	r1 = Urho3D__tvariant_get_object(r0);
	return r1;
}

hl_urho3d_variant* urho3d__TVariant_TVariant_Impl__ToVariant(hl_urho3d_tvariant* r0) {
	hl_urho3d_variant *r1;
	r1 = Urho3D__math_tvariant_cast_to_variant(r0);
	return r1;
}

double urho3d__TVariant_TVariant_Impl__GetSingle(hl_urho3d_tvariant* r0) {
	float r1;
	double r2;
	r1 = Urho3D__tvariant_get_float(r0);
	r2 = (double)r1;
	return r2;
}

double urho3d__TVariant_TVariant_Impl__GetFloat(hl_urho3d_tvariant* r0) {
	float r1;
	double r2;
	r1 = Urho3D__tvariant_get_float(r0);
	r2 = (double)r1;
	return r2;
}

int urho3d__TVariant_TVariant_Impl__GetInt(hl_urho3d_tvariant* r0) {
	int r1;
	r1 = Urho3D__tvariant_get_int(r0);
	return r1;
}

hl_urho3d_math_vector2* urho3d__TVariant_TVariant_Impl__GetVector2(hl_urho3d_tvariant* r0) {
	hl_urho3d_math_vector2 *r1;
	r1 = Urho3D__tvariant_get_vector2(r0);
	return r1;
}

hl_urho3d_math_tvector2* urho3d__TVariant_TVariant_Impl__GetTVector2(hl_urho3d_tvariant* r0) {
	hl_urho3d_math_tvector2 *r1;
	r1 = Urho3D__tvariant_get_tvector2(r0);
	return r1;
}

hl_urho3d_math_tintvector2* urho3d__TVariant_TVariant_Impl__GetTIntVector2(hl_urho3d_tvariant* r0) {
	hl_urho3d_math_tintvector2 *r1;
	r1 = Urho3D__tvariant_get_tintvector2(r0);
	return r1;
}

hl_urho3d_io_t_vector_buffer* urho3d__TVariant_TVariant_Impl__GetTIntVectorBuffer(hl_urho3d_tvariant* r0) {
	hl_urho3d_io_t_vector_buffer *r1;
	r1 = Urho3D__t_variant_get_vector_buffer(r0);
	return r1;
}

hl_urho3d_tvariant* urho3d__TVariant_TVariant_Impl__fromTVectorBuffer(hl_urho3d_io_t_vector_buffer* r0) {
	hl_urho3d_tvariant *r1;
	r1 = Urho3D__create_tvariant();
	Urho3D__t_variant_set_vector_buffer(r1,r0);
	return r1;
}

hl_urho3d_tvariant* urho3d__TVariant_TVariant_Impl__fromObject(hl_urho3d_core_object* r0) {
	hl_urho3d_tvariant *r1;
	r1 = Urho3D__create_tvariant();
	Urho3D__tvariant_set_object(r1,r0);
	return r1;
}

hl_urho3d_tvariant* urho3d__TVariant_TVariant_Impl__FromVariant(hl_urho3d_variant* r0) {
	hl_urho3d_tvariant *r1;
	r1 = Urho3D__math_tvariant_cast_from_variant(r0);
	return r1;
}

hl_urho3d_tvariant* urho3d__TVariant_TVariant_Impl__FromTIntVector2(hl_urho3d_math_tintvector2* r0) {
	hl_urho3d_tvariant *r1;
	r1 = Urho3D__create_tvariant();
	Urho3D__tvariant_set_tintvector2(r1,r0);
	return r1;
}

hl_urho3d_tvariant* urho3d__TVariant_TVariant_Impl__FromTVector2(hl_urho3d_math_tvector2* r0) {
	hl_urho3d_tvariant *r1;
	r1 = Urho3D__create_tvariant();
	Urho3D__tvariant_set_tvector2(r1,r0);
	return r1;
}

hl_urho3d_tvariant* urho3d__TVariant_TVariant_Impl__FromVector2(hl_urho3d_math_vector2* r0) {
	hl_urho3d_tvariant *r1;
	r1 = Urho3D__create_tvariant();
	Urho3D__tvariant_set_vector2(r1,r0);
	return r1;
}

hl_urho3d_tvariant* urho3d__TVariant_TVariant_Impl__FromInt(int r0) {
	hl_urho3d_tvariant *r1;
	r1 = Urho3D__create_tvariant();
	Urho3D__tvariant_set_int(r1,r0);
	return r1;
}

hl_urho3d_tvariant* urho3d__TVariant_TVariant_Impl__FromFloat(double r0) {
	hl_urho3d_tvariant *r1;
	float r3;
	r1 = Urho3D__create_tvariant();
	r3 = (float)r0;
	Urho3D__tvariant_set_float(r1,r3);
	return r1;
}

