// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_urho3d__LogicComponent
#define INC_urho3d__LogicComponent
typedef struct _urho3d__$LogicComponent *urho3d__$LogicComponent;
typedef struct _urho3d__LogicComponent *urho3d__LogicComponent;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <urho3d/Component.h>
#include <urho3d/Node.h>
#include <urho3d/Scene.h>


struct _urho3d__$LogicComponent {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* CreateFactory;
	vclosure* RegisterObject;
};
struct _urho3d__LogicComponent {
	hl_type *$type;
	urho3d__Node _node;
	urho3d__Scene _scene;
	hl_urho3d_scene_component* abstractComponent;
	hl_urho3d_scene_logic_component* abstractLogicComponent;
};
#endif

