// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/StaticModel.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
void urho3d_Component_new(urho3d__Component,hl_urho3d_scene_component*);

bool urho3d_StaticModel_set_occluder(urho3d__StaticModel r0,bool r1) {
	urho3d___Context__$Context_Impl_ r4;
	urho3d_context *r3;
	hl_urho3d_graphics_staticmodel *r5;
	r4 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r3 = r4->context;
	r5 = r0->_abstract;
	Urho3D__graphics_staticmodel_set_occluder(r3,r5,r1);
	return r1;
}

bool urho3d_StaticModel_get_occluder(urho3d__StaticModel r0) {
	bool r1;
	urho3d___Context__$Context_Impl_ r3;
	urho3d_context *r2;
	hl_urho3d_graphics_staticmodel *r4;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r4 = r0->_abstract;
	r1 = Urho3D__graphics_staticmodel_get_occluder(r2,r4);
	return r1;
}

bool urho3d_StaticModel_set_occludee(urho3d__StaticModel r0,bool r1) {
	urho3d___Context__$Context_Impl_ r4;
	urho3d_context *r3;
	hl_urho3d_graphics_staticmodel *r5;
	r4 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r3 = r4->context;
	r5 = r0->_abstract;
	Urho3D__graphics_staticmodel_set_occludee(r3,r5,r1);
	return r1;
}

bool urho3d_StaticModel_get_occludee(urho3d__StaticModel r0) {
	bool r1;
	urho3d___Context__$Context_Impl_ r3;
	urho3d_context *r2;
	hl_urho3d_graphics_staticmodel *r4;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r4 = r0->_abstract;
	r1 = Urho3D__graphics_staticmodel_get_occludee(r2,r4);
	return r1;
}

hl_urho3d_graphics_model* urho3d_StaticModel_set_model(urho3d__StaticModel r0,hl_urho3d_graphics_model* r1) {
	urho3d___Context__$Context_Impl_ r4;
	urho3d_context *r3;
	hl_urho3d_graphics_staticmodel *r5;
	r4 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r3 = r4->context;
	r5 = r0->_abstract;
	Urho3D__graphics_staticmodel_set_model(r3,r5,r1);
	return r1;
}

hl_urho3d_graphics_model* urho3d_StaticModel_get_model(urho3d__StaticModel r0) {
	urho3d___Context__$Context_Impl_ r3;
	urho3d_context *r2;
	hl_urho3d_graphics_staticmodel *r4;
	hl_urho3d_graphics_model *r1;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r4 = r0->_abstract;
	r1 = Urho3D__graphics_staticmodel_get_model(r2,r4);
	return r1;
}

hl_urho3d_graphics_material* urho3d_StaticModel_set_material(urho3d__StaticModel r0,hl_urho3d_graphics_material* r1) {
	urho3d___Context__$Context_Impl_ r4;
	urho3d_context *r3;
	hl_urho3d_graphics_staticmodel *r5;
	r4 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r3 = r4->context;
	r5 = r0->_abstract;
	Urho3D__graphics_staticmodel_set_material(r3,r5,r1);
	return r1;
}

hl_urho3d_graphics_material* urho3d_StaticModel_get_material(urho3d__StaticModel r0) {
	urho3d___Context__$Context_Impl_ r3;
	hl_urho3d_graphics_material *r1;
	urho3d_context *r2;
	hl_urho3d_graphics_staticmodel *r4;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r4 = r0->_abstract;
	r1 = Urho3D__graphics_staticmodel_get_material(r2,r4);
	return r1;
}

bool urho3d_StaticModel_set_castShadows(urho3d__StaticModel r0,bool r1) {
	urho3d___Context__$Context_Impl_ r4;
	urho3d_context *r3;
	hl_urho3d_graphics_staticmodel *r5;
	r4 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r3 = r4->context;
	r5 = r0->_abstract;
	Urho3D__graphics_staticmodel_set_cast_shadows(r3,r5,r1);
	return r1;
}

bool urho3d_StaticModel_get_castShadows(urho3d__StaticModel r0) {
	bool r1;
	urho3d___Context__$Context_Impl_ r3;
	urho3d_context *r2;
	hl_urho3d_graphics_staticmodel *r4;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r4 = r0->_abstract;
	r1 = Urho3D__graphics_staticmodel_get_cast_shadows(r2,r4);
	return r1;
}

void urho3d_StaticModel_new(urho3d__StaticModel r0,hl_urho3d_graphics_staticmodel* r1) {
	hl_urho3d_scene_component *r6;
	urho3d___Context__$Context_Impl_ r5;
	urho3d_context *r4;
	hl_urho3d_graphics_staticmodel *r2;
	r2 = NULL;
	r0->_abstract = r2;
	if( !r1 ) goto label$3796faa_11_5;
	r0->_abstract = r1;
	goto label$3796faa_11_9;
	label$3796faa_11_5:
	r5 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r4 = r5->context;
	r2 = Urho3D__graphics_staticmodel_create(r4);
	r0->_abstract = r2;
	label$3796faa_11_9:
	r5 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r4 = r5->context;
	r2 = r0->_abstract;
	r6 = Urho3D__graphics_staticmodel_cast_to_component(r4,r2);
	urho3d_Component_new(((urho3d__Component)r0),r6);
	return;
}

