// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_actions__BezierConfig
#define INC_actions__BezierConfig
typedef struct _actions__$BezierConfig *actions__$BezierConfig;
typedef struct _actions__BezierConfig *actions__BezierConfig;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>


struct _actions__$BezierConfig {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _actions__BezierConfig {
	hl_type *$type;
	hl_urho3d_math_vector3* ControlPoint1;
	hl_urho3d_math_vector3* ControlPoint2;
	hl_urho3d_math_vector3* EndPosition;
};
#endif

