// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/CollisionShape.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
#include <urho3d/_Vector3/Vector3_Impl_.h>
extern urho3d___Vector3__$Vector3_Impl_ g$_urho3d__Vector3_Vector3_Impl_;
void urho3d_Component_new(urho3d__Component,hl_urho3d_scene_component*);

void urho3d_CollisionShape_SetBox(urho3d__CollisionShape r0,hl_urho3d_math_tvector3* r1,hl_urho3d_math_tvector3* r2,hl_urho3d_math_tquaternion* r3) {
	hl_urho3d_math_tquaternion *r10;
	urho3d___Context__$Context_Impl_ r13;
	urho3d_context *r12;
	float r7, r8, r9;
	double r6, r11;
	hl_urho3d_physics_collision_shape *r14;
	hl_urho3d_math_tvector3 *r5;
	if( r2 ) goto label$376a5b5_1_9;
	r6 = 0.;
	r7 = (float)r6;
	r6 = 0.;
	r8 = (float)r6;
	r6 = 0.;
	r9 = (float)r6;
	r5 = Urho3D__math_tvector3_create(r7,r8,r9);
	r2 = r5;
	label$376a5b5_1_9:
	if( r3 ) goto label$376a5b5_1_23;
	r6 = 0.;
	r5 = NULL;
	if( !r5 ) goto label$376a5b5_1_16;
	r7 = (float)r6;
	r10 = Urho3D__math_t_quaternion_create_fv(r7,r5);
	goto label$376a5b5_1_22;
	label$376a5b5_1_16:
	r7 = (float)r6;
	r11 = 0.;
	r8 = (float)r11;
	r11 = 0.;
	r9 = (float)r11;
	r10 = Urho3D__math_t_quaternion_create(r7,r8,r9);
	label$376a5b5_1_22:
	r3 = r10;
	label$376a5b5_1_23:
	r13 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r12 = r13->context;
	r14 = r0->_abstract;
	Urho3D__physics_collision_shape_set_box(r12,r14,r1,r2,r3);
	return;
}

void urho3d_CollisionShape_SetSphere(urho3d__CollisionShape r0,double r1,hl_urho3d_math_tvector3* r2,hl_urho3d_math_tquaternion* r3) {
	hl_urho3d_math_tquaternion *r10;
	urho3d___Context__$Context_Impl_ r13;
	urho3d_context *r12;
	float r7, r8, r9;
	double r6, r11;
	hl_urho3d_physics_collision_shape *r14;
	hl_urho3d_math_tvector3 *r5;
	if( r2 ) goto label$376a5b5_2_9;
	r6 = 0.;
	r7 = (float)r6;
	r6 = 0.;
	r8 = (float)r6;
	r6 = 0.;
	r9 = (float)r6;
	r5 = Urho3D__math_tvector3_create(r7,r8,r9);
	r2 = r5;
	label$376a5b5_2_9:
	if( r3 ) goto label$376a5b5_2_23;
	r6 = 0.;
	r5 = NULL;
	if( !r5 ) goto label$376a5b5_2_16;
	r7 = (float)r6;
	r10 = Urho3D__math_t_quaternion_create_fv(r7,r5);
	goto label$376a5b5_2_22;
	label$376a5b5_2_16:
	r7 = (float)r6;
	r11 = 0.;
	r8 = (float)r11;
	r11 = 0.;
	r9 = (float)r11;
	r10 = Urho3D__math_t_quaternion_create(r7,r8,r9);
	label$376a5b5_2_22:
	r3 = r10;
	label$376a5b5_2_23:
	r13 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r12 = r13->context;
	r14 = r0->_abstract;
	r7 = (float)r1;
	Urho3D__physics_collision_shape_set_sphere(r12,r14,r7,r2,r3);
	return;
}

void urho3d_CollisionShape_SetStaticPlane(urho3d__CollisionShape r0,hl_urho3d_math_tvector3* r1,hl_urho3d_math_tquaternion* r2) {
	hl_urho3d_math_tquaternion *r9;
	urho3d___Context__$Context_Impl_ r12;
	urho3d_context *r11;
	float r6, r7, r8;
	double r5, r10;
	hl_urho3d_physics_collision_shape *r13;
	hl_urho3d_math_tvector3 *r4;
	if( r1 ) goto label$376a5b5_3_9;
	r5 = 0.;
	r6 = (float)r5;
	r5 = 0.;
	r7 = (float)r5;
	r5 = 0.;
	r8 = (float)r5;
	r4 = Urho3D__math_tvector3_create(r6,r7,r8);
	r1 = r4;
	label$376a5b5_3_9:
	if( r2 ) goto label$376a5b5_3_23;
	r5 = 0.;
	r4 = NULL;
	if( !r4 ) goto label$376a5b5_3_16;
	r6 = (float)r5;
	r9 = Urho3D__math_t_quaternion_create_fv(r6,r4);
	goto label$376a5b5_3_22;
	label$376a5b5_3_16:
	r6 = (float)r5;
	r10 = 0.;
	r7 = (float)r10;
	r10 = 0.;
	r8 = (float)r10;
	r9 = Urho3D__math_t_quaternion_create(r6,r7,r8);
	label$376a5b5_3_22:
	r2 = r9;
	label$376a5b5_3_23:
	r12 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r11 = r12->context;
	r13 = r0->_abstract;
	Urho3D__physics_collision_shape_set_static_plane(r11,r13,r1,r2);
	return;
}

void urho3d_CollisionShape_SetCylinder(urho3d__CollisionShape r0,double r1,double r2,hl_urho3d_math_tvector3* r3,hl_urho3d_math_tquaternion* r4) {
	hl_urho3d_math_tquaternion *r11;
	urho3d___Context__$Context_Impl_ r14;
	urho3d_context *r13;
	float r8, r9, r10;
	double r7, r12;
	hl_urho3d_physics_collision_shape *r15;
	hl_urho3d_math_tvector3 *r6;
	if( r3 ) goto label$376a5b5_4_9;
	r7 = 0.;
	r8 = (float)r7;
	r7 = 0.;
	r9 = (float)r7;
	r7 = 0.;
	r10 = (float)r7;
	r6 = Urho3D__math_tvector3_create(r8,r9,r10);
	r3 = r6;
	label$376a5b5_4_9:
	if( r4 ) goto label$376a5b5_4_23;
	r7 = 0.;
	r6 = NULL;
	if( !r6 ) goto label$376a5b5_4_16;
	r8 = (float)r7;
	r11 = Urho3D__math_t_quaternion_create_fv(r8,r6);
	goto label$376a5b5_4_22;
	label$376a5b5_4_16:
	r8 = (float)r7;
	r12 = 0.;
	r9 = (float)r12;
	r12 = 0.;
	r10 = (float)r12;
	r11 = Urho3D__math_t_quaternion_create(r8,r9,r10);
	label$376a5b5_4_22:
	r4 = r11;
	label$376a5b5_4_23:
	r14 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r13 = r14->context;
	r15 = r0->_abstract;
	r8 = (float)r1;
	r9 = (float)r2;
	Urho3D__physics_collision_shape_set_cylinder(r13,r15,r8,r9,r3,r4);
	return;
}

void urho3d_CollisionShape_SetCapsule(urho3d__CollisionShape r0,double r1,double r2,hl_urho3d_math_tvector3* r3,hl_urho3d_math_tquaternion* r4) {
	hl_urho3d_math_tquaternion *r11;
	urho3d___Context__$Context_Impl_ r14;
	urho3d_context *r13;
	float r8, r9, r10;
	double r7, r12;
	hl_urho3d_physics_collision_shape *r15;
	hl_urho3d_math_tvector3 *r6;
	if( r3 ) goto label$376a5b5_5_9;
	r7 = 0.;
	r8 = (float)r7;
	r7 = 0.;
	r9 = (float)r7;
	r7 = 0.;
	r10 = (float)r7;
	r6 = Urho3D__math_tvector3_create(r8,r9,r10);
	r3 = r6;
	label$376a5b5_5_9:
	if( r4 ) goto label$376a5b5_5_23;
	r7 = 0.;
	r6 = NULL;
	if( !r6 ) goto label$376a5b5_5_16;
	r8 = (float)r7;
	r11 = Urho3D__math_t_quaternion_create_fv(r8,r6);
	goto label$376a5b5_5_22;
	label$376a5b5_5_16:
	r8 = (float)r7;
	r12 = 0.;
	r9 = (float)r12;
	r12 = 0.;
	r10 = (float)r12;
	r11 = Urho3D__math_t_quaternion_create(r8,r9,r10);
	label$376a5b5_5_22:
	r4 = r11;
	label$376a5b5_5_23:
	r14 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r13 = r14->context;
	r15 = r0->_abstract;
	r8 = (float)r1;
	r9 = (float)r2;
	Urho3D__physics_collision_shape_set_capsule(r13,r15,r8,r9,r3,r4);
	return;
}

void urho3d_CollisionShape_SetTriangleMesh(urho3d__CollisionShape r0,hl_urho3d_graphics_model* r1,int* r2,hl_urho3d_math_tvector3* r3,hl_urho3d_math_tvector3* r4,hl_urho3d_math_tquaternion* r5) {
	urho3d___Vector3__$Vector3_Impl_ r10;
	hl_urho3d_math_vector3 *r9;
	hl_urho3d_math_tquaternion *r12;
	urho3d___Context__$Context_Impl_ r18;
	urho3d_context *r17;
	float r14, r15, r16;
	double r11, r13;
	hl_urho3d_physics_collision_shape *r19;
	hl_urho3d_math_tvector3 *r8;
	int r6;
	if( r2 ) goto label$376a5b5_6_3;
	r6 = 0;
	goto label$376a5b5_6_4;
	label$376a5b5_6_3:
	r6 = *r2;
	label$376a5b5_6_4:
	if( r3 ) goto label$376a5b5_6_9;
	r10 = (urho3d___Vector3__$Vector3_Impl_)g$_urho3d__Vector3_Vector3_Impl_;
	r9 = r10->ONE;
	r8 = Urho3D__math_tvector3_cast_from_vector3(r9);
	r3 = r8;
	label$376a5b5_6_9:
	if( r4 ) goto label$376a5b5_6_14;
	r10 = (urho3d___Vector3__$Vector3_Impl_)g$_urho3d__Vector3_Vector3_Impl_;
	r9 = r10->ZERO;
	r8 = Urho3D__math_tvector3_cast_from_vector3(r9);
	r4 = r8;
	label$376a5b5_6_14:
	if( r5 ) goto label$376a5b5_6_28;
	r11 = 0.;
	r8 = NULL;
	if( !r8 ) goto label$376a5b5_6_21;
	r14 = (float)r11;
	r12 = Urho3D__math_t_quaternion_create_fv(r14,r8);
	goto label$376a5b5_6_27;
	label$376a5b5_6_21:
	r14 = (float)r11;
	r13 = 0.;
	r15 = (float)r13;
	r13 = 0.;
	r16 = (float)r13;
	r12 = Urho3D__math_t_quaternion_create(r14,r15,r16);
	label$376a5b5_6_27:
	r5 = r12;
	label$376a5b5_6_28:
	r18 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r17 = r18->context;
	r19 = r0->_abstract;
	Urho3D__physics_collision_shape_set_triangle_mesh(r17,r19,r1,r6,r3,r4,r5);
	return;
}

void urho3d_CollisionShape_new(urho3d__CollisionShape r0,hl_urho3d_physics_collision_shape* r1) {
	hl_urho3d_scene_component *r6;
	urho3d___Context__$Context_Impl_ r5;
	urho3d_context *r4;
	hl_urho3d_physics_collision_shape *r2;
	r2 = NULL;
	r0->_abstract = r2;
	if( !r1 ) goto label$376a5b5_7_5;
	r0->_abstract = r1;
	goto label$376a5b5_7_9;
	label$376a5b5_7_5:
	r5 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r4 = r5->context;
	r2 = Urho3D__physics_collision_shape_create(r4);
	r0->_abstract = r2;
	label$376a5b5_7_9:
	r5 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r4 = r5->context;
	r2 = r0->_abstract;
	r6 = Urho3D__physics_collision_shape_cast_to_component(r4,r2);
	urho3d_Component_new(((urho3d__Component)r0),r6);
	return;
}

