// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/actions/EaseBackInOut.h>
void urho3d_actions_ActionEase_new(urho3d__actions__ActionEase,urho3d__actions__FiniteTimeAction);
#include <urho3d/Node.h>
#include <urho3d/actions/EaseBackInOutState.h>
#include <urho3d/actions/FiniteTimeActionState.h>
extern hl_type t$urho3d_actions_EaseBackInOutState;
void urho3d_actions_EaseBackInOutState_new(urho3d__actions__EaseBackInOutState,urho3d__actions__EaseBackInOut,urho3d__Node);
extern hl_type t$urho3d_actions_EaseBackInOut;

void urho3d_actions_EaseBackInOut_new(urho3d__actions__EaseBackInOut r0,urho3d__actions__FiniteTimeAction r1) {
	urho3d_actions_ActionEase_new(((urho3d__actions__ActionEase)r0),r1);
	return;
}

urho3d__actions__FiniteTimeActionState urho3d_actions_EaseBackInOut_StartAction(urho3d__actions__EaseBackInOut r0,urho3d__Node r1) {
	urho3d__actions__EaseBackInOutState r2;
	r2 = (urho3d__actions__EaseBackInOutState)hl_alloc_obj(&t$urho3d_actions_EaseBackInOutState);
	urho3d_actions_EaseBackInOutState_new(r2,r0,r1);
	return ((urho3d__actions__FiniteTimeActionState)r2);
}

urho3d__actions__FiniteTimeAction urho3d_actions_EaseBackInOut_Reverse(urho3d__actions__EaseBackInOut r0) {
	hl__types__ArrayObj r3;
	urho3d__actions__EaseBackInOut r1;
	urho3d__actions__FiniteTimeAction r2;
	vdynamic *r6;
	varray *r7;
	int r4, r5;
	r1 = (urho3d__actions__EaseBackInOut)hl_alloc_obj(&t$urho3d_actions_EaseBackInOut);
	r3 = r0->InnerAction;
	if( r3 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$4f466b9_3_8;
	r2 = NULL;
	goto label$4f466b9_3_11;
	label$4f466b9_3_8:
	r7 = r3->array;
	r6 = ((vdynamic**)(r7 + 1))[r4];
	r2 = (urho3d__actions__FiniteTimeAction)r6;
	label$4f466b9_3_11:
	if( r2 == NULL ) hl_null_access();
	r2 = ((urho3d__actions__FiniteTimeAction (*)(urho3d__actions__FiniteTimeAction))r2->$type->vobj_proto[0])(r2);
	urho3d_actions_EaseBackInOut_new(r1,r2);
	return ((urho3d__actions__FiniteTimeAction)r1);
}

