// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_urho3d__actions__Parallel
#define INC_urho3d__actions__Parallel
typedef struct _urho3d__actions__$Parallel *urho3d__actions__$Parallel;
typedef struct _urho3d__actions__Parallel *urho3d__actions__Parallel;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <urho3d/actions/FiniteTimeAction.h>
#include <hl/types/ArrayObj.h>


struct _urho3d__actions__$Parallel {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _urho3d__actions__Parallel {
	hl_type *$type;
	double duration;
	int Tag;
	bool isRepeatForever;
	hl__types__ArrayObj Actions;
};
#endif

