// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_Bone/Bone_Impl_.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;

bool urho3d__Bone_Bone_Impl__set_animated(hl_urho3d_graphics_bone* r0,bool r1) {
	urho3d___Context__$Context_Impl_ r4;
	urho3d_context *r3;
	r4 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r3 = r4->context;
	Urho3D__graphics_bone_set_animated(r3,r0,r1);
	return r1;
}

bool urho3d__Bone_Bone_Impl__get_animated(hl_urho3d_graphics_bone* r0) {
	bool r1;
	urho3d___Context__$Context_Impl_ r3;
	urho3d_context *r2;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_bone_get_animated(r2,r0);
	return r1;
}

