// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_VariantMap/VariantMap_Impl_.h>
#include <hl/natives.h>

hl_urho3d_variantmap* urho3d__VariantMap_VariantMap_Impl___new() {
	hl_urho3d_variantmap *r0;
	r0 = Urho3D__create_variantmap();
	return r0;
}

hl_urho3d_variant* urho3d__VariantMap_VariantMap_Impl__getValue(hl_urho3d_variantmap* r0,hl_urho3d_stringhash* r1) {
	hl_urho3d_variant *r2;
	r2 = Urho3D__get_value(r0,r1);
	return r2;
}

hl_urho3d_variant* urho3d__VariantMap_VariantMap_Impl__setKeyValue(hl_urho3d_variantmap* r0,hl_urho3d_stringhash* r1,hl_urho3d_variant* r2) {
	hl_urho3d_variant *r3;
	r3 = Urho3D__set_key_value(r0,r1,r2);
	return r3;
}

