// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_Quaternion/Quaternion_Impl_.h>
#include <hl/natives.h>

hl_urho3d_math_quaternion* urho3d__Quaternion_Quaternion_Impl___new(double* r0,double* r1,double* r2,hl_urho3d_math_tvector3* r3) {
	hl_urho3d_math_quaternion *r7;
	float r8, r9, r10;
	double r4, r5, r6;
	if( r0 ) goto label$e48a056_1_3;
	r4 = 0.;
	goto label$e48a056_1_4;
	label$e48a056_1_3:
	r4 = *r0;
	label$e48a056_1_4:
	if( r1 ) goto label$e48a056_1_7;
	r5 = 0.;
	goto label$e48a056_1_8;
	label$e48a056_1_7:
	r5 = *r1;
	label$e48a056_1_8:
	if( r2 ) goto label$e48a056_1_11;
	r6 = 0.;
	goto label$e48a056_1_12;
	label$e48a056_1_11:
	r6 = *r2;
	label$e48a056_1_12:
	if( !r3 ) goto label$e48a056_1_16;
	r8 = (float)r4;
	r7 = Urho3D__math_quaternion_create_fv(r8,r3);
	goto label$e48a056_1_20;
	label$e48a056_1_16:
	r8 = (float)r4;
	r9 = (float)r5;
	r10 = (float)r6;
	r7 = Urho3D__math_quaternion_create(r8,r9,r10);
	label$e48a056_1_20:
	return r7;
}

void urho3d__Quaternion_Quaternion_Impl__Normalize(hl_urho3d_math_quaternion* r0) {
	Urho3D__math_quaternion_normalize(r0);
	return;
}

void urho3d__Quaternion_Quaternion_Impl__SetAngles(hl_urho3d_math_quaternion* r0,double r1,double r2,double r3) {
	float r5, r6, r7;
	r5 = (float)r1;
	r6 = (float)r2;
	r7 = (float)r3;
	Urho3D__math_quaternion_set_euler_angles(r0,r5,r6,r7);
	return;
}

hl_urho3d_math_tquaternion* urho3d__Quaternion_Quaternion_Impl__mulTQuaternion(hl_urho3d_math_quaternion* r0,hl_urho3d_math_tquaternion* r1) {
	hl_urho3d_math_tquaternion *r2;
	r2 = Urho3D__math_t_quaternion_cast_from_quaternion(r0);
	r2 = Urho3D__math_t_quaternion_multiply_tquaternion(r2,r1);
	return r2;
}

hl_urho3d_math_tquaternion* urho3d__Quaternion_Quaternion_Impl__mulQuaternion(hl_urho3d_math_quaternion* r0,hl_urho3d_math_quaternion* r1) {
	hl_urho3d_math_tquaternion *r2, *r3;
	r2 = Urho3D__math_t_quaternion_cast_from_quaternion(r0);
	r3 = Urho3D__math_t_quaternion_cast_from_quaternion(r1);
	r2 = Urho3D__math_t_quaternion_multiply_tquaternion(r2,r3);
	return r2;
}

hl_urho3d_math_tquaternion* urho3d__Quaternion_Quaternion_Impl__toTQuaternion(hl_urho3d_math_quaternion* r0) {
	hl_urho3d_math_tquaternion *r1;
	r1 = Urho3D__math_t_quaternion_cast_from_quaternion(r0);
	return r1;
}

hl_urho3d_math_quaternion* urho3d__Quaternion_Quaternion_Impl__fromTQuaternion(hl_urho3d_math_tquaternion* r0) {
	hl_urho3d_math_quaternion *r1;
	r1 = Urho3D__math_t_quaternion_cast_to_quaternion(r0);
	return r1;
}

