// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/SpritesSample.h>
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
extern haxe__$Log g$_haxe_Log;
extern String s$Setup;
extern hl_type t$vrt_329ffa8;
extern String s$src_haxe_SpritesSample_hx;
extern hl_type t$String;
extern hl_type t$_i32;
extern String s$SpritesSample;
extern hl_type t$vrt_eaa6a3b;
extern String s$Start;
void SpritesSample_CreateSprites(SpritesSample);
void SpritesSample_SubscribeToEvents(SpritesSample);
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
int urho3d_Graphics_get_width(void);
int urho3d_Graphics_get_height(void);
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
extern String s$Textures_UrhoDecal_dds;
hl_urho3d_texture2d* urho3d__Sprite_Sprite_Impl__set_texture(hl_urho3d_sprite*,hl_urho3d_texture2d*);
double urho3d_Application_Random(urho3d__Application,vdynamic*,vdynamic*);
hl_urho3d_math_tvector2* urho3d__Sprite_Sprite_Impl__set_position(hl_urho3d_sprite*,hl_urho3d_math_tvector2*);
hl_urho3d_math_tintvector2* urho3d__Sprite_Sprite_Impl__set_size(hl_urho3d_sprite*,hl_urho3d_math_tintvector2*);
hl_urho3d_math_tintvector2* urho3d__Sprite_Sprite_Impl__set_hotSpot(hl_urho3d_sprite*,hl_urho3d_math_tintvector2*);
float urho3d__Sprite_Sprite_Impl__set_rotation(hl_urho3d_sprite*,float);
hl_urho3d_math_tvector2* urho3d__Sprite_Sprite_Impl__set_scale(hl_urho3d_sprite*,hl_urho3d_math_tvector2*);
extern hl_type t$_f64;
hl_urho3d_tcolor* urho3d__Sprite_Sprite_Impl__set_color(hl_urho3d_sprite*,hl_urho3d_tcolor*);
int urho3d__Sprite_Sprite_Impl__set_blendMode(hl_urho3d_sprite*,int);
hl_urho3d_uielement* urho3d_UI_get_root(void);
void urho3d__UIElement_UIElement_Impl__AddChild(hl_urho3d_uielement*,hl_urho3d_uielement*);
hl_urho3d_tvariantmap* urho3d__Sprite_Sprite_Impl__get_vars(hl_urho3d_sprite*);
extern String s$Velocity;
extern hl_type t$hl_urho3d_sprite;
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
extern hl_type t$_dyn;
float urho3d__Sprite_Sprite_Impl__get_rotation(hl_urho3d_sprite*);
hl_urho3d_math_tvector2* urho3d__Sprite_Sprite_Impl__get_position(hl_urho3d_sprite*);
hl_urho3d_math_tvector2* urho3d__TVariant_TVariant_Impl__get_tvector2(hl_urho3d_tvariant*);
extern String s$Update;
extern String s$HandleUpdate;
void urho3d_Application_SubscribeToEvent(urho3d__Application,hl_urho3d_stringhash*,String);
extern String s$TimeStep;
double urho3d__TVariant_TVariant_Impl__get_float(hl_urho3d_tvariant*);
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
void urho3d_Application_new(urho3d__Application);

void SpritesSample_Setup(SpritesSample r0) {
	String r4, r6;
	vvirtual *r5, *r8;
	haxe__$Log r3;
	vclosure *r2;
	int r7;
	r3 = (haxe__$Log)g$_haxe_Log;
	r2 = r3->trace;
	if( r2 == NULL ) hl_null_access();
	r4 = (String)s$Setup;
	r5 = hl_alloc_virtual(&t$vrt_329ffa8);
	r6 = (String)s$src_haxe_SpritesSample_hx;
	if( hl_vfields(r5)[1] ) *(String*)(hl_vfields(r5)[1]) = (String)r6; else hl_dyn_setp(r5->value,37969014/*fileName*/,&t$String,r6);
	r7 = 10;
	if( hl_vfields(r5)[2] ) *(int*)(hl_vfields(r5)[2]) = (int)r7; else hl_dyn_seti(r5->value,371360620/*lineNumber*/,&t$_i32,r7);
	r6 = (String)s$SpritesSample;
	if( hl_vfields(r5)[0] ) *(String*)(hl_vfields(r5)[0]) = (String)r6; else hl_dyn_setp(r5->value,-63073762/*className*/,&t$String,r6);
	r6 = (String)s$Setup;
	if( hl_vfields(r5)[3] ) *(String*)(hl_vfields(r5)[3]) = (String)r6; else hl_dyn_setp(r5->value,302979532/*methodName*/,&t$String,r6);
	r8 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r5);
	r2->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r2->fun)((vdynamic*)r2->value,((vdynamic*)r4),r8) : ((void (*)(vdynamic*,vvirtual*))r2->fun)(((vdynamic*)r4),r8);
	return;
}

void SpritesSample_Start(SpritesSample r0) {
	String r4, r6;
	vvirtual *r5, *r8;
	haxe__$Log r3;
	vclosure *r2;
	int r7;
	r3 = (haxe__$Log)g$_haxe_Log;
	r2 = r3->trace;
	if( r2 == NULL ) hl_null_access();
	r4 = (String)s$Start;
	r5 = hl_alloc_virtual(&t$vrt_329ffa8);
	r6 = (String)s$src_haxe_SpritesSample_hx;
	if( hl_vfields(r5)[1] ) *(String*)(hl_vfields(r5)[1]) = (String)r6; else hl_dyn_setp(r5->value,37969014/*fileName*/,&t$String,r6);
	r7 = 14;
	if( hl_vfields(r5)[2] ) *(int*)(hl_vfields(r5)[2]) = (int)r7; else hl_dyn_seti(r5->value,371360620/*lineNumber*/,&t$_i32,r7);
	r6 = (String)s$SpritesSample;
	if( hl_vfields(r5)[0] ) *(String*)(hl_vfields(r5)[0]) = (String)r6; else hl_dyn_setp(r5->value,-63073762/*className*/,&t$String,r6);
	r6 = (String)s$Start;
	if( hl_vfields(r5)[3] ) *(String*)(hl_vfields(r5)[3]) = (String)r6; else hl_dyn_setp(r5->value,302979532/*methodName*/,&t$String,r6);
	r8 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r5);
	r2->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r2->fun)((vdynamic*)r2->value,((vdynamic*)r4),r8) : ((void (*)(vdynamic*,vvirtual*))r2->fun)(((vdynamic*)r4),r8);
	SpritesSample_CreateSprites(r0);
	SpritesSample_SubscribeToEvents(r0);
	return;
}

void SpritesSample_CreateSprites(SpritesSample r0) {
	String r7;
	hl__types__ArrayObj r37;
	hl_urho3d_tstringhash *r34;
	hl_urho3d_texture2d *r4, *r8, *r13;
	hl_urho3d_tvariant *r35, *r36;
	hl_urho3d_tvariantmap *r33;
	hl_urho3d_tcolor *r27, *r30;
	hl_urho3d_math_tintvector2 *r22, *r24, *r25;
	urho3d___Context__$Context_Impl_ r6;
	float r19, r20, r28, r29;
	urho3d_context *r5;
	double r15, r18;
	vdynamic *r16, *r17, *r38;
	hl_urho3d_math_tvector2 *r14, *r21, *r26;
	hl_urho3d_sprite *r12;
	hl_urho3d_uielement *r31, *r32;
	int r1, r3, r9, r10, r11, r23;
	r1 = urho3d_Graphics_get_width();
	r3 = urho3d_Graphics_get_height();
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r7 = (String)s$Textures_UrhoDecal_dds;
	r4 = Urho3D__create_texture2d(r5,r7);
	r8 = r4;
	r9 = 0;
	r10 = r0->NUM_SPRITES;
	label$200845f_3_9:
	if( r9 >= r10 ) goto label$200845f_3_117;
	++r9;
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r12 = Urho3D__create_sprite(r5);
	r13 = urho3d__Sprite_Sprite_Impl__set_texture(r12,r8);
	r16 = NULL;
	r17 = NULL;
	r15 = urho3d_Application_Random(((urho3d__Application)r0),r16,r17);
	r18 = (double)r1;
	r15 = r15 * r18;
	r19 = (float)r15;
	r16 = NULL;
	r17 = NULL;
	r15 = urho3d_Application_Random(((urho3d__Application)r0),r16,r17);
	r18 = (double)r3;
	r15 = r15 * r18;
	r20 = (float)r15;
	r14 = Urho3D__math_tvector2_create(r19,r20);
	r21 = urho3d__Sprite_Sprite_Impl__set_position(r12,r14);
	r11 = 128;
	r23 = 128;
	r22 = Urho3D__math_tintvector2_create(r11,r23);
	r24 = urho3d__Sprite_Sprite_Impl__set_size(r12,r22);
	r11 = 64;
	r23 = 64;
	r24 = Urho3D__math_tintvector2_create(r11,r23);
	r25 = urho3d__Sprite_Sprite_Impl__set_hotSpot(r12,r24);
	r16 = NULL;
	r17 = NULL;
	r15 = urho3d_Application_Random(((urho3d__Application)r0),r16,r17);
	r18 = 360.;
	r15 = r15 * r18;
	r19 = (float)r15;
	r19 = urho3d__Sprite_Sprite_Impl__set_rotation(r12,r19);
	r16 = NULL;
	r17 = NULL;
	r15 = urho3d_Application_Random(((urho3d__Application)r0),r16,r17);
	r18 = 0.5;
	r15 = r15 + r18;
	r19 = (float)r15;
	r16 = NULL;
	r17 = NULL;
	r15 = urho3d_Application_Random(((urho3d__Application)r0),r16,r17);
	r18 = 0.5;
	r15 = r15 + r18;
	r20 = (float)r15;
	r21 = Urho3D__math_tvector2_create(r19,r20);
	r26 = urho3d__Sprite_Sprite_Impl__set_scale(r12,r21);
	r15 = 0.5;
	r16 = hl_alloc_dynamic(&t$_f64);
	r16->v.d = r15;
	r17 = NULL;
	r15 = urho3d_Application_Random(((urho3d__Application)r0),r16,r17);
	r18 = 0.5;
	r15 = r15 + r18;
	r19 = (float)r15;
	r15 = 0.5;
	r16 = hl_alloc_dynamic(&t$_f64);
	r16->v.d = r15;
	r17 = NULL;
	r15 = urho3d_Application_Random(((urho3d__Application)r0),r16,r17);
	r18 = 0.5;
	r15 = r15 + r18;
	r20 = (float)r15;
	r15 = 0.5;
	r16 = hl_alloc_dynamic(&t$_f64);
	r16->v.d = r15;
	r17 = NULL;
	r15 = urho3d_Application_Random(((urho3d__Application)r0),r16,r17);
	r18 = 0.5;
	r15 = r15 + r18;
	r28 = (float)r15;
	r15 = 1.;
	r29 = (float)r15;
	r27 = Urho3D__math_tcolor_create(r19,r20,r28,r29);
	r30 = urho3d__Sprite_Sprite_Impl__set_color(r12,r27);
	r11 = 1;
	r11 = urho3d__Sprite_Sprite_Impl__set_blendMode(r12,r11);
	r31 = urho3d_UI_get_root();
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r32 = Urho3D__cast_sprite_to_uielement(r5,r12);
	urho3d__UIElement_UIElement_Impl__AddChild(r31,r32);
	r33 = urho3d__Sprite_Sprite_Impl__get_vars(r12);
	r7 = (String)s$Velocity;
	r34 = Urho3D__math_tstringhash_create(r7);
	r15 = 200.;
	r16 = hl_alloc_dynamic(&t$_f64);
	r16->v.d = r15;
	r17 = NULL;
	r15 = urho3d_Application_Random(((urho3d__Application)r0),r16,r17);
	r18 = 100.;
	r15 = r15 - r18;
	r19 = (float)r15;
	r15 = 200.;
	r16 = hl_alloc_dynamic(&t$_f64);
	r16->v.d = r15;
	r17 = NULL;
	r15 = urho3d_Application_Random(((urho3d__Application)r0),r16,r17);
	r18 = 100.;
	r15 = r15 - r18;
	r20 = (float)r15;
	r26 = Urho3D__math_tvector2_create(r19,r20);
	r35 = Urho3D__create_tvariant();
	Urho3D__tvariant_set_tvector2(r35,r26);
	r36 = Urho3D__core_tvariantmap_set_key_value(r33,r34,r35);
	r37 = r0->sprites;
	if( r37 == NULL ) hl_null_access();
	if( r12 == NULL ) r38 = NULL; else {
		r38 = hl_alloc_dynamic(&t$hl_urho3d_sprite);
		r38->v.ptr = r12;
	}
	r11 = hl_types_ArrayObj_push(r37,r38);
	goto label$200845f_3_9;
	label$200845f_3_117:
	return;
}

void SpritesSample_MoveSprites(SpritesSample r0,double r1) {
	String r18;
	hl__types__ArrayObj r6;
	hl_urho3d_tstringhash *r17;
	hl_urho3d_tvariant *r20;
	hl_urho3d_tvariantmap *r16;
	float r11, r22, r23, r24, r26;
	double r12, r13, r14;
	hl_urho3d_math_tvector2 *r15, *r19, *r21, *r25, *r27;
	vdynamic *r9;
	hl_urho3d_sprite *r8;
	varray *r10;
	int r2, r4, r5, r7;
	r2 = urho3d_Graphics_get_width();
	r4 = urho3d_Graphics_get_height();
	r5 = 0;
	r6 = r0->sprites;
	label$200845f_4_4:
	if( r6 == NULL ) hl_null_access();
	r7 = r6->length;
	if( r5 >= r7 ) goto label$200845f_4_93;
	r7 = r6->length;
	if( ((unsigned)r5) < ((unsigned)r7) ) goto label$200845f_4_12;
	r8 = NULL;
	goto label$200845f_4_15;
	label$200845f_4_12:
	r10 = r6->array;
	r9 = ((vdynamic**)(r10 + 1))[r5];
	r8 = (hl_urho3d_sprite*)hl_dyn_castp(&r9,&t$_dyn,&t$hl_urho3d_sprite);
	label$200845f_4_15:
	++r5;
	r11 = urho3d__Sprite_Sprite_Impl__get_rotation(r8);
	r12 = (double)r11;
	r14 = 30.;
	r13 = r1 * r14;
	r12 = r12 + r13;
	r11 = (float)r12;
	r11 = urho3d__Sprite_Sprite_Impl__set_rotation(r8,r11);
	r15 = urho3d__Sprite_Sprite_Impl__get_position(r8);
	r16 = urho3d__Sprite_Sprite_Impl__get_vars(r8);
	r18 = (String)s$Velocity;
	r17 = Urho3D__math_tstringhash_create(r18);
	r20 = Urho3D__core_tvariantmap_get_value(r16,r17);
	r19 = urho3d__TVariant_TVariant_Impl__get_tvector2(r20);
	r11 = Urho3D__math_tvector2_get_x(r19);
	r12 = (double)r11;
	r12 = r12 * r1;
	r11 = (float)r12;
	r22 = Urho3D__math_tvector2_get_y(r19);
	r12 = (double)r22;
	r12 = r12 * r1;
	r22 = (float)r12;
	r21 = Urho3D__math_tvector2_create(r11,r22);
	r23 = Urho3D__math_tvector2_get_x(r15);
	r12 = (double)r23;
	r23 = Urho3D__math_tvector2_get_x(r21);
	r13 = (double)r23;
	r12 = r12 + r13;
	r23 = (float)r12;
	r24 = Urho3D__math_tvector2_get_y(r15);
	r12 = (double)r24;
	r24 = Urho3D__math_tvector2_get_y(r21);
	r13 = (double)r24;
	r12 = r12 + r13;
	r24 = (float)r12;
	r25 = Urho3D__math_tvector2_create(r23,r24);
	r26 = Urho3D__math_tvector2_get_x(r25);
	r12 = (double)r26;
	r13 = 0.;
	if( !(r12 < r13) ) goto label$200845f_4_61;
	r26 = Urho3D__math_tvector2_get_x(r25);
	r12 = (double)r26;
	r13 = (double)r2;
	r12 = r12 + r13;
	r26 = (float)r12;
	r26 = Urho3D__math_tvector2_set_x(r25,r26);
	label$200845f_4_61:
	r26 = Urho3D__math_tvector2_get_x(r25);
	r12 = (double)r26;
	r13 = (double)r2;
	if( !(r12 >= r13) ) goto label$200845f_4_71;
	r26 = Urho3D__math_tvector2_get_x(r25);
	r12 = (double)r26;
	r13 = (double)r2;
	r12 = r12 - r13;
	r26 = (float)r12;
	r26 = Urho3D__math_tvector2_set_x(r25,r26);
	label$200845f_4_71:
	r26 = Urho3D__math_tvector2_get_y(r25);
	r12 = (double)r26;
	r13 = 0.;
	if( !(r12 < r13) ) goto label$200845f_4_81;
	r26 = Urho3D__math_tvector2_get_y(r25);
	r12 = (double)r26;
	r13 = (double)r4;
	r12 = r12 + r13;
	r26 = (float)r12;
	r26 = Urho3D__math_tvector2_set_y(r25,r26);
	label$200845f_4_81:
	r26 = Urho3D__math_tvector2_get_y(r25);
	r12 = (double)r26;
	r13 = (double)r4;
	if( !(r12 >= r13) ) goto label$200845f_4_91;
	r26 = Urho3D__math_tvector2_get_y(r25);
	r12 = (double)r26;
	r13 = (double)r4;
	r12 = r12 - r13;
	r26 = (float)r12;
	r26 = Urho3D__math_tvector2_set_y(r25,r26);
	label$200845f_4_91:
	r27 = urho3d__Sprite_Sprite_Impl__set_position(r8,r25);
	goto label$200845f_4_4;
	label$200845f_4_93:
	return;
}

void SpritesSample_SubscribeToEvents(SpritesSample r0) {
	String r2;
	hl_urho3d_stringhash *r1;
	r2 = (String)s$Update;
	r1 = Urho3D__create_stringhash(r2);
	r2 = (String)s$HandleUpdate;
	urho3d_Application_SubscribeToEvent(((urho3d__Application)r0),r1,r2);
	return;
}

void SpritesSample_HandleUpdate(SpritesSample r0,hl_urho3d_stringhash* r1,hl_urho3d_variantmap* r2) {
	String r4;
	hl_urho3d_tstringhash *r3;
	hl_urho3d_tvariant *r7;
	double r6;
	r4 = (String)s$TimeStep;
	r3 = Urho3D__math_tstringhash_create(r4);
	r7 = Urho3D__get_value(r2,r3);
	r6 = urho3d__TVariant_TVariant_Impl__get_float(r7);
	SpritesSample_MoveSprites(r0,r6);
	return;
}

void SpritesSample_new(SpritesSample r0) {
	hl__types__ArrayObj r1;
	hl_type *r3;
	int r4;
	varray *r2;
	r3 = &t$_dyn;
	r4 = 0;
	r2 = hl_alloc_array(r3,r4);
	r1 = hl_types_ArrayObj_alloc(r2);
	r0->sprites = r1;
	r4 = 700;
	r0->NUM_SPRITES = r4;
	urho3d_Application_new(((urho3d__Application)r0));
	return;
}

