// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_urho3d__Constraint
#define INC_urho3d__Constraint
typedef struct _urho3d__$Constraint *urho3d__$Constraint;
typedef struct _urho3d__Constraint *urho3d__Constraint;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <urho3d/Component.h>
#include <urho3d/Node.h>
#include <hl/natives.h>


struct _urho3d__$Constraint {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _urho3d__Constraint {
	hl_type *$type;
	urho3d__Node _node;
	hl_urho3d_scene_component* abstractComponent;
	hl_urho3d_physics_constraint* _abstract;
};
#endif

