// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_urho3d__Controls
#define INC_urho3d__Controls
typedef struct _urho3d__$Controls *urho3d__$Controls;
typedef struct _urho3d__Controls *urho3d__Controls;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>


struct _urho3d__$Controls {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _urho3d__Controls {
	hl_type *$type;
	int buttons;
	double yaw;
	double pitch;
	hl_urho3d_variantmap* extraData;
};
#endif

