// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_urho3d__DelayedCall
#define INC_urho3d__DelayedCall
typedef struct _urho3d__$DelayedCall *urho3d__$DelayedCall;
typedef struct _urho3d__DelayedCall *urho3d__DelayedCall;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayDyn.h>


struct _urho3d__$DelayedCall {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _urho3d__DelayedCall {
	hl_type *$type;
	double period_;
	double delay_;
	bool repeat_;
	vdynamic* obj_;
	String declaration_;
	hl__types__ArrayDyn parameters_;
};
#endif

