// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_urho3d__SoundSource
#define INC_urho3d__SoundSource
typedef struct _urho3d__$SoundSource *urho3d__$SoundSource;
typedef struct _urho3d__SoundSource *urho3d__SoundSource;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <urho3d/Component.h>
#include <urho3d/Node.h>
#include <urho3d/Scene.h>
#include <hl/natives.h>


struct _urho3d__$SoundSource {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _urho3d__SoundSource {
	hl_type *$type;
	urho3d__Node _node;
	urho3d__Scene _scene;
	hl_urho3d_scene_component* abstractComponent;
	hl_urho3d_audio_sound_source* _abstract;
};
#endif

