// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_haxe___Int32__Int32_Impl_
#define INC_haxe___Int32__Int32_Impl_
typedef struct _haxe___Int32__$Int32_Impl_ *haxe___Int32__$Int32_Impl_;
typedef struct _haxe___Int32__Int32_Impl_ *haxe___Int32__Int32_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _haxe___Int32__$Int32_Impl_ {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* ucompare;
};
struct _haxe___Int32__Int32_Impl_ {
	hl_type *$type;
};
#endif

