// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_AbstractApplication/AbstractApplication_Impl_.h>
#include <hl/natives.h>
extern String s$test;

hl_urho3d_application* urho3d__AbstractApplication_AbstractApplication_Impl___new(urho3d_context* r0) {
	hl_urho3d_application *r1;
	r1 = Urho3D__create_application(r0);
	return r1;
}

void urho3d__AbstractApplication_AbstractApplication_Impl__Run(hl_urho3d_application* r0) {
	String r2;
	hl_urho3d_stringhash *r1;
	r2 = (String)s$test;
	r1 = Urho3D__create_stringhash(r2);
	Urho3D__pass_stringhash(r0,r1);
	Urho3D__run_application(r0);
	return;
}

void urho3d__AbstractApplication_AbstractApplication_Impl__RegisterSetupClosure(hl_urho3d_application* r0,vclosure* r1) {
	Urho3D__setup_closure_application(r0,r1);
	return;
}

void urho3d__AbstractApplication_AbstractApplication_Impl__RegisterStartClosure(hl_urho3d_application* r0,vclosure* r1) {
	Urho3D__start_closure_application(r0,r1);
	return;
}

void urho3d__AbstractApplication_AbstractApplication_Impl__RegisterStopClosure(hl_urho3d_application* r0,vclosure* r1) {
	Urho3D__stop_closure_application(r0,r1);
	return;
}

void urho3d__AbstractApplication_AbstractApplication_Impl__SubscribeToEvent(hl_urho3d_application* r0,hl_urho3d_stringhash* r1,vclosure* r2) {
	Urho3D__application_subscribe_to_event(r0,r1,r2);
	return;
}

