// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_urho3d___AnimationController__AbstractAnimationController_Impl_
#define INC_urho3d___AnimationController__AbstractAnimationController_Impl_
typedef struct _urho3d___AnimationController__$AbstractAnimationController_Impl_ *urho3d___AnimationController__$AbstractAnimationController_Impl_;
typedef struct _urho3d___AnimationController__AbstractAnimationController_Impl_ *urho3d___AnimationController__AbstractAnimationController_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <urho3d/AnimationController.h>


struct _urho3d___AnimationController__$AbstractAnimationController_Impl_ {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* _new;
	vclosure* toAnimationController;
};
struct _urho3d___AnimationController__AbstractAnimationController_Impl_ {
	hl_type *$type;
};
#endif

