// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_ParticleEmitter2D/AbstractParticleEmitter2D_Impl_.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
extern hl_type t$urho3d_ParticleEmitter2D;
void urho3d_ParticleEmitter2D_new(urho3d__ParticleEmitter2D,hl_urho3d_urho2d_particle_emitter2d*);

hl_urho3d_urho2d_particle_emitter2d* urho3d__ParticleEmitter2D_AbstractParticleEmitter2D_Impl___new() {
	hl_urho3d_urho2d_particle_emitter2d *r0;
	urho3d___Context__$Context_Impl_ r2;
	urho3d_context *r1;
	r2 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r1 = r2->context;
	r0 = Urho3D__urho2d_particle_emitter2d_create(r1);
	return r0;
}

urho3d__ParticleEmitter2D urho3d__ParticleEmitter2D_AbstractParticleEmitter2D_Impl__toParticleEmitter2D(hl_urho3d_urho2d_particle_emitter2d* r0) {
	urho3d__ParticleEmitter2D r1;
	r1 = (urho3d__ParticleEmitter2D)hl_alloc_obj(&t$urho3d_ParticleEmitter2D);
	urho3d_ParticleEmitter2D_new(r1,r0);
	return r1;
}

