// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_RigidBody/AbstractRigidBody_Impl_.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;

hl_urho3d_physics_rigid_body* urho3d__RigidBody_AbstractRigidBody_Impl___new() {
	hl_urho3d_physics_rigid_body *r0;
	urho3d___Context__$Context_Impl_ r2;
	urho3d_context *r1;
	r2 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r1 = r2->context;
	r0 = Urho3D__physics_rigid_body_create(r1);
	return r0;
}

