// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_urho3d___Text__Text_Impl_
#define INC_urho3d___Text__Text_Impl_
typedef struct _urho3d___Text__$Text_Impl_ *urho3d___Text__$Text_Impl_;
typedef struct _urho3d___Text__Text_Impl_ *urho3d___Text__Text_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>


struct _urho3d___Text__$Text_Impl_ {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* _new;
	vclosure* fromUIElement;
	vclosure* toUIElement;
	vclosure* get_text;
	vclosure* set_text;
	vclosure* get_horizontalAlignment;
	vclosure* set_horizontalAlignment;
	vclosure* AddChild;
	vclosure* SetFont;
};
struct _urho3d___Text__Text_Impl_ {
	hl_type *$type;
};
#endif

