// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_TColor/TColor_Impl_.h>
#include <hl/natives.h>

hl_urho3d_tcolor* urho3d__TColor_TColor_Impl___new(double* r0,double* r1,double* r2,double* r3) {
	hl_urho3d_tcolor *r8;
	float r9, r10, r11, r12;
	double r4, r5, r6, r7;
	if( r0 ) goto label$d581593_1_3;
	r4 = 0.;
	goto label$d581593_1_4;
	label$d581593_1_3:
	r4 = *r0;
	label$d581593_1_4:
	if( r1 ) goto label$d581593_1_7;
	r5 = 0.;
	goto label$d581593_1_8;
	label$d581593_1_7:
	r5 = *r1;
	label$d581593_1_8:
	if( r2 ) goto label$d581593_1_11;
	r6 = 0.;
	goto label$d581593_1_12;
	label$d581593_1_11:
	r6 = *r2;
	label$d581593_1_12:
	if( r3 ) goto label$d581593_1_15;
	r7 = 1.;
	goto label$d581593_1_16;
	label$d581593_1_15:
	r7 = *r3;
	label$d581593_1_16:
	r9 = (float)r4;
	r10 = (float)r5;
	r11 = (float)r6;
	r12 = (float)r7;
	r8 = Urho3D__math_tcolor_create(r9,r10,r11,r12);
	return r8;
}

hl_urho3d_color* urho3d__TColor_TColor_Impl__toColor(hl_urho3d_tcolor* r0) {
	hl_urho3d_color *r1;
	r1 = Urho3D__math_tcolor_cast_to_color(r0);
	return r1;
}

hl_urho3d_tcolor* urho3d__TColor_TColor_Impl__fromColor(hl_urho3d_color* r0) {
	hl_urho3d_tcolor *r1;
	r1 = Urho3D__math_tcolor_cast_from_color(r0);
	return r1;
}

