// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <samplygame/Aircraft.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
#include <urho3d/RigidBody.h>
#include <urho3d/CollisionShape.h>
urho3d__Node urho3d_Component_get_node(urho3d__Component);
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
extern String s$RigidBody;
extern hl_type t$urho3d_RigidBody;
void urho3d_RigidBody_new(urho3d__RigidBody,hl_urho3d_physics_rigid_body*);
float urho3d_RigidBody_set_mass(urho3d__RigidBody,float);
bool urho3d_RigidBody_set_kinematic(urho3d__RigidBody,bool);
int urho3d_RigidBody_set_collisionMask(urho3d__RigidBody,int);
extern String s$CollisionShape;
extern hl_type t$urho3d_CollisionShape;
void urho3d_CollisionShape_new(urho3d__CollisionShape,hl_urho3d_physics_collision_shape*);
extern String s$NodeCollisionStart;
extern String s$HandleNodeCollision;
void urho3d_Component_SubscribeToEvent(urho3d__Component,hl_urho3d_core_object*,hl_urho3d_stringhash*,String);
#include <hl/types/ArrayDyn.h>
#include <hl/types/ArrayObj.h>
#include <samplygame/Weapon.h>
#include <haxe/ds/StringMap.h>
#include <samplygame/Globals.h>
extern String s$OtherNode;
extern hl_type t$urho3d_Node;
void urho3d_Node_new(urho3d__Node,hl_urho3d_scene_node*);
extern String s$OtherBody;
extern String s$Body;
hl_urho3d_tvariantmap* urho3d_Node_get_vars(urho3d__Node);
extern String s$node;
extern hl_type t$_dyn;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
#include <hl/types/ArrayBase.h>
hl__types__ArrayDyn hl_types_ArrayDyn_alloc(hl__types__ArrayBase,bool*);
int hl_types_ArrayDyn_push(hl__types__ArrayDyn,vdynamic*);
int hl_types_ArrayDyn_get_length(hl__types__ArrayDyn);
extern samplygame__$Weapon g$_samplygame_Weapon;
extern hl_type t$_bool;
extern hl_type t$samplygame_Weapon;
extern samplygame__$Globals g$_samplygame_Globals;
String urho3d_LogicComponent_get_className(urho3d__LogicComponent);
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
void samplygame_Aircraft_Explode(samplygame__Aircraft);
void samplygame_Aircraft_Hit(samplygame__Aircraft);
extern String s$Player;
int String___compare(String,vdynamic*);
#include <urho3d/StaticModel.h>
extern String s$StaticModel;
extern hl_type t$urho3d_StaticModel;
void urho3d_StaticModel_new(urho3d__StaticModel,hl_urho3d_graphics_staticmodel*);
hl_urho3d_graphics_material* urho3d_StaticModel_get_material(urho3d__StaticModel);
extern String s$MatSpecColor;
bool urho3d__ValueAnimation_ValueAnimation_Impl__SetKeyFrame(hl_urho3d_scene_value_animation*,double,hl_urho3d_tvariant*);
#include <haxe/ds/ObjectMap.h>
#include <urho3d/SoundSource.h>
#include <actions/ActionGroup.h>
#include <actions/ScaleTo.h>
#include <actions/DelayTime.h>
#include <actions/ActionID.h>
urho3d__Scene urho3d_Component_get_scene(urho3d__Component);
extern String s$;
hl_urho3d_scene_node_ptr* urho3d_Node_get_pointer(urho3d__Node);
extern hl_type t$hl_urho3d_scene_node_ptr;
void haxe_ds_ObjectMap_set(haxe__ds__ObjectMap,vdynamic*,vdynamic*);
extern String s$SoundSource;
extern hl_type t$urho3d_SoundSource;
void urho3d_SoundSource_new(urho3d__SoundSource,hl_urho3d_audio_sound_source*);
extern String s$Sounds_BigExplosion_wav;
void urho3d_SoundSource_Play(urho3d__SoundSource,hl_urho3d_audio_sound*,vdynamic*,vdynamic*,vdynamic*);
float urho3d_SoundSource_set_gain(urho3d__SoundSource,float);
int urho3d_SoundSource_set_autoRemoveMode(urho3d__SoundSource,int);
void actions_ActionManager_RemoveAllActions(urho3d__Node);
extern hl_type t$actions_ActionGroup;
void actions_ActionGroup_new(actions__ActionGroup);
extern hl_type t$actions_ScaleTo;
void actions_ScaleTo_new(actions__ScaleTo,double,double,vdynamic*,vdynamic*);
#include <actions/FiniteTimeAction.h>
void actions_ActionGroup_Push(actions__ActionGroup,actions__FiniteTimeAction,urho3d__Node);
extern hl_type t$actions_DelayTime;
void actions_DelayTime_new(actions__DelayTime,double);
void samplygame_Aircraft_ExplodeDone(samplygame__Aircraft,actions__ActionID);
extern hl_type t$fun_e4fcee9;
actions__ActionID actions_ActionManager_AddActions(hl__types__ArrayObj,actions__ActionGroup,vclosure*);
#include <urho3d/ParticleEmitter2D.h>
extern String s$ParticleEmitter2D;
extern hl_type t$urho3d_ParticleEmitter2D;
void urho3d_ParticleEmitter2D_new(urho3d__ParticleEmitter2D,hl_urho3d_urho2d_particle_emitter2d*);
extern String s$Particles_Explosion_pex;
hl_urho3d_urho2d_particle_effect2d* urho3d_ParticleEmitter2D_set_effect(urho3d__ParticleEmitter2D,hl_urho3d_urho2d_particle_effect2d*);
#include <actions/ActionDef.h>
#include <actions/FiniteTimeActionState.h>
void actions_ActionID_DeleteTargets(actions__ActionID);
void samplygame_Aircraft_DisableNode(samplygame__Aircraft,actions__ActionID);
actions__ActionID actions_ActionManager_AddAction(actions__ActionDef,actions__FiniteTimeAction,urho3d__Node,actions__FiniteTimeActionState,vclosure*);
bool urho3d_Node_set_enabled(urho3d__Node,bool);
bool haxe_ds_ObjectMap_remove(haxe__ds__ObjectMap,vdynamic*);
extern hl_type t$vrt_b840ca7;
extern hl_type t$String;
extern hl_type t$haxe_ds_StringMap;
bool haxe_ds_StringMap_remove(haxe__ds__StringMap,String);
vvirtual* haxe_ds_ObjectMap_iterator(haxe__ds__ObjectMap);
extern hl_type t$vrt_1cffe76;
extern hl_type t$fun_bf7849e;
extern hl_type t$fun_d937e10;
bool urho3d_Node_set_valid(urho3d__Node,bool);
vvirtual* haxe_ds_StringMap_iterator(haxe__ds__StringMap);
void urho3d_Node_CleanChildData(urho3d__Node);
void haxe_ds_StringMap_clear(haxe__ds__StringMap);
void haxe_ds_ObjectMap_clear(haxe__ds__ObjectMap);
void urho3d_LogicComponent_new(urho3d__LogicComponent,vdynamic*);

bool samplygame_Aircraft_IsAlive(samplygame__Aircraft r0) {
	bool r1;
	int r2, r3;
	r2 = r0->Health;
	r3 = 0;
	if( r2 > r3 ) goto label$49dff5b_1_5;
	r1 = false;
	goto label$49dff5b_1_6;
	label$49dff5b_1_5:
	r1 = true;
	label$49dff5b_1_6:
	return r1;
}

void samplygame_Aircraft_DelayedStart(samplygame__Aircraft r0) {
	return;
}

void samplygame_Aircraft_Play(samplygame__Aircraft r0) {
	hl_urho3d_stringhash *r32;
	String r9;
	hl_urho3d_physics_rigid_body *r11;
	hl_urho3d_scene_component *r6;
	bool r15;
	urho3d__RigidBody r12;
	hl_urho3d_core_object *r31;
	hl_urho3d_math_quaternion *r26;
	hl_urho3d_math_vector3 *r20;
	urho3d__Node r3, r5, r16;
	urho3d__CollisionShape r18;
	hl_urho3d_math_tquaternion *r28, *r29;
	urho3d___Context__$Context_Impl_ r8;
	float r13, r21, r22;
	urho3d_context *r7;
	hl_urho3d_scene_node *r4;
	double r14, r27, r30;
	hl_urho3d_math_tvector3 *r19, *r23, *r24, *r25;
	hl_urho3d_physics_collision_shape *r17;
	int r1, r10;
	r1 = r0->MaxHealth;
	r0->Health = r1;
	r3 = urho3d_Component_get_node(((urho3d__Component)r0));
	if( r3 == NULL ) hl_null_access();
	r4 = r3->abstractNode;
	if( !r4 ) goto label$49dff5b_3_14;
	r8 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r7 = r8->context;
	r4 = r3->abstractNode;
	r9 = (String)s$RigidBody;
	r1 = 0;
	r10 = 0;
	r6 = Urho3D__scene_node_create_component(r7,r4,r9,r1,r10);
	goto label$49dff5b_3_15;
	label$49dff5b_3_14:
	r6 = NULL;
	label$49dff5b_3_15:
	if( !r6 ) goto label$49dff5b_3_25;
	r8 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r7 = r8->context;
	r11 = Urho3D__physics_rigid_body_cast_from_component(r7,r6);
	if( !r11 ) goto label$49dff5b_3_23;
	r12 = (urho3d__RigidBody)hl_alloc_obj(&t$urho3d_RigidBody);
	urho3d_RigidBody_new(r12,r11);
	goto label$49dff5b_3_24;
	label$49dff5b_3_23:
	r12 = NULL;
	label$49dff5b_3_24:
	goto label$49dff5b_3_26;
	label$49dff5b_3_25:
	r12 = NULL;
	label$49dff5b_3_26:
	if( r12 == NULL ) hl_null_access();
	r1 = 1;
	r13 = (float)r1;
	r13 = urho3d_RigidBody_set_mass(r12,r13);
	r14 = (double)r13;
	r15 = true;
	r15 = urho3d_RigidBody_set_kinematic(r12,r15);
	r1 = r0->CollisionLayer;
	r1 = urho3d_RigidBody_set_collisionMask(r12,r1);
	r5 = urho3d_Component_get_node(((urho3d__Component)r0));
	if( r5 == NULL ) hl_null_access();
	r4 = r5->abstractNode;
	if( !r4 ) goto label$49dff5b_3_47;
	r8 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r7 = r8->context;
	r4 = r5->abstractNode;
	r9 = (String)s$CollisionShape;
	r1 = 0;
	r10 = 0;
	r6 = Urho3D__scene_node_create_component(r7,r4,r9,r1,r10);
	goto label$49dff5b_3_48;
	label$49dff5b_3_47:
	r6 = NULL;
	label$49dff5b_3_48:
	if( !r6 ) goto label$49dff5b_3_58;
	r8 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r7 = r8->context;
	r17 = Urho3D__physics_collision_shape_cast_from_component(r7,r6);
	if( !r17 ) goto label$49dff5b_3_56;
	r18 = (urho3d__CollisionShape)hl_alloc_obj(&t$urho3d_CollisionShape);
	urho3d_CollisionShape_new(r18,r17);
	goto label$49dff5b_3_57;
	label$49dff5b_3_56:
	r18 = NULL;
	label$49dff5b_3_57:
	goto label$49dff5b_3_59;
	label$49dff5b_3_58:
	r18 = NULL;
	label$49dff5b_3_59:
	r20 = r0->CollisionShapeSize;
	r19 = Urho3D__math_tvector3_cast_from_vector3(r20);
	r1 = 0;
	r13 = (float)r1;
	r1 = 0;
	r21 = (float)r1;
	r1 = 0;
	r22 = (float)r1;
	r20 = Urho3D__math_vector3_create(r13,r21,r22);
	r23 = Urho3D__math_tvector3_cast_from_vector3(r20);
	r14 = 0.;
	r24 = NULL;
	if( !r24 ) goto label$49dff5b_3_75;
	r13 = (float)r14;
	r26 = Urho3D__math_quaternion_create_fv(r13,r24);
	goto label$49dff5b_3_81;
	label$49dff5b_3_75:
	r13 = (float)r14;
	r27 = 0.;
	r21 = (float)r27;
	r27 = 0.;
	r22 = (float)r27;
	r26 = Urho3D__math_quaternion_create(r13,r21,r22);
	label$49dff5b_3_81:
	r28 = Urho3D__math_t_quaternion_cast_from_quaternion(r26);
	if( r23 ) goto label$49dff5b_3_91;
	r27 = 0.;
	r13 = (float)r27;
	r27 = 0.;
	r21 = (float)r27;
	r27 = 0.;
	r22 = (float)r27;
	r25 = Urho3D__math_tvector3_create(r13,r21,r22);
	r23 = r25;
	label$49dff5b_3_91:
	if( r28 ) goto label$49dff5b_3_105;
	r27 = 0.;
	r25 = NULL;
	if( !r25 ) goto label$49dff5b_3_98;
	r13 = (float)r27;
	r29 = Urho3D__math_t_quaternion_create_fv(r13,r25);
	goto label$49dff5b_3_104;
	label$49dff5b_3_98:
	r13 = (float)r27;
	r30 = 0.;
	r21 = (float)r30;
	r30 = 0.;
	r22 = (float)r30;
	r29 = Urho3D__math_t_quaternion_create(r13,r21,r22);
	label$49dff5b_3_104:
	r28 = r29;
	label$49dff5b_3_105:
	r8 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r7 = r8->context;
	if( r18 == NULL ) hl_null_access();
	r17 = r18->_abstract;
	Urho3D__physics_collision_shape_set_box(r7,r17,r19,r23,r28);
	((void (*)(samplygame__Aircraft))r0->$type->vobj_proto[2])(r0);
	r16 = urho3d_Component_get_node(((urho3d__Component)r0));
	r8 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r7 = r8->context;
	if( r16 == NULL ) hl_null_access();
	r4 = r16->abstractNode;
	r31 = Urho3D__core_object_cast_from_node(r7,r4);
	r9 = (String)s$NodeCollisionStart;
	r32 = Urho3D__create_stringhash(r9);
	r9 = (String)s$HandleNodeCollision;
	urho3d_Component_SubscribeToEvent(((urho3d__Component)r0),r31,r32,r9);
	return;
}

void samplygame_Aircraft_Init(samplygame__Aircraft r0) {
	return;
}

void samplygame_Aircraft_HandleNodeCollision(samplygame__Aircraft r0,hl_urho3d_stringhash* r1,hl_urho3d_variantmap* r2) {
	samplygame__$Weapon r36;
	bool *r29;
	String r5, r41;
	hl_urho3d_physics_rigid_body *r15;
	haxe__ds__StringMap r38;
	hl__types__ArrayObj r28;
	samplygame__Weapon r37;
	hl_type *r26;
	hl_urho3d_scene_component *r12, *r14;
	hl_urho3d_tstringhash *r22;
	bool r19;
	urho3d__RigidBody r16, r18;
	hl_urho3d_core_object *r3, *r11, *r13, *r17;
	urho3d__Node r7, r21;
	hl_urho3d_tvariantmap *r20;
	hl_urho3d_tvariant *r4;
	urho3d___Context__$Context_Impl_ r10;
	samplygame__$Globals r39;
	urho3d_context *r9;
	hl_urho3d_scene_node *r8;
	hl__types__ArrayDyn r24, r33;
	vdynamic *r34, *r35, *r40;
	int r27, r30, r31, r32;
	varray *r23, *r25;
	r5 = (String)s$OtherNode;
	r4 = Urho3D__core_variantmap_get_key_string_value(r2,r5);
	r3 = Urho3D__tvariant_get_object(r4);
	r7 = (urho3d__Node)hl_alloc_obj(&t$urho3d_Node);
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r8 = Urho3D__core_object_cast_to_node(r9,r3);
	urho3d_Node_new(r7,r8);
	r5 = (String)s$OtherBody;
	r4 = Urho3D__core_variantmap_get_key_string_value(r2,r5);
	r11 = Urho3D__tvariant_get_object(r4);
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r12 = Urho3D__core_object_cast_to_component(r9,r11);
	if( !r12 ) goto label$49dff5b_5_24;
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r15 = Urho3D__physics_rigid_body_cast_from_component(r9,r12);
	if( !r15 ) goto label$49dff5b_5_22;
	r16 = (urho3d__RigidBody)hl_alloc_obj(&t$urho3d_RigidBody);
	urho3d_RigidBody_new(r16,r15);
	goto label$49dff5b_5_23;
	label$49dff5b_5_22:
	r16 = NULL;
	label$49dff5b_5_23:
	goto label$49dff5b_5_25;
	label$49dff5b_5_24:
	r16 = NULL;
	label$49dff5b_5_25:
	r5 = (String)s$Body;
	r4 = Urho3D__core_variantmap_get_key_string_value(r2,r5);
	r13 = Urho3D__tvariant_get_object(r4);
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r14 = Urho3D__core_object_cast_to_component(r9,r13);
	if( !r14 ) goto label$49dff5b_5_41;
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r15 = Urho3D__physics_rigid_body_cast_from_component(r9,r14);
	if( !r15 ) goto label$49dff5b_5_39;
	r18 = (urho3d__RigidBody)hl_alloc_obj(&t$urho3d_RigidBody);
	urho3d_RigidBody_new(r18,r15);
	goto label$49dff5b_5_40;
	label$49dff5b_5_39:
	r18 = NULL;
	label$49dff5b_5_40:
	goto label$49dff5b_5_42;
	label$49dff5b_5_41:
	r18 = NULL;
	label$49dff5b_5_42:
	r19 = samplygame_Aircraft_IsAlive(r0);
	if( !r19 ) goto label$49dff5b_5_135;
	r20 = urho3d_Node_get_vars(r7);
	r5 = (String)s$node;
	r22 = Urho3D__math_tstringhash_create(r5);
	r4 = Urho3D__core_tvariantmap_get_value(r20,r22);
	r17 = Urho3D__tvariant_get_object(r4);
	r21 = (urho3d__Node)hl_alloc_obj(&t$urho3d_Node);
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r8 = Urho3D__core_object_cast_to_node(r9,r17);
	urho3d_Node_new(r21,r8);
	r8 = r21->abstractNode;
	if( !r8 ) goto label$49dff5b_5_81;
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r8 = r21->abstractNode;
	r19 = true;
	r23 = Urho3D__scene_node_get_all_logic_components(r9,r8,r19);
	r26 = &t$_dyn;
	r27 = 0;
	r25 = hl_alloc_array(r26,r27);
	r28 = hl_types_ArrayObj_alloc(r25);
	r19 = true;
	r29 = &r19;
	r24 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r28),r29);
	if( !r23 ) goto label$49dff5b_5_79;
	r27 = 0;
	r30 = r23->size;
	label$49dff5b_5_71:
	if( r27 >= r30 ) goto label$49dff5b_5_79;
	r31 = r27;
	++r27;
	if( r24 == NULL ) hl_null_access();
	r34 = ((vdynamic**)(r23 + 1))[r31];
	r32 = hl_types_ArrayDyn_push(r24,r34);
	goto label$49dff5b_5_71;
	label$49dff5b_5_79:
	r33 = r24;
	goto label$49dff5b_5_89;
	label$49dff5b_5_81:
	r26 = &t$_dyn;
	r27 = 0;
	r23 = hl_alloc_array(r26,r27);
	r28 = hl_types_ArrayObj_alloc(r23);
	r19 = true;
	r29 = &r19;
	r24 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r28),r29);
	r33 = r24;
	label$49dff5b_5_89:
	r27 = 0;
	label$49dff5b_5_90:
	if( r33 == NULL ) hl_null_access();
	r31 = hl_types_ArrayDyn_get_length(r33);
	if( r27 >= r31 ) goto label$49dff5b_5_135;
	r34 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r33->$type->vobj_proto[0])(r33,r27);
	++r27;
	if( r34 == NULL ) hl_null_access();
	r35 = (vdynamic*)hl_dyn_getp((vdynamic*)r34,3655927/*IsA*/,&t$_dyn);
	if( r35 == NULL ) hl_null_access();
	r36 = (samplygame__$Weapon)g$_samplygame_Weapon;
	{
		vdynamic *args[] = {(vdynamic*)r36};
		r35 = (vdynamic*)hl_dyn_call((vclosure*)r35,args,1);
	}
	r19 = (bool)hl_dyn_casti(&r35,&t$_dyn,&t$_bool);
	if( !r19 ) goto label$49dff5b_5_134;
	r37 = (samplygame__Weapon)hl_dyn_castp(&r34,&t$_dyn,&t$samplygame_Weapon);
	r39 = (samplygame__$Globals)g$_samplygame_Globals;
	r38 = r39->damageMap;
	if( r38 == NULL ) hl_null_access();
	if( r37 == NULL ) hl_null_access();
	r5 = urho3d_LogicComponent_get_className(((urho3d__LogicComponent)r37));
	r35 = haxe_ds_StringMap_get(r38,r5);
	r40 = (vdynamic*)r35;
	r30 = r0->Health;
	r31 = r40 ? r40->v.i : 0;
	r30 = r30 - r31;
	r0->Health = r30;
	r30 = r0->Health;
	r31 = 0;
	if( r30 <= r31 ) goto label$49dff5b_5_120;
	r19 = false;
	goto label$49dff5b_5_121;
	label$49dff5b_5_120:
	r19 = true;
	label$49dff5b_5_121:
	if( !r19 ) goto label$49dff5b_5_124;
	samplygame_Aircraft_Explode(r0);
	goto label$49dff5b_5_128;
	label$49dff5b_5_124:
	r30 = r40 ? r40->v.i : 0;
	r31 = 0;
	if( r31 >= r30 ) goto label$49dff5b_5_128;
	samplygame_Aircraft_Hit(r0);
	label$49dff5b_5_128:
	((void (*)(samplygame__Weapon,samplygame__Aircraft,bool,urho3d__Node))r37->$type->vobj_proto[2])(r37,r0,r19,r7);
	r5 = r0->name;
	r41 = (String)s$Player;
	if( r5 != r41 && (!r5 || !r41 || String___compare(r5,(vdynamic*)r41) != 0) ) goto label$49dff5b_5_133;
	((void (*)(samplygame__Aircraft))r0->$type->vobj_proto[3])(r0);
	label$49dff5b_5_133:
	goto label$49dff5b_5_135;
	label$49dff5b_5_134:
	goto label$49dff5b_5_90;
	label$49dff5b_5_135:
	return;
}

void samplygame_Aircraft_SendHealthUpdateToSamplyGame(samplygame__Aircraft r0) {
	return;
}

void samplygame_Aircraft_Hit(samplygame__Aircraft r0) {
	String r7;
	hl_urho3d_color *r12, *r21;
	hl_urho3d_scene_value_animation *r22;
	hl_urho3d_scene_component *r4;
	urho3d__StaticModel r10;
	bool r8;
	urho3d__Node r2;
	hl_urho3d_tcolor *r20;
	hl_urho3d_tvariant *r18, *r19;
	hl_urho3d_graphics_material *r11;
	urho3d___Context__$Context_Impl_ r6;
	float r14, r15, r16, r17;
	urho3d_context *r5;
	hl_urho3d_scene_node *r3;
	double r23;
	hl_urho3d_graphics_staticmodel *r9;
	int r13;
	r2 = urho3d_Component_get_node(((urho3d__Component)r0));
	if( r2 == NULL ) hl_null_access();
	r3 = r2->abstractNode;
	if( !r3 ) goto label$49dff5b_7_11;
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r3 = r2->abstractNode;
	r7 = (String)s$StaticModel;
	r8 = false;
	r4 = Urho3D__scene_node_get_component(r5,r3,r7,r8);
	goto label$49dff5b_7_12;
	label$49dff5b_7_11:
	r4 = NULL;
	label$49dff5b_7_12:
	if( !r4 ) goto label$49dff5b_7_19;
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r9 = Urho3D__graphics_staticmodel_cast_from_component(r5,r4);
	r10 = (urho3d__StaticModel)hl_alloc_obj(&t$urho3d_StaticModel);
	urho3d_StaticModel_new(r10,r9);
	goto label$49dff5b_7_20;
	label$49dff5b_7_19:
	r10 = NULL;
	label$49dff5b_7_20:
	if( r10 == NULL ) hl_null_access();
	r11 = urho3d_StaticModel_get_material(r10);
	if( r11 ) goto label$49dff5b_7_24;
	return;
	label$49dff5b_7_24:
	r13 = 0;
	r14 = (float)r13;
	r13 = 0;
	r15 = (float)r13;
	r13 = 0;
	r16 = (float)r13;
	r13 = 0;
	r17 = (float)r13;
	r12 = Urho3D__math_create_color(r14,r15,r16,r17);
	r18 = Urho3D__create_tvariant();
	r20 = Urho3D__math_tcolor_cast_from_color(r12);
	Urho3D__tvariant_set_t_color(r18,r20);
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r7 = (String)s$MatSpecColor;
	Urho3D__graphics_material_set_shader_parameter(r5,r11,r7,r18);
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r22 = Urho3D__scene_value_animation_create(r5);
	r23 = 1.;
	r14 = (float)r23;
	r23 = 1.;
	r15 = (float)r23;
	r23 = 1.;
	r16 = (float)r23;
	r23 = 0.5;
	r17 = (float)r23;
	r12 = Urho3D__math_create_color(r14,r15,r16,r17);
	r18 = Urho3D__create_tvariant();
	r20 = Urho3D__math_tcolor_cast_from_color(r12);
	Urho3D__tvariant_set_t_color(r18,r20);
	r23 = 0.;
	r8 = urho3d__ValueAnimation_ValueAnimation_Impl__SetKeyFrame(r22,r23,r18);
	r13 = 0;
	r14 = (float)r13;
	r13 = 0;
	r15 = (float)r13;
	r13 = 0;
	r16 = (float)r13;
	r13 = 0;
	r17 = (float)r13;
	r21 = Urho3D__math_create_color(r14,r15,r16,r17);
	r19 = Urho3D__create_tvariant();
	r20 = Urho3D__math_tcolor_cast_from_color(r21);
	Urho3D__tvariant_set_t_color(r19,r20);
	r23 = 0.1000000000000000056;
	r8 = urho3d__ValueAnimation_ValueAnimation_Impl__SetKeyFrame(r22,r23,r19);
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r7 = (String)s$MatSpecColor;
	r13 = 1;
	r23 = 1.;
	r14 = (float)r23;
	Urho3D__graphics_material_set_shader_parameter_animation(r5,r11,r7,r22,r13,r14);
	return;
}

void samplygame_Aircraft_Explode(samplygame__Aircraft r0) {
	actions__ScaleTo r29;
	String r7;
	haxe__ds__ObjectMap r11;
	hl__types__ArrayObj r33;
	urho3d__SoundSource r17;
	hl_urho3d_scene_component *r15;
	hl_urho3d_scene_node_ptr *r12;
	bool r9;
	actions__DelayTime r31;
	hl_urho3d_audio_sound *r18;
	urho3d__Node r10, r13;
	urho3d__Scene r2;
	urho3d___Context__$Context_Impl_ r6;
	actions__ActionID r32;
	float r22, r26, r27;
	urho3d_context *r5;
	hl_urho3d_scene_node *r4;
	vclosure *r34;
	actions__ActionGroup r28;
	double r23, r30;
	hl_urho3d_math_tvector3 *r24, *r25;
	hl_urho3d_audio_sound_source *r16;
	vdynamic *r14, *r19, *r20, *r21;
	int r1, r8;
	r1 = 0;
	r0->Health = r1;
	r2 = urho3d_Component_get_scene(((urho3d__Component)r0));
	if( r2 == NULL ) hl_null_access();
	r4 = r2->abstractNode;
	if( !r4 ) goto label$49dff5b_8_24;
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r4 = r2->abstractNode;
	r7 = (String)s$;
	r1 = 0;
	r8 = 0;
	r9 = false;
	r4 = Urho3D__scene_node_create_child(r5,r4,r7,r1,r8,r9);
	r10 = (urho3d__Node)hl_alloc_obj(&t$urho3d_Node);
	urho3d_Node_new(r10,r4);
	r11 = r2->children_pointers_map;
	if( r11 == NULL ) hl_null_access();
	r12 = urho3d_Node_get_pointer(r10);
	if( r12 == NULL ) r14 = NULL; else {
		r14 = hl_alloc_dynamic(&t$hl_urho3d_scene_node_ptr);
		r14->v.ptr = r12;
	}
	haxe_ds_ObjectMap_set(r11,r14,((vdynamic*)r10));
	r10->_parent = ((urho3d__Node)r2);
	r13 = r10;
	goto label$49dff5b_8_26;
	label$49dff5b_8_24:
	r10 = NULL;
	r13 = r10;
	label$49dff5b_8_26:
	if( r10 == NULL ) hl_null_access();
	r4 = r10->abstractNode;
	if( !r4 ) goto label$49dff5b_8_37;
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r4 = r10->abstractNode;
	r7 = (String)s$SoundSource;
	r1 = 0;
	r8 = 0;
	r15 = Urho3D__scene_node_create_component(r5,r4,r7,r1,r8);
	goto label$49dff5b_8_38;
	label$49dff5b_8_37:
	r15 = NULL;
	label$49dff5b_8_38:
	if( !r15 ) goto label$49dff5b_8_48;
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r16 = Urho3D__audio_sound_source_cast_from_component(r5,r15);
	if( !r16 ) goto label$49dff5b_8_46;
	r17 = (urho3d__SoundSource)hl_alloc_obj(&t$urho3d_SoundSource);
	urho3d_SoundSource_new(r17,r16);
	goto label$49dff5b_8_47;
	label$49dff5b_8_46:
	r17 = NULL;
	label$49dff5b_8_47:
	goto label$49dff5b_8_49;
	label$49dff5b_8_48:
	r17 = NULL;
	label$49dff5b_8_49:
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r7 = (String)s$Sounds_BigExplosion_wav;
	r18 = Urho3D__audio_sound_create(r5,r7);
	if( !r18 ) goto label$49dff5b_8_65;
	if( r17 == NULL ) hl_null_access();
	r19 = NULL;
	r20 = NULL;
	r21 = NULL;
	urho3d_SoundSource_Play(r17,r18,r19,r20,r21);
	r23 = 0.5;
	r22 = (float)r23;
	r22 = urho3d_SoundSource_set_gain(r17,r22);
	r23 = (double)r22;
	r1 = 1;
	r1 = urho3d_SoundSource_set_autoRemoveMode(r17,r1);
	label$49dff5b_8_65:
	r10 = urho3d_Component_get_node(((urho3d__Component)r0));
	if( r10 == NULL ) hl_null_access();
	r4 = r10->abstractNode;
	if( !r4 ) goto label$49dff5b_8_74;
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r4 = r10->abstractNode;
	r25 = Urho3D__scene_node_get_world_position(r5,r4);
	goto label$49dff5b_8_81;
	label$49dff5b_8_74:
	r23 = 0.;
	r22 = (float)r23;
	r23 = 0.;
	r26 = (float)r23;
	r23 = 0.;
	r27 = (float)r23;
	r25 = Urho3D__math_tvector3_create(r22,r26,r27);
	label$49dff5b_8_81:
	if( r13 == NULL ) hl_null_access();
	r4 = r13->abstractNode;
	if( !r4 ) goto label$49dff5b_8_88;
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r4 = r13->abstractNode;
	Urho3D__scene_node_set_position(r5,r4,r25);
	label$49dff5b_8_88:
	((void (*)(samplygame__Aircraft,urho3d__Node))r0->$type->vobj_proto[4])(r0,r13);
	r10 = urho3d_Component_get_node(((urho3d__Component)r0));
	actions_ActionManager_RemoveAllActions(r10);
	r10 = urho3d_Component_get_node(((urho3d__Component)r0));
	r23 = 0.;
	r22 = (float)r23;
	r23 = 0.;
	r26 = (float)r23;
	r23 = 0.;
	r27 = (float)r23;
	r24 = Urho3D__math_tvector3_create(r22,r26,r27);
	if( r10 == NULL ) hl_null_access();
	r4 = r10->abstractNode;
	if( !r4 ) goto label$49dff5b_8_106;
	r6 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r5 = r6->context;
	r4 = r10->abstractNode;
	Urho3D__scene_node_set_scale(r5,r4,r24);
	label$49dff5b_8_106:
	r28 = (actions__ActionGroup)hl_alloc_obj(&t$actions_ActionGroup);
	actions_ActionGroup_new(r28);
	r29 = (actions__ScaleTo)hl_alloc_obj(&t$actions_ScaleTo);
	r23 = 1.;
	r30 = 0.;
	r19 = NULL;
	r20 = NULL;
	actions_ScaleTo_new(r29,r23,r30,r19,r20);
	actions_ActionGroup_Push(r28,((actions__FiniteTimeAction)r29),r13);
	r31 = (actions__DelayTime)hl_alloc_obj(&t$actions_DelayTime);
	r23 = 1.;
	actions_DelayTime_new(r31,r23);
	actions_ActionGroup_Push(r28,((actions__FiniteTimeAction)r31),r13);
	r33 = NULL;
	r34 = hl_alloc_closure_ptr(&t$fun_e4fcee9,samplygame_Aircraft_ExplodeDone,r0);
	r32 = actions_ActionManager_AddActions(r33,r28,r34);
	return;
}

void samplygame_Aircraft_OnExplode(samplygame__Aircraft r0,urho3d__Node r1) {
	hl_urho3d_urho2d_particle_effect2d *r17, *r18;
	String r12;
	urho3d__ParticleEmitter2D r16;
	hl_urho3d_scene_component *r11;
	hl_urho3d_urho2d_particle_emitter2d *r15;
	urho3d___Context__$Context_Impl_ r10;
	urho3d_context *r9;
	hl_urho3d_scene_node *r8;
	float r4, r5, r6;
	double r3;
	hl_urho3d_math_tvector3 *r2;
	int r13, r14;
	r3 = 2.;
	r4 = (float)r3;
	r3 = 2.;
	r5 = (float)r3;
	r3 = 2.;
	r6 = (float)r3;
	r2 = Urho3D__math_tvector3_create(r4,r5,r6);
	if( r1 == NULL ) hl_null_access();
	r8 = r1->abstractNode;
	if( !r8 ) goto label$49dff5b_9_14;
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r8 = r1->abstractNode;
	Urho3D__scene_node_set_scale(r9,r8,r2);
	label$49dff5b_9_14:
	r8 = r1->abstractNode;
	if( !r8 ) goto label$49dff5b_9_24;
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r8 = r1->abstractNode;
	r12 = (String)s$ParticleEmitter2D;
	r13 = 0;
	r14 = 0;
	r11 = Urho3D__scene_node_create_component(r9,r8,r12,r13,r14);
	goto label$49dff5b_9_25;
	label$49dff5b_9_24:
	r11 = NULL;
	label$49dff5b_9_25:
	if( !r11 ) goto label$49dff5b_9_35;
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r15 = Urho3D__urho2d_particle_emitter2d_cast_from_component(r9,r11);
	if( !r15 ) goto label$49dff5b_9_33;
	r16 = (urho3d__ParticleEmitter2D)hl_alloc_obj(&t$urho3d_ParticleEmitter2D);
	urho3d_ParticleEmitter2D_new(r16,r15);
	goto label$49dff5b_9_34;
	label$49dff5b_9_33:
	r16 = NULL;
	label$49dff5b_9_34:
	goto label$49dff5b_9_36;
	label$49dff5b_9_35:
	r16 = NULL;
	label$49dff5b_9_36:
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r12 = (String)s$Particles_Explosion_pex;
	r17 = Urho3D__urho2d_particle_effect2d_create(r9,r12);
	if( r16 == NULL ) hl_null_access();
	r18 = urho3d_ParticleEmitter2D_set_effect(r16,r17);
	return;
}

void samplygame_Aircraft_ExplodeDone(samplygame__Aircraft r0,actions__ActionID r1) {
	bool *r19;
	samplygame__$Weapon r5;
	hl__types__ArrayObj r18;
	hl_type *r16;
	actions__FiniteTimeActionState r29;
	bool r7, r13;
	actions__DelayTime r27;
	urho3d__Node r4, r9;
	urho3d___Context__$Context_Impl_ r12;
	actions__ActionDef r26;
	actions__ActionID r3;
	urho3d_context *r11;
	hl_urho3d_scene_node *r8;
	vclosure *r30;
	double r28;
	hl__types__ArrayDyn r14, r25;
	vdynamic *r6, *r23, *r24;
	int r17, r20, r21, r22;
	varray *r10, *r15;
	if( r1 == NULL ) hl_null_access();
	actions_ActionID_DeleteTargets(r1);
	r4 = urho3d_Component_get_node(((urho3d__Component)r0));
	r5 = (samplygame__$Weapon)g$_samplygame_Weapon;
	r6 = ((vdynamic*)r5);
	r7 = true;
	if( r4 == NULL ) hl_null_access();
	r8 = r4->abstractNode;
	if( !r8 ) goto label$49dff5b_10_40;
	r12 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r11 = r12->context;
	r8 = r4->abstractNode;
	r10 = Urho3D__scene_node_get_all_logic_components(r11,r8,r7);
	r16 = &t$_dyn;
	r17 = 0;
	r15 = hl_alloc_array(r16,r17);
	r18 = hl_types_ArrayObj_alloc(r15);
	r13 = true;
	r19 = &r13;
	r14 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r18),r19);
	if( !r10 ) goto label$49dff5b_10_38;
	r17 = 0;
	r20 = r10->size;
	label$49dff5b_10_23:
	if( r17 >= r20 ) goto label$49dff5b_10_38;
	r21 = r17;
	++r17;
	r23 = ((vdynamic**)(r10 + 1))[r21];
	if( r23 == NULL ) hl_null_access();
	r23 = (vdynamic*)hl_dyn_getp((vdynamic*)r23,3655927/*IsA*/,&t$_dyn);
	if( r23 == NULL ) hl_null_access();
	{
		vdynamic *args[] = {r6};
		r23 = (vdynamic*)hl_dyn_call((vclosure*)r23,args,1);
	}
	r13 = (bool)hl_dyn_casti(&r23,&t$_dyn,&t$_bool);
	if( !r13 ) goto label$49dff5b_10_37;
	if( r14 == NULL ) hl_null_access();
	r23 = ((vdynamic**)(r10 + 1))[r21];
	r22 = hl_types_ArrayDyn_push(r14,r23);
	label$49dff5b_10_37:
	goto label$49dff5b_10_23;
	label$49dff5b_10_38:
	r25 = r14;
	goto label$49dff5b_10_48;
	label$49dff5b_10_40:
	r16 = &t$_dyn;
	r17 = 0;
	r10 = hl_alloc_array(r16,r17);
	r18 = hl_types_ArrayObj_alloc(r10);
	r13 = true;
	r19 = &r13;
	r14 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r18),r19);
	r25 = r14;
	label$49dff5b_10_48:
	r17 = 0;
	label$49dff5b_10_49:
	if( r25 == NULL ) hl_null_access();
	r21 = hl_types_ArrayDyn_get_length(r25);
	if( r17 >= r21 ) goto label$49dff5b_10_60;
	r23 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r25->$type->vobj_proto[0])(r25,r17);
	++r17;
	if( r23 == NULL ) hl_null_access();
	r24 = (vdynamic*)hl_dyn_getp((vdynamic*)r23,389356711/*Stop*/,&t$_dyn);
	if( r24 == NULL ) hl_null_access();
	{
		r24 = (vdynamic*)hl_dyn_call((vclosure*)r24,NULL,0);
	}
	goto label$49dff5b_10_49;
	label$49dff5b_10_60:
	r26 = NULL;
	r27 = (actions__DelayTime)hl_alloc_obj(&t$actions_DelayTime);
	r28 = 5.;
	actions_DelayTime_new(r27,r28);
	r9 = urho3d_Component_get_node(((urho3d__Component)r0));
	r29 = NULL;
	r30 = hl_alloc_closure_ptr(&t$fun_e4fcee9,samplygame_Aircraft_DisableNode,r0);
	r3 = actions_ActionManager_AddAction(r26,((actions__FiniteTimeAction)r27),r9,r29,r30);
	return;
}

void samplygame_Aircraft_DisableNode(samplygame__Aircraft r0,actions__ActionID r1) {
	String r15, r19;
	haxe__ds__ObjectMap r10;
	vvirtual *r14, *r21, *r22, *r23, *r25;
	haxe__ds__StringMap r13;
	hl_urho3d_scene_node_ptr *r11;
	bool r2, r8;
	urho3d__Node r3, r6, r9, r24, r26;
	urho3d___Context__$Context_Impl_ r18;
	urho3d_context *r17;
	hl_urho3d_scene_node *r5, *r7;
	vdynamic *r12;
	int r20;
	vbyte *r16;
	r3 = urho3d_Component_get_node(((urho3d__Component)r0));
	if( r3 == NULL ) hl_null_access();
	r2 = false;
	r2 = urho3d_Node_set_enabled(r3,r2);
	r3 = urho3d_Component_get_node(((urho3d__Component)r0));
	if( r3 == NULL ) hl_null_access();
	r5 = r3->abstractNode;
	r7 = NULL;
	if( r5 != r7 ) goto label$49dff5b_11_11;
	r2 = false;
	goto label$49dff5b_11_12;
	label$49dff5b_11_11:
	r2 = true;
	label$49dff5b_11_12:
	r8 = true;
	if( r2 != r8 ) goto label$49dff5b_11_924;
	r6 = r3->_parent;
	if( !r6 ) goto label$49dff5b_11_498;
	r6 = r3->_parent;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->abstractNode;
	r7 = NULL;
	if( r5 != r7 ) goto label$49dff5b_11_23;
	r2 = false;
	goto label$49dff5b_11_24;
	label$49dff5b_11_23:
	r2 = true;
	label$49dff5b_11_24:
	r8 = true;
	if( r2 != r8 ) goto label$49dff5b_11_497;
	r5 = r3->abstractNode;
	r7 = NULL;
	if( r5 != r7 ) goto label$49dff5b_11_31;
	r2 = false;
	goto label$49dff5b_11_32;
	label$49dff5b_11_31:
	r2 = true;
	label$49dff5b_11_32:
	r8 = true;
	if( r2 != r8 ) goto label$49dff5b_11_497;
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r11 = urho3d_Node_get_pointer(r3);
	if( r11 == NULL ) r12 = NULL; else {
		r12 = hl_alloc_dynamic(&t$hl_urho3d_scene_node_ptr);
		r12->v.ptr = r11;
	}
	r2 = haxe_ds_ObjectMap_remove(r10,r12);
	r13 = r6->children_name_map;
	if( r13 ) goto label$49dff5b_11_43;
	r14 = NULL;
	goto label$49dff5b_11_47;
	label$49dff5b_11_43:
	r14 = r13->f$1;
	if( r14 ) goto label$49dff5b_11_47;
	r14 = hl_to_virtual(&t$vrt_b840ca7,(vdynamic*)r13);
	r13->f$1 = r14;
	label$49dff5b_11_47:
	r5 = r3->abstractNode;
	if( !r5 ) goto label$49dff5b_11_66;
	r15 = r3->_name;
	if( r15 ) goto label$49dff5b_11_64;
	r18 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r17 = r18->context;
	r5 = r3->abstractNode;
	r16 = Urho3D__scene_node_get_name(r17,r5);
	if( r16 ) goto label$49dff5b_11_58;
	r19 = NULL;
	goto label$49dff5b_11_63;
	label$49dff5b_11_58:
	r19 = (String)hl_alloc_obj(&t$String);
	r19->bytes = r16;
	r20 = 0;
	r20 = hl_ucs2length(r16,r20);
	r19->length = r20;
	label$49dff5b_11_63:
	r3->_name = r19;
	label$49dff5b_11_64:
	r19 = r3->_name;
	goto label$49dff5b_11_67;
	label$49dff5b_11_66:
	r19 = (String)s$;
	label$49dff5b_11_67:
	r13 = (haxe__ds__StringMap)hl_dyn_castp(&r14,&t$vrt_b840ca7,&t$haxe_ds_StringMap);
	if( r13 == NULL ) hl_null_access();
	r2 = haxe_ds_StringMap_remove(r13,r19);
	r18 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r17 = r18->context;
	r5 = r6->abstractNode;
	r7 = r3->abstractNode;
	Urho3D__scene_node_remove_child(r17,r5,r7);
	r10 = r3->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_79:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_228;
	if( hl_vfields(r22)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_89:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_98;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r2 = false;
	r2 = urho3d_Node_set_valid(r24,r2);
	goto label$49dff5b_11_89;
	label$49dff5b_11_98:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_103:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_112;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r2 = false;
	r2 = urho3d_Node_set_valid(r24,r2);
	goto label$49dff5b_11_103;
	label$49dff5b_11_112:
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_117:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_162;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_127:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_135;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$49dff5b_11_127;
	label$49dff5b_11_135:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_140:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_148;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$49dff5b_11_140;
	label$49dff5b_11_148:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r24->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$49dff5b_11_117;
	label$49dff5b_11_162:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_167:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_212;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_177:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_185;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$49dff5b_11_177;
	label$49dff5b_11_185:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_190:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_198;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$49dff5b_11_190;
	label$49dff5b_11_198:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r24->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$49dff5b_11_167;
	label$49dff5b_11_212:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r5 = NULL;
	r9->abstractNode = r5;
	goto label$49dff5b_11_79;
	label$49dff5b_11_228:
	if( r3 == NULL ) hl_null_access();
	r13 = r3->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_233:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_382;
	if( hl_vfields(r22)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_243:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_252;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r2 = false;
	r2 = urho3d_Node_set_valid(r24,r2);
	goto label$49dff5b_11_243;
	label$49dff5b_11_252:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_257:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_266;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r2 = false;
	r2 = urho3d_Node_set_valid(r24,r2);
	goto label$49dff5b_11_257;
	label$49dff5b_11_266:
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_271:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_316;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_281:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_289;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$49dff5b_11_281;
	label$49dff5b_11_289:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_294:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_302;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$49dff5b_11_294;
	label$49dff5b_11_302:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r24->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$49dff5b_11_271;
	label$49dff5b_11_316:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_321:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_366;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_331:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_339;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$49dff5b_11_331;
	label$49dff5b_11_339:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_344:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_352;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$49dff5b_11_344;
	label$49dff5b_11_352:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r24->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$49dff5b_11_321;
	label$49dff5b_11_366:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r5 = NULL;
	r9->abstractNode = r5;
	goto label$49dff5b_11_233;
	label$49dff5b_11_382:
	if( r3 == NULL ) hl_null_access();
	r10 = r3->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_387:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_432;
	if( hl_vfields(r22)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_397:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_405;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$49dff5b_11_397;
	label$49dff5b_11_405:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_410:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_418;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$49dff5b_11_410;
	label$49dff5b_11_418:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$49dff5b_11_387;
	label$49dff5b_11_432:
	if( r3 == NULL ) hl_null_access();
	r13 = r3->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_437:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_482;
	if( hl_vfields(r22)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_447:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_455;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$49dff5b_11_447;
	label$49dff5b_11_455:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_460:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_468;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$49dff5b_11_460;
	label$49dff5b_11_468:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$49dff5b_11_437;
	label$49dff5b_11_482:
	if( r3 == NULL ) hl_null_access();
	r13 = r3->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r3->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r3->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r3->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r5 = NULL;
	r3->abstractNode = r5;
	label$49dff5b_11_497:
	goto label$49dff5b_11_924;
	label$49dff5b_11_498:
	r18 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r17 = r18->context;
	r5 = r3->abstractNode;
	Urho3D__scene_node_remove(r17,r5);
	r10 = r3->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_506:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_655;
	if( hl_vfields(r22)[1] ) r6 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r6 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r6 == NULL ) hl_null_access();
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_516:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_525;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r2 = false;
	r2 = urho3d_Node_set_valid(r9,r2);
	goto label$49dff5b_11_516;
	label$49dff5b_11_525:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_530:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_539;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r2 = false;
	r2 = urho3d_Node_set_valid(r9,r2);
	goto label$49dff5b_11_530;
	label$49dff5b_11_539:
	if( r6 == NULL ) hl_null_access();
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_544:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_589;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_554:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_562;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$49dff5b_11_554;
	label$49dff5b_11_562:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_567:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_575;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$49dff5b_11_567;
	label$49dff5b_11_575:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$49dff5b_11_544;
	label$49dff5b_11_589:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_594:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_639;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_604:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_612;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$49dff5b_11_604;
	label$49dff5b_11_612:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_617:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_625;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$49dff5b_11_617;
	label$49dff5b_11_625:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$49dff5b_11_594;
	label$49dff5b_11_639:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r6->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r5 = NULL;
	r6->abstractNode = r5;
	goto label$49dff5b_11_506;
	label$49dff5b_11_655:
	if( r3 == NULL ) hl_null_access();
	r13 = r3->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_660:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_809;
	if( hl_vfields(r22)[1] ) r6 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r6 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r6 == NULL ) hl_null_access();
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_670:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_679;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r2 = false;
	r2 = urho3d_Node_set_valid(r9,r2);
	goto label$49dff5b_11_670;
	label$49dff5b_11_679:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_684:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_693;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r2 = false;
	r2 = urho3d_Node_set_valid(r9,r2);
	goto label$49dff5b_11_684;
	label$49dff5b_11_693:
	if( r6 == NULL ) hl_null_access();
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_698:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_743;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_708:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_716;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$49dff5b_11_708;
	label$49dff5b_11_716:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_721:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_729;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$49dff5b_11_721;
	label$49dff5b_11_729:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$49dff5b_11_698;
	label$49dff5b_11_743:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_748:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_793;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_758:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_766;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$49dff5b_11_758;
	label$49dff5b_11_766:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_771:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_779;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$49dff5b_11_771;
	label$49dff5b_11_779:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$49dff5b_11_748;
	label$49dff5b_11_793:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r6->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r5 = NULL;
	r6->abstractNode = r5;
	goto label$49dff5b_11_660;
	label$49dff5b_11_809:
	if( r3 == NULL ) hl_null_access();
	r10 = r3->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_814:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_859;
	if( hl_vfields(r22)[1] ) r6 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r6 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r6 == NULL ) hl_null_access();
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_824:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_832;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r9);
	goto label$49dff5b_11_824;
	label$49dff5b_11_832:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_837:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_845;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r9);
	goto label$49dff5b_11_837;
	label$49dff5b_11_845:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r6->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$49dff5b_11_814;
	label$49dff5b_11_859:
	if( r3 == NULL ) hl_null_access();
	r13 = r3->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_864:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_909;
	if( hl_vfields(r22)[1] ) r6 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r6 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r6 == NULL ) hl_null_access();
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_874:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_882;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r9);
	goto label$49dff5b_11_874;
	label$49dff5b_11_882:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$49dff5b_11_887:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r2 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r2 = (bool)ret.v.i;
	}
	if( !r2 ) goto label$49dff5b_11_895;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r9);
	goto label$49dff5b_11_887;
	label$49dff5b_11_895:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r6->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$49dff5b_11_864;
	label$49dff5b_11_909:
	if( r3 == NULL ) hl_null_access();
	r13 = r3->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r3->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r3->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r3->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r5 = NULL;
	r3->abstractNode = r5;
	label$49dff5b_11_924:
	return;
}

void samplygame_Aircraft_new(samplygame__Aircraft r0,vdynamic* r1) {
	String r2;
	hl_urho3d_math_vector3 *r3;
	float r5, r6, r7;
	double r4;
	int r8;
	r2 = (String)s$;
	r0->name = r2;
	r4 = 1.199999999999999956;
	r5 = (float)r4;
	r4 = 1.199999999999999956;
	r6 = (float)r4;
	r4 = 1.199999999999999956;
	r7 = (float)r4;
	r3 = Urho3D__math_vector3_create(r5,r6,r7);
	r0->CollisionShapeSize = r3;
	r8 = 4;
	r0->CollisionLayer = r8;
	r8 = 0;
	r0->level = r8;
	r8 = 30;
	r0->MaxHealth = r8;
	urho3d_LogicComponent_new(((urho3d__LogicComponent)r0),r1);
	return;
}

