// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_TVariantMap/TVariantMap_Impl_.h>
#include <hl/natives.h>

hl_urho3d_tvariantmap* urho3d__TVariantMap_TVariantMap_Impl___new() {
	hl_urho3d_tvariantmap *r0;
	r0 = Urho3D__core_tvariantmap_create();
	return r0;
}

hl_urho3d_tvariant* urho3d__TVariantMap_TVariantMap_Impl__getValue(hl_urho3d_tvariantmap* r0,hl_urho3d_tstringhash* r1) {
	hl_urho3d_tvariant *r2;
	r2 = Urho3D__core_tvariantmap_get_value(r0,r1);
	return r2;
}

hl_urho3d_tvariant* urho3d__TVariantMap_TVariantMap_Impl__setKeyValue(hl_urho3d_tvariantmap* r0,hl_urho3d_tstringhash* r1,hl_urho3d_tvariant* r2) {
	hl_urho3d_tvariant *r3;
	r3 = Urho3D__core_tvariantmap_set_key_value(r0,r1,r2);
	return r3;
}

