// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_urho3d___IntVector2__IntVector2_Impl_
#define INC_urho3d___IntVector2__IntVector2_Impl_
typedef struct _urho3d___IntVector2__$IntVector2_Impl_ *urho3d___IntVector2__$IntVector2_Impl_;
typedef struct _urho3d___IntVector2__IntVector2_Impl_ *urho3d___IntVector2__IntVector2_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>


struct _urho3d___IntVector2__$IntVector2_Impl_ {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* _new;
	vclosure* toString;
	vclosure* fromStructVector2;
	vclosure* isequal;
	vclosure* isnotequal;
	vclosure* add;
	vclosure* add2;
	vclosure* sub;
	vclosure* sub2;
	vclosure* mul;
	vclosure* mul2;
	vclosure* neg;
	vclosure* preneg;
	vclosure* postneg;
	vclosure* preadd;
	vclosure* postadd;
	vclosure* get_x;
	vclosure* set_x;
	vclosure* get_y;
	vclosure* set_y;
};
struct _urho3d___IntVector2__IntVector2_Impl_ {
	hl_type *$type;
};
#endif

