// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_Node/PodNode_Impl_.h>
#include <hl/natives.h>

hl_urho3d_scene_pod_node* urho3d__Node_PodNode_Impl___new() {
	hl_urho3d_scene_pod_node *r0;
	r0 = NULL;
	return r0;
}

