// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <samplygame/BigWhiteCube.h>
void samplygame_Weapon_new(samplygame__Weapon,vdynamic*);
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
#include <haxe/ds/ObjectMap.h>
#include <urho3d/StaticModel.h>
#include <urho3d/ParticleEmitter2D.h>
#include <actions/BezierConfig.h>
#include <actions/ActionGroup.h>
#include <actions/RotateBy.h>
#include <actions/BezierBy.h>
#include <actions/Sequence.h>
#include <actions/DelayTime.h>
#include <hl/types/ArrayObj.h>
#include <actions/ActionID.h>
urho3d__Node samplygame_Weapon_CreateRigidBullet(samplygame__Weapon,bool,hl_urho3d_math_vector3*);
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
extern String s$;
extern hl_type t$urho3d_Node;
void urho3d_Node_new(urho3d__Node,hl_urho3d_scene_node*);
hl_urho3d_scene_node_ptr* urho3d_Node_get_pointer(urho3d__Node);
extern hl_type t$hl_urho3d_scene_node_ptr;
void haxe_ds_ObjectMap_set(haxe__ds__ObjectMap,vdynamic*,vdynamic*);
extern String s$StaticModel;
extern hl_type t$urho3d_StaticModel;
void urho3d_StaticModel_new(urho3d__StaticModel,hl_urho3d_graphics_staticmodel*);
extern String s$Models_Box_mdl;
hl_urho3d_graphics_model* urho3d_StaticModel_set_model(urho3d__StaticModel,hl_urho3d_graphics_model*);
extern hl_type t$_f64;
double urho3d_LogicComponent_Random(urho3d__LogicComponent,vdynamic*,vdynamic*);
extern String s$ParticleEmitter2D;
extern hl_type t$urho3d_ParticleEmitter2D;
void urho3d_ParticleEmitter2D_new(urho3d__ParticleEmitter2D,hl_urho3d_urho2d_particle_emitter2d*);
extern String s$Particles_Explosion_pex;
hl_urho3d_urho2d_particle_effect2d* urho3d_ParticleEmitter2D_set_effect(urho3d__ParticleEmitter2D,hl_urho3d_urho2d_particle_effect2d*);
extern hl_type t$actions_BezierConfig;
void actions_BezierConfig_new(actions__BezierConfig);
extern hl_type t$actions_ActionGroup;
void actions_ActionGroup_new(actions__ActionGroup);
extern hl_type t$actions_RotateBy;
void actions_RotateBy_new(actions__RotateBy,double,double,vdynamic*,vdynamic*);
#include <actions/FiniteTimeAction.h>
void actions_ActionGroup_Push(actions__ActionGroup,actions__FiniteTimeAction,urho3d__Node);
extern hl_type t$actions_BezierBy;
void actions_BezierBy_new(actions__BezierBy,double,actions__BezierConfig);
extern hl_type t$actions_Sequence;
extern hl_type t$actions_DelayTime;
void actions_DelayTime_new(actions__DelayTime,double);
void actions_Sequence_new(actions__Sequence,actions__FiniteTimeAction,actions__FiniteTimeAction,hl__types__ArrayObj);
void samplygame_BigWhiteCube_bulletNodeRemove(samplygame__BigWhiteCube,actions__ActionID);
extern hl_type t$fun_a0af39e;
actions__ActionID actions_ActionManager_AddActions(hl__types__ArrayObj,actions__ActionGroup,vclosure*);
void actions_ActionID_DeleteTargets(actions__ActionID);

void samplygame_BigWhiteCube_new(samplygame__BigWhiteCube r0) {
	vdynamic *r2;
	int r3;
	r2 = NULL;
	samplygame_Weapon_new(((samplygame__Weapon)r0),r2);
	r3 = 3000;
	r0->ReloadDuration = r3;
	r3 = 20;
	r0->Damage = r3;
	return;
}

void samplygame_BigWhiteCube_OnFire(samplygame__BigWhiteCube r0,bool r1) {
	hl_urho3d_urho2d_particle_effect2d *r33, *r34;
	String r10;
	urho3d__ParticleEmitter2D r32;
	haxe__ds__ObjectMap r13;
	hl__types__ArrayObj r44;
	hl_urho3d_scene_component *r17;
	hl_urho3d_scene_node_ptr *r15;
	actions__BezierConfig r35;
	hl_urho3d_urho2d_particle_emitter2d *r31;
	urho3d__StaticModel r19;
	bool r3;
	actions__DelayTime r43;
	hl_urho3d_math_vector3 *r4, *r36, *r37;
	urho3d__Node r2, r7, r14;
	hl_urho3d_math_tquaternion *r27;
	urho3d___Context__$Context_Impl_ r9;
	actions__BezierBy r41;
	actions__ActionID r45;
	actions__Sequence r42;
	float r24, r25, r26;
	urho3d_context *r8;
	hl_urho3d_scene_node *r6;
	vclosure *r46;
	actions__RotateBy r39;
	actions__ActionGroup r38;
	double r23, r30, r40;
	hl_urho3d_graphics_staticmodel *r18;
	hl_urho3d_math_tvector3 *r22;
	vdynamic *r16, *r28, *r29;
	hl_urho3d_graphics_model *r20, *r21;
	int r11, r12;
	r4 = NULL;
	r2 = samplygame_Weapon_CreateRigidBullet(((samplygame__Weapon)r0),r1,r4);
	if( r2 == NULL ) hl_null_access();
	r6 = r2->abstractNode;
	if( !r6 ) goto label$56eab30_2_23;
	r9 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r8 = r9->context;
	r6 = r2->abstractNode;
	r10 = (String)s$;
	r11 = 0;
	r12 = 0;
	r3 = false;
	r6 = Urho3D__scene_node_create_child(r8,r6,r10,r11,r12,r3);
	r7 = (urho3d__Node)hl_alloc_obj(&t$urho3d_Node);
	urho3d_Node_new(r7,r6);
	r13 = r2->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r15 = urho3d_Node_get_pointer(r7);
	if( r15 == NULL ) r16 = NULL; else {
		r16 = hl_alloc_dynamic(&t$hl_urho3d_scene_node_ptr);
		r16->v.ptr = r15;
	}
	haxe_ds_ObjectMap_set(r13,r16,((vdynamic*)r7));
	r7->_parent = r2;
	r14 = r7;
	goto label$56eab30_2_25;
	label$56eab30_2_23:
	r7 = NULL;
	r14 = r7;
	label$56eab30_2_25:
	if( r7 == NULL ) hl_null_access();
	r6 = r7->abstractNode;
	if( !r6 ) goto label$56eab30_2_36;
	r9 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r8 = r9->context;
	r6 = r7->abstractNode;
	r10 = (String)s$StaticModel;
	r11 = 0;
	r12 = 0;
	r17 = Urho3D__scene_node_create_component(r8,r6,r10,r11,r12);
	goto label$56eab30_2_37;
	label$56eab30_2_36:
	r17 = NULL;
	label$56eab30_2_37:
	if( !r17 ) goto label$56eab30_2_44;
	r9 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r8 = r9->context;
	r18 = Urho3D__graphics_staticmodel_cast_from_component(r8,r17);
	r19 = (urho3d__StaticModel)hl_alloc_obj(&t$urho3d_StaticModel);
	urho3d_StaticModel_new(r19,r18);
	goto label$56eab30_2_45;
	label$56eab30_2_44:
	r19 = NULL;
	label$56eab30_2_45:
	r9 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r8 = r9->context;
	r10 = (String)s$Models_Box_mdl;
	r20 = Urho3D__graphics_model_create(r8,r10);
	if( r19 == NULL ) hl_null_access();
	r21 = urho3d_StaticModel_set_model(r19,r20);
	r23 = 2.;
	r24 = (float)r23;
	r23 = 2.;
	r25 = (float)r23;
	r23 = 2.;
	r26 = (float)r23;
	r22 = Urho3D__math_tvector3_create(r24,r25,r26);
	r6 = r7->abstractNode;
	if( !r6 ) goto label$56eab30_2_64;
	r9 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r8 = r9->context;
	r6 = r7->abstractNode;
	Urho3D__scene_node_set_scale(r8,r6,r22);
	label$56eab30_2_64:
	r22 = NULL;
	if( !r22 ) goto label$56eab30_2_70;
	r11 = 45;
	r24 = (float)r11;
	r27 = Urho3D__math_t_quaternion_create_fv(r24,r22);
	goto label$56eab30_2_77;
	label$56eab30_2_70:
	r11 = 45;
	r24 = (float)r11;
	r11 = 0;
	r25 = (float)r11;
	r11 = 0;
	r26 = (float)r11;
	r27 = Urho3D__math_t_quaternion_create(r24,r25,r26);
	label$56eab30_2_77:
	r6 = r7->abstractNode;
	if( !r6 ) goto label$56eab30_2_84;
	r9 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r8 = r9->context;
	r6 = r7->abstractNode;
	r11 = 0;
	Urho3D__scene_node_rotate(r8,r6,r27,r11);
	label$56eab30_2_84:
	r23 = 0.1499999999999999944;
	r28 = hl_alloc_dynamic(&t$_f64);
	r28->v.d = r23;
	r23 = 0.2000000000000000111;
	r29 = hl_alloc_dynamic(&t$_f64);
	r29->v.d = r23;
	r23 = urho3d_LogicComponent_Random(((urho3d__LogicComponent)r0),r28,r29);
	r24 = (float)r23;
	r25 = (float)r23;
	r26 = (float)r23;
	r22 = Urho3D__math_tvector3_create(r24,r25,r26);
	r6 = r2->abstractNode;
	if( !r6 ) goto label$56eab30_2_99;
	r9 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r8 = r9->context;
	r6 = r2->abstractNode;
	Urho3D__scene_node_set_scale(r8,r6,r22);
	label$56eab30_2_99:
	r6 = r2->abstractNode;
	if( !r6 ) goto label$56eab30_2_118;
	r9 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r8 = r9->context;
	r6 = r2->abstractNode;
	r10 = (String)s$;
	r11 = 0;
	r12 = 0;
	r3 = false;
	r6 = Urho3D__scene_node_create_child(r8,r6,r10,r11,r12,r3);
	r7 = (urho3d__Node)hl_alloc_obj(&t$urho3d_Node);
	urho3d_Node_new(r7,r6);
	r13 = r2->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r15 = urho3d_Node_get_pointer(r7);
	if( r15 == NULL ) r16 = NULL; else {
		r16 = hl_alloc_dynamic(&t$hl_urho3d_scene_node_ptr);
		r16->v.ptr = r15;
	}
	haxe_ds_ObjectMap_set(r13,r16,((vdynamic*)r7));
	r7->_parent = r2;
	goto label$56eab30_2_119;
	label$56eab30_2_118:
	r7 = NULL;
	label$56eab30_2_119:
	r23 = 2.;
	r24 = (float)r23;
	r23 = 2.;
	r25 = (float)r23;
	r23 = 2.;
	r26 = (float)r23;
	r22 = Urho3D__math_tvector3_create(r24,r25,r26);
	if( r7 == NULL ) hl_null_access();
	r6 = r7->abstractNode;
	if( !r6 ) goto label$56eab30_2_133;
	r9 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r8 = r9->context;
	r6 = r7->abstractNode;
	Urho3D__scene_node_set_scale(r8,r6,r22);
	label$56eab30_2_133:
	r6 = r7->abstractNode;
	if( !r6 ) goto label$56eab30_2_143;
	r9 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r8 = r9->context;
	r6 = r7->abstractNode;
	r10 = (String)s$ParticleEmitter2D;
	r11 = 0;
	r12 = 0;
	r17 = Urho3D__scene_node_create_component(r8,r6,r10,r11,r12);
	goto label$56eab30_2_144;
	label$56eab30_2_143:
	r17 = NULL;
	label$56eab30_2_144:
	if( !r17 ) goto label$56eab30_2_154;
	r9 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r8 = r9->context;
	r31 = Urho3D__urho2d_particle_emitter2d_cast_from_component(r8,r17);
	if( !r31 ) goto label$56eab30_2_152;
	r32 = (urho3d__ParticleEmitter2D)hl_alloc_obj(&t$urho3d_ParticleEmitter2D);
	urho3d_ParticleEmitter2D_new(r32,r31);
	goto label$56eab30_2_153;
	label$56eab30_2_152:
	r32 = NULL;
	label$56eab30_2_153:
	goto label$56eab30_2_155;
	label$56eab30_2_154:
	r32 = NULL;
	label$56eab30_2_155:
	r9 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r8 = r9->context;
	r10 = (String)s$Particles_Explosion_pex;
	r33 = Urho3D__urho2d_particle_effect2d_create(r8,r10);
	if( r32 == NULL ) hl_null_access();
	r34 = urho3d_ParticleEmitter2D_set_effect(r32,r33);
	if( !r1 ) goto label$56eab30_2_164;
	r11 = 1;
	goto label$56eab30_2_165;
	label$56eab30_2_164:
	r11 = -1;
	label$56eab30_2_165:
	r35 = (actions__BezierConfig)hl_alloc_obj(&t$actions_BezierConfig);
	actions_BezierConfig_new(r35);
	r12 = 0;
	r24 = (float)r12;
	r23 = 3.;
	r30 = (double)r11;
	r23 = r23 * r30;
	r25 = (float)r23;
	r12 = 0;
	r26 = (float)r12;
	r4 = Urho3D__math_vector3_create(r24,r25,r26);
	r35->ControlPoint1 = r4;
	r23 = -3.;
	r28 = hl_alloc_dynamic(&t$_f64);
	r28->v.d = r23;
	r23 = 3.;
	r29 = hl_alloc_dynamic(&t$_f64);
	r29->v.d = r23;
	r23 = urho3d_LogicComponent_Random(((urho3d__LogicComponent)r0),r28,r29);
	r24 = (float)r23;
	r12 = 5;
	r12 = r12 * r11;
	r25 = (float)r12;
	r12 = 0;
	r26 = (float)r12;
	r36 = Urho3D__math_vector3_create(r24,r25,r26);
	r35->ControlPoint2 = r36;
	r12 = 0;
	r24 = (float)r12;
	r12 = 12;
	r12 = r12 * r11;
	r25 = (float)r12;
	r12 = 0;
	r26 = (float)r12;
	r37 = Urho3D__math_vector3_create(r24,r25,r26);
	r35->EndPosition = r37;
	r38 = (actions__ActionGroup)hl_alloc_obj(&t$actions_ActionGroup);
	actions_ActionGroup_new(r38);
	r39 = (actions__RotateBy)hl_alloc_obj(&t$actions_RotateBy);
	r23 = 3.;
	r30 = 0.;
	r12 = 1000;
	r40 = (double)r12;
	r28 = hl_alloc_dynamic(&t$_f64);
	r28->v.d = r40;
	r12 = 0;
	r40 = (double)r12;
	r29 = hl_alloc_dynamic(&t$_f64);
	r29->v.d = r40;
	actions_RotateBy_new(r39,r23,r30,r28,r29);
	actions_ActionGroup_Push(r38,((actions__FiniteTimeAction)r39),r14);
	r41 = (actions__BezierBy)hl_alloc_obj(&t$actions_BezierBy);
	r23 = 4.;
	actions_BezierBy_new(r41,r23,r35);
	r42 = (actions__Sequence)hl_alloc_obj(&t$actions_Sequence);
	r43 = (actions__DelayTime)hl_alloc_obj(&t$actions_DelayTime);
	r23 = 5.;
	actions_DelayTime_new(r43,r23);
	r44 = NULL;
	actions_Sequence_new(r42,((actions__FiniteTimeAction)r41),((actions__FiniteTimeAction)r43),r44);
	actions_ActionGroup_Push(r38,((actions__FiniteTimeAction)r42),r2);
	r44 = NULL;
	r46 = hl_alloc_closure_ptr(&t$fun_a0af39e,samplygame_BigWhiteCube_bulletNodeRemove,r0);
	r45 = actions_ActionManager_AddActions(r44,r38,r46);
	return;
}

void samplygame_BigWhiteCube_bulletNodeRemove(samplygame__BigWhiteCube r0,actions__ActionID r1) {
	if( r1 == NULL ) hl_null_access();
	actions_ActionID_DeleteTargets(r1);
	return;
}

void samplygame_BigWhiteCube_OnHit(samplygame__BigWhiteCube r0,urho3d__LogicComponent r1,bool r2,urho3d__Node r3) {
	return;
}

