// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_actions__ActionManager
#define INC_actions__ActionManager
typedef struct _actions__$ActionManager *actions__$ActionManager;
typedef struct _actions__ActionManager *actions__ActionManager;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>
#include <urho3d/Node.h>
#include <actions/ActionGroup.h>
#include <actions/ActionID.h>
#include <actions/ActionDef.h>
#include <actions/FiniteTimeAction.h>
#include <actions/FiniteTimeActionState.h>


struct _actions__$ActionManager {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	hl__types__ArrayObj actions;
	vclosure* RemoveAllActions;
	vclosure* AddActions;
	vclosure* AddAction;
	vclosure* IsRunning;
	vclosure* Step;
};
struct _actions__ActionManager {
	hl_type *$type;
};
#endif

