// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_IntVector2/IntVector2_Impl_.h>
#include <hl/natives.h>
extern String s$IntVector2_;
String String___alloc__(vbyte*,int);
String String___add__(String,String);
extern String s$853ae90;
extern String s$9371d7a;
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
extern haxe__$Log g$_haxe_Log;
extern String s$fromStructVector2;
extern hl_type t$vrt_329ffa8;
extern String s$src_haxe_urho3d_IntVector2_hx;
extern hl_type t$String;
extern hl_type t$_i32;
extern String s$56cf1e1;
extern hl_type t$vrt_eaa6a3b;
extern hl_type t$_f64;

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl___new(int* r0,int* r1) {
	hl_urho3d_intvector2 *r4;
	int r2, r3;
	if( r0 ) goto label$8c149a3_1_3;
	r2 = 0;
	goto label$8c149a3_1_4;
	label$8c149a3_1_3:
	r2 = *r0;
	label$8c149a3_1_4:
	if( r1 ) goto label$8c149a3_1_7;
	r3 = 0;
	goto label$8c149a3_1_8;
	label$8c149a3_1_7:
	r3 = *r1;
	label$8c149a3_1_8:
	r4 = Urho3D__create_intvector2(r2,r3);
	return r4;
}

String urho3d__IntVector2_IntVector2_Impl__toString(hl_urho3d_intvector2* r0) {
	String r1, r5;
	int *r3;
	vbyte *r4;
	int r2;
	r1 = (String)s$IntVector2_;
	r2 = Urho3D__intvector2_get_x(r0);
	r3 = &r2;
	r4 = hl_itos(r2,r3);
	r5 = String___alloc__(r4,r2);
	r1 = String___add__(r1,r5);
	r5 = (String)s$853ae90;
	r1 = String___add__(r1,r5);
	r2 = Urho3D__intvector2_get_y(r0);
	r3 = &r2;
	r4 = hl_itos(r2,r3);
	r5 = String___alloc__(r4,r2);
	r1 = String___add__(r1,r5);
	r5 = (String)s$9371d7a;
	r1 = String___add__(r1,r5);
	return r1;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__fromStructVector2(vvirtual* r0) {
	String r4, r6;
	vvirtual *r5, *r8;
	hl_urho3d_intvector2 *r9;
	haxe__$Log r3;
	vclosure *r2;
	int r7, r10;
	r3 = (haxe__$Log)g$_haxe_Log;
	r2 = r3->trace;
	if( r2 == NULL ) hl_null_access();
	r4 = (String)s$fromStructVector2;
	r5 = hl_alloc_virtual(&t$vrt_329ffa8);
	r6 = (String)s$src_haxe_urho3d_IntVector2_hx;
	if( hl_vfields(r5)[1] ) *(String*)(hl_vfields(r5)[1]) = (String)r6; else hl_dyn_setp(r5->value,37969014/*fileName*/,&t$String,r6);
	r7 = 33;
	if( hl_vfields(r5)[2] ) *(int*)(hl_vfields(r5)[2]) = (int)r7; else hl_dyn_seti(r5->value,371360620/*lineNumber*/,&t$_i32,r7);
	r6 = (String)s$56cf1e1;
	if( hl_vfields(r5)[0] ) *(String*)(hl_vfields(r5)[0]) = (String)r6; else hl_dyn_setp(r5->value,-63073762/*className*/,&t$String,r6);
	r6 = (String)s$fromStructVector2;
	if( hl_vfields(r5)[3] ) *(String*)(hl_vfields(r5)[3]) = (String)r6; else hl_dyn_setp(r5->value,302979532/*methodName*/,&t$String,r6);
	r8 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r5);
	r2->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r2->fun)((vdynamic*)r2->value,((vdynamic*)r4),r8) : ((void (*)(vdynamic*,vvirtual*))r2->fun)(((vdynamic*)r4),r8);
	if( r0 == NULL ) hl_null_access();
	r7 = hl_vfields(r0)[0] ? (*(int*)(hl_vfields(r0)[0])) : (int)hl_dyn_geti(r0->value,120/*x*/,&t$_i32);
	r10 = hl_vfields(r0)[1] ? (*(int*)(hl_vfields(r0)[1])) : (int)hl_dyn_geti(r0->value,121/*y*/,&t$_i32);
	r9 = Urho3D__create_intvector2(r7,r10);
	return r9;
}

bool urho3d__IntVector2_IntVector2_Impl__isequal(hl_urho3d_intvector2* r0,hl_urho3d_intvector2* r1) {
	bool r4;
	int r2, r3;
	r2 = Urho3D__intvector2_get_x(r0);
	r3 = Urho3D__intvector2_get_x(r1);
	if( r2 != r3 ) goto label$8c149a3_4_10;
	r2 = Urho3D__intvector2_get_y(r0);
	r3 = Urho3D__intvector2_get_y(r1);
	if( r2 == r3 ) goto label$8c149a3_4_8;
	r4 = false;
	goto label$8c149a3_4_9;
	label$8c149a3_4_8:
	r4 = true;
	label$8c149a3_4_9:
	return r4;
	label$8c149a3_4_10:
	r4 = false;
	return r4;
}

bool urho3d__IntVector2_IntVector2_Impl__isnotequal(hl_urho3d_intvector2* r0,hl_urho3d_intvector2* r1) {
	bool r2;
	int r3, r4;
	r3 = Urho3D__intvector2_get_x(r0);
	r4 = Urho3D__intvector2_get_x(r1);
	if( r3 != r4 ) goto label$8c149a3_5_8;
	r3 = Urho3D__intvector2_get_y(r0);
	r4 = Urho3D__intvector2_get_y(r1);
	if( r3 != r4 ) goto label$8c149a3_5_8;
	r2 = true;
	goto label$8c149a3_5_9;
	label$8c149a3_5_8:
	r2 = false;
	label$8c149a3_5_9:
	r2 = !r2;
	return r2;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__add(hl_urho3d_intvector2* r0,hl_urho3d_intvector2* r1) {
	hl_urho3d_intvector2 *r3;
	int r2, r4, r5;
	r2 = Urho3D__intvector2_get_x(r0);
	r4 = Urho3D__intvector2_get_x(r1);
	r2 = r2 + r4;
	r4 = Urho3D__intvector2_get_y(r0);
	r5 = Urho3D__intvector2_get_y(r1);
	r4 = r4 + r5;
	r3 = Urho3D__create_intvector2(r2,r4);
	return r3;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__addTo(hl_urho3d_intvector2* r0,hl_urho3d_intvector2* r1) {
	int r2, r3;
	r2 = Urho3D__intvector2_get_x(r0);
	r3 = Urho3D__intvector2_get_x(r1);
	r2 = r2 + r3;
	r2 = Urho3D__intvector2_set_x(r0,r2);
	r2 = Urho3D__intvector2_get_y(r0);
	r3 = Urho3D__intvector2_get_y(r1);
	r2 = r2 + r3;
	r2 = Urho3D__intvector2_set_y(r0,r2);
	return r0;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__sub(hl_urho3d_intvector2* r0,hl_urho3d_intvector2* r1) {
	hl_urho3d_intvector2 *r3;
	int r2, r4, r5;
	r2 = Urho3D__intvector2_get_x(r0);
	r4 = Urho3D__intvector2_get_x(r1);
	r2 = r2 - r4;
	r4 = Urho3D__intvector2_get_y(r0);
	r5 = Urho3D__intvector2_get_y(r1);
	r4 = r4 - r5;
	r3 = Urho3D__create_intvector2(r2,r4);
	return r3;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__subFrom(hl_urho3d_intvector2* r0,hl_urho3d_intvector2* r1) {
	int r2, r3;
	r2 = Urho3D__intvector2_get_x(r0);
	r3 = Urho3D__intvector2_get_x(r1);
	r2 = r2 - r3;
	r2 = Urho3D__intvector2_set_x(r0,r2);
	r2 = Urho3D__intvector2_get_y(r0);
	r3 = Urho3D__intvector2_get_y(r1);
	r2 = r2 - r3;
	r2 = Urho3D__intvector2_set_y(r0,r2);
	return r0;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__mul(hl_urho3d_intvector2* r0,int r1) {
	hl_urho3d_intvector2 *r3;
	int r2, r4;
	r2 = Urho3D__intvector2_get_x(r0);
	r2 = r2 * r1;
	r4 = Urho3D__intvector2_get_y(r0);
	r4 = r4 * r1;
	r3 = Urho3D__create_intvector2(r2,r4);
	return r3;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__mulWith(hl_urho3d_intvector2* r0,int r1) {
	int r2;
	r2 = Urho3D__intvector2_get_x(r0);
	r2 = r2 * r1;
	r2 = Urho3D__intvector2_set_x(r0,r2);
	r2 = Urho3D__intvector2_get_y(r0);
	r2 = r2 * r1;
	r2 = Urho3D__intvector2_set_y(r0,r2);
	return r0;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__mulVector2(hl_urho3d_intvector2* r0,hl_urho3d_intvector2* r1) {
	hl_urho3d_intvector2 *r3;
	int r2, r4, r5;
	r2 = Urho3D__intvector2_get_x(r0);
	r4 = Urho3D__intvector2_get_x(r1);
	r2 = r2 * r4;
	r4 = Urho3D__intvector2_get_y(r0);
	r5 = Urho3D__intvector2_get_y(r1);
	r4 = r4 * r5;
	r3 = Urho3D__create_intvector2(r2,r4);
	return r3;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__mulWithVector2(hl_urho3d_intvector2* r0,hl_urho3d_intvector2* r1) {
	int r2, r3;
	r2 = Urho3D__intvector2_get_x(r0);
	r3 = Urho3D__intvector2_get_x(r1);
	r2 = r2 * r3;
	r2 = Urho3D__intvector2_set_x(r0,r2);
	r2 = Urho3D__intvector2_get_y(r0);
	r3 = Urho3D__intvector2_get_y(r1);
	r2 = r2 * r3;
	r2 = Urho3D__intvector2_set_y(r0,r2);
	return r0;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__div(hl_urho3d_intvector2* r0,double r1) {
	hl_urho3d_intvector2 *r4;
	double r2, r5;
	int r3, r6;
	r3 = Urho3D__intvector2_get_x(r0);
	r2 = (double)r3;
	r2 = r2 / r1;
	r3 = Urho3D__intvector2_get_y(r0);
	r5 = (double)r3;
	r5 = r5 / r1;
	r3 = (int)hl_dyn_casti(&r2,&t$_f64,&t$_i32);
	r6 = (int)hl_dyn_casti(&r5,&t$_f64,&t$_i32);
	r4 = Urho3D__create_intvector2(r3,r6);
	return r4;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__divWith(hl_urho3d_intvector2* r0,double r1) {
	double r2, r4;
	int r3;
	r3 = Urho3D__intvector2_get_x(r0);
	r2 = (double)r3;
	r2 = r2 / r1;
	r3 = Urho3D__intvector2_get_y(r0);
	r4 = (double)r3;
	r4 = r4 / r1;
	r3 = (int)hl_dyn_casti(&r2,&t$_f64,&t$_i32);
	r3 = Urho3D__intvector2_set_x(r0,r3);
	r3 = (int)hl_dyn_casti(&r4,&t$_f64,&t$_i32);
	r3 = Urho3D__intvector2_set_y(r0,r3);
	return r0;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__divVector2(hl_urho3d_intvector2* r0,hl_urho3d_intvector2* r1) {
	hl_urho3d_intvector2 *r4;
	double r2, r5, r6;
	int r3, r7;
	r3 = Urho3D__intvector2_get_x(r0);
	r2 = (double)r3;
	r3 = Urho3D__intvector2_get_x(r1);
	r5 = (double)r3;
	r2 = r2 / r5;
	r3 = Urho3D__intvector2_get_y(r0);
	r5 = (double)r3;
	r3 = Urho3D__intvector2_get_y(r1);
	r6 = (double)r3;
	r5 = r5 / r6;
	r3 = (int)hl_dyn_casti(&r2,&t$_f64,&t$_i32);
	r7 = (int)hl_dyn_casti(&r5,&t$_f64,&t$_i32);
	r4 = Urho3D__create_intvector2(r3,r7);
	return r4;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__divWithVector2(hl_urho3d_intvector2* r0,hl_urho3d_intvector2* r1) {
	double r2, r4, r5;
	int r3;
	r3 = Urho3D__intvector2_get_x(r0);
	r2 = (double)r3;
	r3 = Urho3D__intvector2_get_x(r1);
	r4 = (double)r3;
	r2 = r2 / r4;
	r3 = Urho3D__intvector2_get_y(r0);
	r4 = (double)r3;
	r3 = Urho3D__intvector2_get_y(r1);
	r5 = (double)r3;
	r4 = r4 / r5;
	r3 = (int)hl_dyn_casti(&r2,&t$_f64,&t$_i32);
	r3 = Urho3D__intvector2_set_x(r0,r3);
	r3 = (int)hl_dyn_casti(&r4,&t$_f64,&t$_i32);
	r3 = Urho3D__intvector2_set_y(r0,r3);
	return r0;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__neg(hl_urho3d_intvector2* r0) {
	int r1;
	r1 = Urho3D__intvector2_get_x(r0);
	r1 = -r1;
	r1 = Urho3D__intvector2_set_x(r0,r1);
	r1 = Urho3D__intvector2_get_y(r0);
	r1 = -r1;
	r1 = Urho3D__intvector2_set_y(r0,r1);
	return r0;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__preneg(hl_urho3d_intvector2* r0) {
	int r1, r2;
	r1 = Urho3D__intvector2_get_x(r0);
	r2 = 1;
	r1 = r1 - r2;
	r1 = Urho3D__intvector2_set_x(r0,r1);
	r1 = Urho3D__intvector2_set_x(r0,r1);
	r1 = Urho3D__intvector2_get_y(r0);
	r2 = 1;
	r1 = r1 - r2;
	r1 = Urho3D__intvector2_set_y(r0,r1);
	r1 = Urho3D__intvector2_set_y(r0,r1);
	return r0;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__postneg(hl_urho3d_intvector2* r0) {
	int r1, r2, r3;
	r1 = Urho3D__intvector2_get_x(r0);
	r3 = 1;
	r2 = r1 - r3;
	r2 = Urho3D__intvector2_set_x(r0,r2);
	r2 = Urho3D__intvector2_set_x(r0,r1);
	r1 = Urho3D__intvector2_get_y(r0);
	r3 = 1;
	r2 = r1 - r3;
	r2 = Urho3D__intvector2_set_y(r0,r2);
	r2 = Urho3D__intvector2_set_y(r0,r1);
	return r0;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__preadd(hl_urho3d_intvector2* r0) {
	int r1, r2;
	r1 = Urho3D__intvector2_get_x(r0);
	r2 = 1;
	r1 = r1 + r2;
	r1 = Urho3D__intvector2_set_x(r0,r1);
	r1 = Urho3D__intvector2_set_x(r0,r1);
	r1 = Urho3D__intvector2_get_y(r0);
	r2 = 1;
	r1 = r1 + r2;
	r1 = Urho3D__intvector2_set_y(r0,r1);
	r1 = Urho3D__intvector2_set_y(r0,r1);
	return r0;
}

hl_urho3d_intvector2* urho3d__IntVector2_IntVector2_Impl__postadd(hl_urho3d_intvector2* r0) {
	int r1, r2, r3;
	r1 = Urho3D__intvector2_get_x(r0);
	r3 = 1;
	r2 = r1 + r3;
	r2 = Urho3D__intvector2_set_x(r0,r2);
	r2 = Urho3D__intvector2_set_x(r0,r1);
	r1 = Urho3D__intvector2_get_y(r0);
	r3 = 1;
	r2 = r1 + r3;
	r2 = Urho3D__intvector2_set_y(r0,r2);
	r2 = Urho3D__intvector2_set_y(r0,r1);
	return r0;
}

int urho3d__IntVector2_IntVector2_Impl__get_x(hl_urho3d_intvector2* r0) {
	int r1;
	r1 = Urho3D__intvector2_get_x(r0);
	return r1;
}

int urho3d__IntVector2_IntVector2_Impl__set_x(hl_urho3d_intvector2* r0,int r1) {
	int r2;
	r2 = Urho3D__intvector2_set_x(r0,r1);
	return r2;
}

int urho3d__IntVector2_IntVector2_Impl__get_y(hl_urho3d_intvector2* r0) {
	int r1;
	r1 = Urho3D__intvector2_get_y(r0);
	return r1;
}

int urho3d__IntVector2_IntVector2_Impl__set_y(hl_urho3d_intvector2* r0,int r1) {
	int r2;
	r2 = Urho3D__intvector2_set_y(r0,r1);
	return r2;
}

