// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <actions/ExtraActionState.h>
#include <actions/ExtraAction.h>
#include <actions/FiniteTimeAction.h>
void actions_FiniteTimeActionState_new(actions__FiniteTimeActionState,actions__FiniteTimeAction,urho3d__Node);

void actions_ExtraActionState_new(actions__ExtraActionState r0,actions__ExtraAction r1,urho3d__Node r2) {
	actions_FiniteTimeActionState_new(((actions__FiniteTimeActionState)r0),((actions__FiniteTimeAction)r1),r2);
	return;
}

void actions_ExtraActionState_Step(actions__ExtraActionState r0,double r1) {
	return;
}

void actions_ExtraActionState_Update(actions__ExtraActionState r0,double r1) {
	return;
}

