// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/Type.h>
#include <hl/natives.h>
extern hl_bytes_map* g$__types__;
extern hl_type t$hl_Class;
extern hl_type t$_dyn;
extern hl_type t$String;
void Type_register(vbyte*,hl__BaseType);
#include <hl/types/ArrayObj.h>
extern hl_type t$hl_Enum;
extern hl_type t$hl_types_ArrayObj;
void hl_types_ArrayObj_new(hl__types__ArrayObj);
extern hl_type t$_i32;
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
extern hl_type t$hl_BaseType;
extern hl__Class g$_hl_Class;
bool Std_isOfType(vdynamic*,vdynamic*);
#include <hl/types/ArrayAccess.h>
extern hl_type t$hl_types_ArrayAccess;
extern hl_type t$hl_types_ArrayDyn;
void hl_types_ArrayDyn_new(hl__types__ArrayDyn);
hl__types__ArrayDyn hl_types_ArrayDyn_copy(hl__types__ArrayDyn);
void hl_types_ArrayDyn_unshift(hl__types__ArrayDyn,vdynamic*);
vdynamic* Reflect_callMethod(vdynamic*,vdynamic*,hl__types__ArrayDyn);

void Type_init() {
	hl_bytes_map *r1;
	r1 = hl_hballoc();
	g$__types__ = (hl_bytes_map*)r1;
	return;
}

hl__Class Type_initClass(hl_type* r0,hl_type* r1,vbyte* r2) {
	String r7;
	hl__Class r4;
	bool r6;
	vdynamic *r3;
	int r8;
	r3 = hl_alloc_obj(r0);
	r4 = (hl__Class)hl_dyn_castp(&r3,&t$_dyn,&t$hl_Class);
	r6 = hl_type_set_global(r1,((vdynamic*)r4));
	if( r4 == NULL ) hl_null_access();
	r4->__type__ = r1;
	r7 = (String)hl_alloc_obj(&t$String);
	r7->bytes = r2;
	r8 = 0;
	r8 = hl_ucs2length(r2,r8);
	r7->length = r8;
	r4->__name__ = r7;
	Type_register(r2,((hl__BaseType)r4));
	return r4;
}

hl__Enum Type_initEnum(hl_type* r0,hl_type* r1) {
	String r8;
	hl__types__ArrayObj r12;
	bool r16;
	hl_bytes_map *r10, *r11;
	hl__Enum r3;
	vdynamic *r2;
	int r9, r13, r14, r15;
	vbyte *r6, *r7;
	varray *r5;
	r2 = hl_alloc_obj(r0);
	r3 = (hl__Enum)hl_dyn_castp(&r2,&t$_dyn,&t$hl_Enum);
	if( r3 == NULL ) hl_null_access();
	r3->__type__ = r1;
	r5 = hl_type_enum_values(r1);
	r3->__evalues__ = r5;
	r6 = hl_type_name(r1);
	if( r6 ) goto label$9fea9d9_3_10;
	r8 = NULL;
	goto label$9fea9d9_3_15;
	label$9fea9d9_3_10:
	r8 = (String)hl_alloc_obj(&t$String);
	r8->bytes = r6;
	r9 = 0;
	r9 = hl_ucs2length(r6,r9);
	r8->length = r9;
	label$9fea9d9_3_15:
	r3->__ename__ = r8;
	r10 = hl_hballoc();
	r3->__emap__ = r10;
	r12 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r12);
	r3->__constructs__ = r12;
	r5 = hl_type_enum_fields(r1);
	r9 = 0;
	r13 = r5->size;
	label$9fea9d9_3_24:
	if( r9 >= r13 ) goto label$9fea9d9_3_42;
	r14 = r9;
	++r9;
	r7 = ((vbyte**)(r5 + 1))[r14];
	if( r3 == NULL ) hl_null_access();
	r11 = r3->__emap__;
	r2 = hl_alloc_dynamic(&t$_i32);
	r2->v.i = r14;
	hl_hbset(r11,r7,r2);
	r12 = r3->__constructs__;
	r8 = (String)hl_alloc_obj(&t$String);
	r8->bytes = r7;
	r15 = 0;
	r15 = hl_ucs2length(r7,r15);
	r8->length = r15;
	if( r12 == NULL ) hl_null_access();
	r15 = hl_types_ArrayObj_push(r12,((vdynamic*)r8));
	goto label$9fea9d9_3_24;
	label$9fea9d9_3_42:
	if( r3 == NULL ) hl_null_access();
	r8 = r3->__ename__;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->bytes;
	Type_register(r7,((hl__BaseType)r3));
	r16 = hl_type_set_global(r1,((vdynamic*)r3));
	return r3;
}

void Type_register(vbyte* r0,hl__BaseType r1) {
	hl_bytes_map *r3;
	r3 = (hl_bytes_map*)g$__types__;
	hl_hbset(r3,r0,((vdynamic*)r1));
	return;
}

hl__Class Type_resolveClass(String r0) {
	hl__BaseType r4;
	hl__Class r6;
	bool r5;
	hl_bytes_map *r2;
	vdynamic *r1;
	vbyte *r3;
	r2 = (hl_bytes_map*)g$__types__;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->bytes;
	r1 = hl_hbget(r2,r3);
	r4 = (hl__BaseType)hl_dyn_castp(&r1,&t$_dyn,&t$hl_BaseType);
	if( !r4 ) goto label$9fea9d9_5_9;
	r6 = (hl__Class)g$_hl_Class;
	r5 = Std_isOfType(((vdynamic*)r4),((vdynamic*)r6));
	if( r5 ) goto label$9fea9d9_5_11;
	label$9fea9d9_5_9:
	r6 = NULL;
	return r6;
	label$9fea9d9_5_11:
	r6 = (hl__Class)hl_dyn_castp(&r4,&t$hl_BaseType,&t$hl_Class);
	return r6;
}

vdynamic* Type_createInstance(hl__Class r0,hl__types__ArrayDyn r1) {
	hl_type *r3, *r5;
	hl__types__ArrayAccess r4;
	hl__types__ArrayDyn r6;
	vdynamic *r7, *r8, *r9;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->__type__;
	r4 = NULL;
	r5 = &t$hl_types_ArrayAccess;
	if( hl_same_type(r3,r5) != 0 ) {} else goto label$9fea9d9_6_8;
	r6 = (hl__types__ArrayDyn)hl_alloc_obj(&t$hl_types_ArrayDyn);
	hl_types_ArrayDyn_new(r6);
	return ((vdynamic*)r6);
	label$9fea9d9_6_8:
	r7 = hl_alloc_obj(r3);
	r8 = r0->__constructor__;
	if( !r8 ) goto label$9fea9d9_6_19;
	r8 = r0->__constructor__;
	r8 = hl_no_closure(r8);
	if( r1 == NULL ) hl_null_access();
	r6 = hl_types_ArrayDyn_copy(r1);
	if( r6 == NULL ) hl_null_access();
	hl_types_ArrayDyn_unshift(r6,r7);
	r9 = NULL;
	r9 = Reflect_callMethod(r9,r8,r6);
	label$9fea9d9_6_19:
	return r7;
}

