// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_urho3d__actions__MoveBy
#define INC_urho3d__actions__MoveBy
typedef struct _urho3d__actions__$MoveBy *urho3d__actions__$MoveBy;
typedef struct _urho3d__actions__MoveBy *urho3d__actions__MoveBy;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <urho3d/actions/FiniteTimeAction.h>
#include <hl/natives.h>


struct _urho3d__actions__$MoveBy {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _urho3d__actions__MoveBy {
	hl_type *$type;
	double duration;
	int Tag;
	bool isRepeatForever;
	hl_urho3d_math_vector3* PositionDelta;
};
#endif

