// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/actions/RepeatForever.h>
#include <urho3d/Node.h>
#include <urho3d/actions/RepeatForeverState.h>
#include <urho3d/actions/FiniteTimeActionState.h>
extern hl_type t$urho3d_actions_RepeatForeverState;
void urho3d_actions_RepeatForeverState_new(urho3d__actions__RepeatForeverState,urho3d__actions__RepeatForever,urho3d__Node);
extern hl_type t$urho3d_actions_RepeatForever;
void urho3d_actions_RepeatForever_new(urho3d__actions__RepeatForever,urho3d__actions__FiniteTimeAction);
extern hl_type t$hl_types_ArrayObj;
void hl_types_ArrayObj_new(hl__types__ArrayObj);
void urho3d_actions_FiniteTimeAction_new(urho3d__actions__FiniteTimeAction,double*);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);

urho3d__actions__FiniteTimeActionState urho3d_actions_RepeatForever_StartAction(urho3d__actions__RepeatForever r0,urho3d__Node r1) {
	urho3d__actions__RepeatForeverState r2;
	r2 = (urho3d__actions__RepeatForeverState)hl_alloc_obj(&t$urho3d_actions_RepeatForeverState);
	urho3d_actions_RepeatForeverState_new(r2,r0,r1);
	return ((urho3d__actions__FiniteTimeActionState)r2);
}

urho3d__actions__FiniteTimeAction urho3d_actions_RepeatForever_Reverse(urho3d__actions__RepeatForever r0) {
	hl__types__ArrayObj r3;
	urho3d__actions__RepeatForever r1;
	urho3d__actions__FiniteTimeAction r2;
	vdynamic *r6;
	varray *r7;
	int r4, r5;
	r1 = (urho3d__actions__RepeatForever)hl_alloc_obj(&t$urho3d_actions_RepeatForever);
	r3 = r0->InnerAction;
	if( r3 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$d5abfe5_2_8;
	r2 = NULL;
	goto label$d5abfe5_2_11;
	label$d5abfe5_2_8:
	r7 = r3->array;
	r6 = ((vdynamic**)(r7 + 1))[r4];
	r2 = (urho3d__actions__FiniteTimeAction)r6;
	label$d5abfe5_2_11:
	if( r2 == NULL ) hl_null_access();
	r2 = ((urho3d__actions__FiniteTimeAction (*)(urho3d__actions__FiniteTimeAction))r2->$type->vobj_proto[0])(r2);
	urho3d_actions_RepeatForever_new(r1,r2);
	return ((urho3d__actions__FiniteTimeAction)r1);
}

void urho3d_actions_RepeatForever_new(urho3d__actions__RepeatForever r0,urho3d__actions__FiniteTimeAction r1) {
	hl__types__ArrayObj r2;
	bool r6;
	double *r4;
	int r5;
	r2 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r2);
	r0->InnerAction = r2;
	r4 = NULL;
	urho3d_actions_FiniteTimeAction_new(((urho3d__actions__FiniteTimeAction)r0),r4);
	r2 = r0->InnerAction;
	if( r2 == NULL ) hl_null_access();
	r5 = hl_types_ArrayObj_push(r2,((vdynamic*)r1));
	r6 = true;
	r0->isRepeatForever = r6;
	return;
}

