// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <actions/ActionGroup.h>
#include <actions/FiniteTimeAction.h>
#include <urho3d/Node.h>
#include <actions/ActionDef.h>
#include <actions/FiniteTimeActionState.h>
extern hl_type t$actions_ActionDef;
void actions_ActionDef_new(actions__ActionDef,actions__FiniteTimeActionState,actions__FiniteTimeAction,urho3d__Node);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
extern hl_type t$hl_types_ArrayObj;
void hl_types_ArrayObj_new(hl__types__ArrayObj);
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);

void actions_ActionGroup_Push(actions__ActionGroup r0,actions__FiniteTimeAction r1,urho3d__Node r2) {
	hl__types__ArrayObj r4;
	actions__FiniteTimeActionState r6;
	actions__ActionDef r5;
	int r3;
	r4 = r0->_actions;
	if( r4 == NULL ) hl_null_access();
	r5 = (actions__ActionDef)hl_alloc_obj(&t$actions_ActionDef);
	r6 = NULL;
	actions_ActionDef_new(r5,r6,r1,r2);
	r3 = hl_types_ArrayObj_push(r4,((vdynamic*)r5));
	return;
}

void actions_ActionGroup_new(actions__ActionGroup r0) {
	hl__types__ArrayObj r1;
	hl_type *r4;
	int r5;
	varray *r3;
	r1 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r1);
	r0->_actions = r1;
	r4 = &t$actions_ActionDef;
	r5 = 0;
	r3 = hl_alloc_array(r4,r5);
	r1 = hl_types_ArrayObj_alloc(r3);
	r0->_actions = r1;
	return;
}

