// Generated by HLC 4.1.2 (HL v4)
#ifndef INC_actions__MoveBy
#define INC_actions__MoveBy
typedef struct _actions__$MoveBy *actions__$MoveBy;
typedef struct _actions__MoveBy *actions__MoveBy;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <actions/FiniteTimeAction.h>
#include <hl/natives.h>


struct _actions__$MoveBy {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _actions__MoveBy {
	hl_type *$type;
	double duration;
	int Tag;
	bool isRepeatForever;
	hl_urho3d_math_vector3* PositionDelta;
};
#endif

