// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_Component/AbstractComponent_Impl_.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
extern hl_type t$urho3d_Component;
void urho3d_Component_new(urho3d__Component,hl_urho3d_scene_component*);
extern hl_type t$urho3d_Zone;
void urho3d_Zone_new(urho3d__Zone,hl_urho3d_graphics_zone*);
extern hl_type t$urho3d_StaticModel;
void urho3d_StaticModel_new(urho3d__StaticModel,hl_urho3d_graphics_staticmodel*);
extern hl_type t$urho3d_AnimatedModel;
void urho3d_AnimatedModel_new(urho3d__AnimatedModel,hl_urho3d_graphics_animatedmodel*);
extern hl_type t$urho3d_Camera;
void urho3d_Camera_new(urho3d__Camera,hl_urho3d_graphics_camera*);
extern hl_type t$urho3d_Light;
void urho3d_Light_new(urho3d__Light,hl_urho3d_graphics_light*);
extern hl_type t$urho3d_BillboardSet;
void urho3d_BillboardSet_new(urho3d__BillboardSet,hl_urho3d_graphics_billboardset*);

hl_urho3d_scene_component* urho3d__Component_AbstractComponent_Impl___new() {
	hl_urho3d_scene_component *r0;
	urho3d___Context__$Context_Impl_ r2;
	urho3d_context *r1;
	r2 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r1 = r2->context;
	r0 = Urho3D__scene_component_create(r1);
	return r0;
}

urho3d__Component urho3d__Component_AbstractComponent_Impl__toComponent(hl_urho3d_scene_component* r0) {
	urho3d__Component r1;
	r1 = (urho3d__Component)hl_alloc_obj(&t$urho3d_Component);
	urho3d_Component_new(r1,r0);
	return r1;
}

urho3d__Zone urho3d__Component_AbstractComponent_Impl__toZone(hl_urho3d_scene_component* r0) {
	hl_urho3d_graphics_zone *r1;
	urho3d___Context__$Context_Impl_ r3;
	urho3d__Zone r5;
	urho3d_context *r2;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_zone_cast_from_component(r2,r0);
	r5 = (urho3d__Zone)hl_alloc_obj(&t$urho3d_Zone);
	urho3d_Zone_new(r5,r1);
	return r5;
}

urho3d__StaticModel urho3d__Component_AbstractComponent_Impl__toStaticModel(hl_urho3d_scene_component* r0) {
	urho3d__StaticModel r5;
	urho3d___Context__$Context_Impl_ r3;
	urho3d_context *r2;
	hl_urho3d_graphics_staticmodel *r1;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_staticmodel_cast_from_component(r2,r0);
	r5 = (urho3d__StaticModel)hl_alloc_obj(&t$urho3d_StaticModel);
	urho3d_StaticModel_new(r5,r1);
	return r5;
}

urho3d__AnimatedModel urho3d__Component_AbstractComponent_Impl__toAnimatedModel(hl_urho3d_scene_component* r0) {
	urho3d__AnimatedModel r5;
	urho3d___Context__$Context_Impl_ r3;
	urho3d_context *r2;
	hl_urho3d_graphics_animatedmodel *r1;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_animatedmodel_cast_from_component(r2,r0);
	r5 = (urho3d__AnimatedModel)hl_alloc_obj(&t$urho3d_AnimatedModel);
	urho3d_AnimatedModel_new(r5,r1);
	return r5;
}

urho3d__Camera urho3d__Component_AbstractComponent_Impl__toCamera(hl_urho3d_scene_component* r0) {
	urho3d__Camera r5;
	urho3d___Context__$Context_Impl_ r3;
	hl_urho3d_graphics_camera *r1;
	urho3d_context *r2;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_camera_cast_from_component(r2,r0);
	r5 = (urho3d__Camera)hl_alloc_obj(&t$urho3d_Camera);
	urho3d_Camera_new(r5,r1);
	return r5;
}

urho3d__Light urho3d__Component_AbstractComponent_Impl__toLight(hl_urho3d_scene_component* r0) {
	urho3d___Context__$Context_Impl_ r3;
	urho3d_context *r2;
	urho3d__Light r5;
	hl_urho3d_graphics_light *r1;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_light_cast_from_component(r2,r0);
	r5 = (urho3d__Light)hl_alloc_obj(&t$urho3d_Light);
	urho3d_Light_new(r5,r1);
	return r5;
}

urho3d__BillboardSet urho3d__Component_AbstractComponent_Impl__toBillboardset(hl_urho3d_scene_component* r0) {
	urho3d__BillboardSet r5;
	hl_urho3d_graphics_billboardset *r1;
	urho3d___Context__$Context_Impl_ r3;
	urho3d_context *r2;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_billboardset_cast_from_component(r2,r0);
	r5 = (urho3d__BillboardSet)hl_alloc_obj(&t$urho3d_BillboardSet);
	urho3d_BillboardSet_new(r5,r1);
	return r5;
}

