// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <actions/ScaleTo.h>
void actions_FiniteTimeAction_new(actions__FiniteTimeAction,double*);
extern hl_type t$actions_ScaleTo;
#include <urho3d/Node.h>
#include <actions/ScaleToState.h>
#include <actions/FiniteTimeActionState.h>
extern hl_type t$actions_ScaleToState;
void actions_ScaleToState_new(actions__ScaleToState,actions__ScaleTo,urho3d__Node);

void actions_ScaleTo_new(actions__ScaleTo r0,double r1,double r2,vdynamic* r3,vdynamic* r4) {
	double r6, r8;
	double *r7;
	r6 = r1;
	r7 = &r6;
	actions_FiniteTimeAction_new(((actions__FiniteTimeAction)r0),r7);
	r0->EndScaleX = r2;
	if( r3 ) goto label$79a798b_1_7;
	r8 = r2;
	goto label$79a798b_1_8;
	label$79a798b_1_7:
	r8 = r3 ? r3->v.d : 0;
	label$79a798b_1_8:
	r0->EndScaleY = r8;
	if( r4 ) goto label$79a798b_1_12;
	r8 = r2;
	goto label$79a798b_1_13;
	label$79a798b_1_12:
	r8 = r4 ? r4->v.d : 0;
	label$79a798b_1_13:
	r0->EndScaleZ = r8;
	return;
}

actions__FiniteTimeAction actions_ScaleTo_Reverse(actions__ScaleTo r0) {
	actions__ScaleTo r1;
	double r2, r3;
	vdynamic *r4, *r5;
	r1 = (actions__ScaleTo)hl_alloc_obj(&t$actions_ScaleTo);
	r2 = r0->duration;
	r3 = r0->EndScaleX;
	r4 = NULL;
	r5 = NULL;
	actions_ScaleTo_new(r1,r2,r3,r4,r5);
	return ((actions__FiniteTimeAction)r1);
}

actions__FiniteTimeActionState actions_ScaleTo_StartAction(actions__ScaleTo r0,urho3d__Node r1) {
	actions__ScaleToState r2;
	r2 = (actions__ScaleToState)hl_alloc_obj(&t$actions_ScaleToState);
	actions_ScaleToState_new(r2,r0,r1);
	return ((actions__FiniteTimeActionState)r2);
}

