// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <samplygame/Background.h>
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
extern haxe__$Log g$_haxe_Log;
extern String s$DelayedStart;
extern hl_type t$vrt_329ffa8;
extern String s$c385087;
extern hl_type t$String;
extern hl_type t$_i32;
extern String s$samplygame_Background;
extern hl_type t$vrt_eaa6a3b;
urho3d__Node samplygame_Background_CreateTile(samplygame__Background,int);
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
void samplygame_Background_CreateBackGroundMovingAction(samplygame__Background);
#include <urho3d/actions/ActionID.h>
void samplygame_Background_SwitchTiles(samplygame__Background);
#include <urho3d/Math.h>
#include <urho3d/actions/ActionGroup.h>
#include <urho3d/actions/MoveBy.h>
#include <hl/types/ArrayObj.h>
extern urho3d__$Math g$_urho3d_Math;
extern hl_type t$urho3d_actions_ActionGroup;
void urho3d_actions_ActionGroup_new(urho3d__actions__ActionGroup);
extern hl_type t$urho3d_actions_MoveBy;
void urho3d_actions_MoveBy_new(urho3d__actions__MoveBy,double,hl_urho3d_math_vector3*);
#include <urho3d/actions/FiniteTimeAction.h>
void urho3d_actions_ActionGroup_Push(urho3d__actions__ActionGroup,urho3d__actions__FiniteTimeAction,urho3d__Node);
extern hl_type t$fun_7a0a5cf;
urho3d__actions__ActionID urho3d_actions_ActionManager_AddActions(hl__types__ArrayObj,urho3d__actions__ActionGroup,vclosure*);
#include <haxe/ds/ObjectMap.h>
#include <urho3d/StaticModel.h>
#include <haxe/ds/StringMap.h>
urho3d__Node urho3d_Component_get_node(urho3d__Component);
extern String s$;
extern hl_type t$urho3d_Node;
void urho3d_Node_new(urho3d__Node,hl_urho3d_scene_node*);
hl_urho3d_scene_node_ptr* urho3d_Node_get_pointer(urho3d__Node);
extern hl_type t$hl_urho3d_scene_node_ptr;
void haxe_ds_ObjectMap_set(haxe__ds__ObjectMap,vdynamic*,vdynamic*);
extern String s$StaticModel;
extern hl_type t$urho3d_StaticModel;
void urho3d_StaticModel_new(urho3d__StaticModel,hl_urho3d_graphics_staticmodel*);
extern String s$Models_Plane_mdl;
hl_urho3d_graphics_model* urho3d_StaticModel_set_model(urho3d__StaticModel,hl_urho3d_graphics_model*);
extern String s$Materials_Grass_xml;
hl_urho3d_graphics_material* urho3d_StaticModel_set_material(urho3d__StaticModel,hl_urho3d_graphics_material*);
extern hl_type t$_f64;
double urho3d_LogicComponent_Random(urho3d__LogicComponent,vdynamic*,vdynamic*);
extern String s$Models_Tree_mdl;
extern String s$Materials_TreeMaterial_xml;
urho3d__Node urho3d_Node_get_parent(urho3d__Node);
extern hl_type t$vrt_b840ca7;
extern hl_type t$haxe_ds_StringMap;
void haxe_ds_StringMap_set(haxe__ds__StringMap,String,vdynamic*);
bool haxe_ds_ObjectMap_remove(haxe__ds__ObjectMap,vdynamic*);
bool haxe_ds_StringMap_remove(haxe__ds__StringMap,String);
vvirtual* haxe_ds_ObjectMap_iterator(haxe__ds__ObjectMap);
extern hl_type t$vrt_1cffe76;
extern hl_type t$fun_bf7849e;
extern hl_type t$fun_d937e10;
bool urho3d_Node_set_valid(urho3d__Node,bool);
vvirtual* haxe_ds_StringMap_iterator(haxe__ds__StringMap);
void urho3d_Node_CleanChildData(urho3d__Node);
void haxe_ds_StringMap_clear(haxe__ds__StringMap);
void haxe_ds_ObjectMap_clear(haxe__ds__ObjectMap);
void urho3d_LogicComponent_new(urho3d__LogicComponent,vdynamic*);

void samplygame_Background_DelayedStart(samplygame__Background r0) {
	String r4, r6;
	vvirtual *r5, *r8;
	hl_urho3d_math_vector3 *r20;
	urho3d__Node r9, r11;
	haxe__$Log r3;
	urho3d___Context__$Context_Impl_ r14;
	float r16, r17, r18;
	urho3d_context *r13;
	hl_urho3d_scene_node *r10;
	double r15;
	vclosure *r2;
	hl_urho3d_math_tvector3 *r12, *r19;
	int r7;
	r3 = (haxe__$Log)g$_haxe_Log;
	r2 = r3->trace;
	if( r2 == NULL ) hl_null_access();
	r4 = (String)s$DelayedStart;
	r5 = hl_alloc_virtual(&t$vrt_329ffa8);
	r6 = (String)s$c385087;
	if( hl_vfields(r5)[1] ) *(String*)(hl_vfields(r5)[1]) = (String)r6; else hl_dyn_setp(r5->value,37969014/*fileName*/,&t$String,r6);
	r7 = 27;
	if( hl_vfields(r5)[2] ) *(int*)(hl_vfields(r5)[2]) = (int)r7; else hl_dyn_seti(r5->value,371360620/*lineNumber*/,&t$_i32,r7);
	r6 = (String)s$samplygame_Background;
	if( hl_vfields(r5)[0] ) *(String*)(hl_vfields(r5)[0]) = (String)r6; else hl_dyn_setp(r5->value,-63073762/*className*/,&t$String,r6);
	r6 = (String)s$DelayedStart;
	if( hl_vfields(r5)[3] ) *(String*)(hl_vfields(r5)[3]) = (String)r6; else hl_dyn_setp(r5->value,302979532/*methodName*/,&t$String,r6);
	r8 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r5);
	r2->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r2->fun)((vdynamic*)r2->value,((vdynamic*)r4),r8) : ((void (*)(vdynamic*,vvirtual*))r2->fun)(((vdynamic*)r4),r8);
	r7 = 0;
	r9 = samplygame_Background_CreateTile(r0,r7);
	r0->frontTile = r9;
	r7 = 1;
	r9 = samplygame_Background_CreateTile(r0,r7);
	r0->rearTile = r9;
	r9 = r0->frontTile;
	if( r9 == NULL ) hl_null_access();
	r10 = r9->abstractNode;
	if( !r10 ) goto label$6714240_1_30;
	r14 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r13 = r14->context;
	r10 = r9->abstractNode;
	r12 = Urho3D__scene_node_get_position(r13,r10);
	goto label$6714240_1_37;
	label$6714240_1_30:
	r15 = 0.;
	r16 = (float)r15;
	r15 = 0.;
	r17 = (float)r15;
	r15 = 0.;
	r18 = (float)r15;
	r12 = Urho3D__math_tvector3_create(r16,r17,r18);
	label$6714240_1_37:
	r20 = Urho3D__math_tvector3_cast_to_vector3(r12);
	r0->frontTilePos = r20;
	r11 = r0->rearTile;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->abstractNode;
	if( !r10 ) goto label$6714240_1_48;
	r14 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r13 = r14->context;
	r10 = r11->abstractNode;
	r19 = Urho3D__scene_node_get_position(r13,r10);
	goto label$6714240_1_55;
	label$6714240_1_48:
	r15 = 0.;
	r16 = (float)r15;
	r15 = 0.;
	r17 = (float)r15;
	r15 = 0.;
	r18 = (float)r15;
	r19 = Urho3D__math_tvector3_create(r16,r17,r18);
	label$6714240_1_55:
	r20 = Urho3D__math_tvector3_cast_to_vector3(r19);
	r0->rearTilePos = r20;
	samplygame_Background_CreateBackGroundMovingAction(r0);
	return;
}

void samplygame_Background_OnActionDone(samplygame__Background r0,urho3d__actions__ActionID r1) {
	samplygame_Background_SwitchTiles(r0);
	samplygame_Background_CreateBackGroundMovingAction(r0);
	return;
}

void samplygame_Background_CreateBackGroundMovingAction(samplygame__Background r0) {
	hl__types__ArrayObj r20;
	urho3d__actions__ActionGroup r8;
	urho3d__$Math r4;
	urho3d__Node r17;
	urho3d__actions__MoveBy r15;
	hl_urho3d_math_vector3 *r10, *r16;
	float r12, r13, r14;
	vclosure *r21;
	double r1, r2, r3, r6, r7, r9, r18;
	urho3d__actions__ActionID r19;
	int r11;
	r1 = r0->BackgroundScale;
	r2 = 90.;
	r3 = r0->BackgroundRotationX;
	r2 = r2 - r3;
	r4 = (urho3d__$Math)g$_urho3d_Math;
	r3 = r4->_DEGTORAD_;
	r2 = r2 * r3;
	r2 = hl_math_sin(r2);
	r1 = r1 * r2;
	r2 = r0->BackgroundScale;
	r3 = r0->BackgroundRotationX;
	r4 = (urho3d__$Math)g$_urho3d_Math;
	r6 = r4->_DEGTORAD_;
	r3 = r3 * r6;
	r3 = hl_math_sin(r3);
	r2 = r2 * r3;
	r3 = r0->FlightHeight;
	r2 = r2 + r3;
	r6 = 1.;
	r3 = r1 + r6;
	r6 = r0->BackgroundRotationX;
	r4 = (urho3d__$Math)g$_urho3d_Math;
	r7 = r4->_DEGTORAD_;
	r6 = r6 * r7;
	r6 = hl_math_tan(r6);
	r6 = r6 * r3;
	r8 = (urho3d__actions__ActionGroup)hl_alloc_obj(&t$urho3d_actions_ActionGroup);
	urho3d_actions_ActionGroup_new(r8);
	r7 = 1.;
	r9 = r0->BackgroundSpeed;
	r7 = r7 / r9;
	r11 = 0;
	r12 = (float)r11;
	r9 = -r3;
	r13 = (float)r9;
	r9 = -r6;
	r14 = (float)r9;
	r10 = Urho3D__math_vector3_create(r12,r13,r14);
	r15 = (urho3d__actions__MoveBy)hl_alloc_obj(&t$urho3d_actions_MoveBy);
	urho3d_actions_MoveBy_new(r15,r7,r10);
	r17 = r0->frontTile;
	urho3d_actions_ActionGroup_Push(r8,((urho3d__actions__FiniteTimeAction)r15),r17);
	r9 = 1.;
	r18 = r0->BackgroundSpeed;
	r9 = r9 / r18;
	r11 = 0;
	r12 = (float)r11;
	r18 = -r3;
	r13 = (float)r18;
	r18 = -r6;
	r14 = (float)r18;
	r16 = Urho3D__math_vector3_create(r12,r13,r14);
	r15 = (urho3d__actions__MoveBy)hl_alloc_obj(&t$urho3d_actions_MoveBy);
	urho3d_actions_MoveBy_new(r15,r9,r16);
	r17 = r0->rearTile;
	urho3d_actions_ActionGroup_Push(r8,((urho3d__actions__FiniteTimeAction)r15),r17);
	r20 = NULL;
	r21 = hl_alloc_closure_ptr(&t$fun_7a0a5cf,samplygame_Background_OnActionDone,r0);
	r19 = urho3d_actions_ActionManager_AddActions(r20,r8,r21);
	return;
}

void samplygame_Background_SwitchTiles(samplygame__Background r0) {
	urho3d__$Math r4;
	hl_urho3d_math_vector3 *r9;
	urho3d__Node r7, r8;
	urho3d___Context__$Context_Impl_ r17;
	urho3d_context *r16;
	hl_urho3d_scene_node *r15;
	float r11, r12, r13;
	double r1, r2, r3, r6;
	hl_urho3d_math_tvector3 *r14;
	int r10;
	r1 = r0->BackgroundScale;
	r2 = 90.;
	r3 = r0->BackgroundRotationX;
	r2 = r2 - r3;
	r4 = (urho3d__$Math)g$_urho3d_Math;
	r3 = r4->_DEGTORAD_;
	r2 = r2 * r3;
	r2 = hl_math_sin(r2);
	r1 = r1 * r2;
	r2 = r0->BackgroundScale;
	r3 = r0->BackgroundRotationX;
	r4 = (urho3d__$Math)g$_urho3d_Math;
	r6 = r4->_DEGTORAD_;
	r3 = r3 * r6;
	r3 = hl_math_sin(r3);
	r2 = r2 * r3;
	r3 = r0->FlightHeight;
	r2 = r2 + r3;
	r7 = r0->frontTile;
	r8 = r0->rearTile;
	r0->frontTile = r8;
	r0->rearTile = r7;
	r8 = r0->rearTile;
	r10 = 0;
	r11 = (float)r10;
	r12 = (float)r1;
	r13 = (float)r2;
	r9 = Urho3D__math_vector3_create(r11,r12,r13);
	r14 = Urho3D__math_tvector3_cast_from_vector3(r9);
	if( r8 == NULL ) hl_null_access();
	r15 = r8->abstractNode;
	if( !r15 ) goto label$6714240_4_36;
	r17 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r16 = r17->context;
	r15 = r8->abstractNode;
	Urho3D__scene_node_set_position(r16,r15,r14);
	label$6714240_4_36:
	return;
}

urho3d__Node samplygame_Background_CreateTile(samplygame__Background r0,int r1) {
	String r8, r48;
	haxe__ds__ObjectMap r13;
	vvirtual *r46, *r51, *r52, *r53, *r54;
	haxe__ds__StringMap r45;
	hl_urho3d_scene_component *r25;
	hl_urho3d_scene_node_ptr *r15;
	urho3d__StaticModel r27, r40;
	bool r11, r50;
	urho3d__$Math r56;
	hl_urho3d_math_quaternion *r38;
	hl_urho3d_math_vector3 *r18;
	urho3d__Node r2, r5, r14, r17, r34, r49, r55;
	hl_urho3d_math_tquaternion *r39;
	hl_urho3d_graphics_material *r30, *r31, *r42;
	urho3d___Context__$Context_Impl_ r7;
	float r20, r21, r22;
	urho3d_context *r6;
	hl_urho3d_scene_node *r4, *r12;
	hl_urho3d_graphics_staticmodel *r26;
	double r19, r32, r33, r37, r43, r44, r57;
	hl_urho3d_math_tvector3 *r23, *r24;
	vdynamic *r16, *r35, *r36;
	vbyte *r47;
	hl_urho3d_graphics_model *r28, *r29, *r41;
	int r9, r10;
	r2 = urho3d_Component_get_node(((urho3d__Component)r0));
	if( r2 == NULL ) hl_null_access();
	r4 = r2->abstractNode;
	if( !r4 ) goto label$6714240_5_22;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r2->abstractNode;
	r8 = (String)s$;
	r9 = 0;
	r10 = 0;
	r11 = false;
	r4 = Urho3D__scene_node_create_child(r6,r4,r8,r9,r10,r11);
	r5 = (urho3d__Node)hl_alloc_obj(&t$urho3d_Node);
	urho3d_Node_new(r5,r4);
	r13 = r2->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r15 = urho3d_Node_get_pointer(r5);
	if( r15 == NULL ) r16 = NULL; else {
		r16 = hl_alloc_dynamic(&t$hl_urho3d_scene_node_ptr);
		r16->v.ptr = r15;
	}
	haxe_ds_ObjectMap_set(r13,r16,((vdynamic*)r5));
	r5->_parent = r2;
	r14 = r5;
	goto label$6714240_5_24;
	label$6714240_5_22:
	r5 = NULL;
	r14 = r5;
	label$6714240_5_24:
	if( r5 == NULL ) hl_null_access();
	r4 = r5->abstractNode;
	if( !r4 ) goto label$6714240_5_45;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r5->abstractNode;
	r8 = (String)s$;
	r9 = 0;
	r10 = 0;
	r11 = false;
	r4 = Urho3D__scene_node_create_child(r6,r4,r8,r9,r10,r11);
	r5 = (urho3d__Node)hl_alloc_obj(&t$urho3d_Node);
	urho3d_Node_new(r5,r4);
	if( r14 == NULL ) hl_null_access();
	r13 = r14->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r15 = urho3d_Node_get_pointer(r5);
	if( r15 == NULL ) r16 = NULL; else {
		r16 = hl_alloc_dynamic(&t$hl_urho3d_scene_node_ptr);
		r16->v.ptr = r15;
	}
	haxe_ds_ObjectMap_set(r13,r16,((vdynamic*)r5));
	r5->_parent = r14;
	goto label$6714240_5_46;
	label$6714240_5_45:
	r5 = NULL;
	label$6714240_5_46:
	r19 = r0->BackgroundScale;
	r20 = (float)r19;
	r19 = 0.0001000000000000000048;
	r21 = (float)r19;
	r19 = r0->BackgroundScale;
	r22 = (float)r19;
	r18 = Urho3D__math_vector3_create(r20,r21,r22);
	r23 = Urho3D__math_tvector3_cast_from_vector3(r18);
	if( r5 == NULL ) hl_null_access();
	r4 = r5->abstractNode;
	if( !r4 ) goto label$6714240_5_61;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r5->abstractNode;
	Urho3D__scene_node_set_scale(r6,r4,r23);
	label$6714240_5_61:
	r4 = r5->abstractNode;
	if( !r4 ) goto label$6714240_5_71;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r5->abstractNode;
	r8 = (String)s$StaticModel;
	r9 = 0;
	r10 = 0;
	r25 = Urho3D__scene_node_create_component(r6,r4,r8,r9,r10);
	goto label$6714240_5_72;
	label$6714240_5_71:
	r25 = NULL;
	label$6714240_5_72:
	if( !r25 ) goto label$6714240_5_79;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r26 = Urho3D__graphics_staticmodel_cast_from_component(r6,r25);
	r27 = (urho3d__StaticModel)hl_alloc_obj(&t$urho3d_StaticModel);
	urho3d_StaticModel_new(r27,r26);
	goto label$6714240_5_80;
	label$6714240_5_79:
	r27 = NULL;
	label$6714240_5_80:
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r8 = (String)s$Models_Plane_mdl;
	r28 = Urho3D__graphics_model_create(r6,r8);
	if( r27 == NULL ) hl_null_access();
	r29 = urho3d_StaticModel_set_model(r27,r28);
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r8 = (String)s$Materials_Grass_xml;
	r30 = Urho3D__graphics_material_create(r6,r8);
	r31 = urho3d_StaticModel_set_material(r27,r30);
	r19 = r0->BackgroundScale;
	r32 = 2.100000000000000089;
	r19 = r19 / r32;
	r32 = r0->BackgroundScale;
	r33 = 3.799999999999999822;
	r32 = r32 / r33;
	if( r14 == NULL ) hl_null_access();
	r4 = r14->abstractNode;
	if( !r4 ) goto label$6714240_5_118;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r14->abstractNode;
	r8 = (String)s$;
	r9 = 0;
	r10 = 0;
	r11 = false;
	r4 = Urho3D__scene_node_create_child(r6,r4,r8,r9,r10,r11);
	r5 = (urho3d__Node)hl_alloc_obj(&t$urho3d_Node);
	urho3d_Node_new(r5,r4);
	r13 = r14->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r15 = urho3d_Node_get_pointer(r5);
	if( r15 == NULL ) r16 = NULL; else {
		r16 = hl_alloc_dynamic(&t$hl_urho3d_scene_node_ptr);
		r16->v.ptr = r15;
	}
	haxe_ds_ObjectMap_set(r13,r16,((vdynamic*)r5));
	r5->_parent = r14;
	r17 = r5;
	goto label$6714240_5_120;
	label$6714240_5_118:
	r5 = NULL;
	r17 = r5;
	label$6714240_5_120:
	r9 = 5;
	r33 = (double)r9;
	r35 = hl_alloc_dynamic(&t$_f64);
	r35->v.d = r33;
	r36 = NULL;
	r33 = urho3d_LogicComponent_Random(((urho3d__LogicComponent)r0),r35,r36);
	r37 = 90.;
	r33 = r33 * r37;
	r23 = NULL;
	if( !r23 ) goto label$6714240_5_133;
	r9 = 0;
	r20 = (float)r9;
	r38 = Urho3D__math_quaternion_create_fv(r20,r23);
	goto label$6714240_5_139;
	label$6714240_5_133:
	r9 = 0;
	r20 = (float)r9;
	r21 = (float)r33;
	r9 = 0;
	r22 = (float)r9;
	r38 = Urho3D__math_quaternion_create(r20,r21,r22);
	label$6714240_5_139:
	r39 = Urho3D__math_t_quaternion_cast_from_quaternion(r38);
	if( r5 == NULL ) hl_null_access();
	r4 = r5->abstractNode;
	if( !r4 ) goto label$6714240_5_148;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r5->abstractNode;
	r9 = 0;
	Urho3D__scene_node_rotate(r6,r4,r39,r9);
	label$6714240_5_148:
	r33 = 0.3499999999999999778;
	r20 = (float)r33;
	r33 = 0.3499999999999999778;
	r21 = (float)r33;
	r33 = 0.3499999999999999778;
	r22 = (float)r33;
	r23 = Urho3D__math_tvector3_create(r20,r21,r22);
	r4 = r5->abstractNode;
	if( !r4 ) goto label$6714240_5_161;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r5->abstractNode;
	Urho3D__scene_node_set_scale(r6,r4,r23);
	label$6714240_5_161:
	r4 = r5->abstractNode;
	if( !r4 ) goto label$6714240_5_171;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r5->abstractNode;
	r8 = (String)s$StaticModel;
	r9 = 0;
	r10 = 0;
	r25 = Urho3D__scene_node_create_component(r6,r4,r8,r9,r10);
	goto label$6714240_5_172;
	label$6714240_5_171:
	r25 = NULL;
	label$6714240_5_172:
	if( !r25 ) goto label$6714240_5_179;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r26 = Urho3D__graphics_staticmodel_cast_from_component(r6,r25);
	r40 = (urho3d__StaticModel)hl_alloc_obj(&t$urho3d_StaticModel);
	urho3d_StaticModel_new(r40,r26);
	goto label$6714240_5_180;
	label$6714240_5_179:
	r40 = NULL;
	label$6714240_5_180:
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r8 = (String)s$Models_Tree_mdl;
	r29 = Urho3D__graphics_model_create(r6,r8);
	if( r40 == NULL ) hl_null_access();
	r41 = urho3d_StaticModel_set_model(r40,r29);
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r8 = (String)s$Materials_TreeMaterial_xml;
	r31 = Urho3D__graphics_material_create(r6,r8);
	r42 = urho3d_StaticModel_set_material(r40,r31);
	r33 = -r32;
	label$6714240_5_192:
	if( !(r33 < r32) ) goto label$6714240_5_272;
	r37 = -r19;
	label$6714240_5_195:
	if( !(r37 < r19) ) goto label$6714240_5_268;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	if( r17 == NULL ) hl_null_access();
	r4 = r17->abstractNode;
	r4 = Urho3D__scene_node_clone(r6,r4);
	r5 = (urho3d__Node)hl_alloc_obj(&t$urho3d_Node);
	urho3d_Node_new(r5,r4);
	r34 = urho3d_Node_get_parent(r17);
	if( !r34 ) goto label$6714240_5_246;
	r34 = urho3d_Node_get_parent(r17);
	if( r34 == NULL ) hl_null_access();
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r15 = urho3d_Node_get_pointer(r17);
	if( r15 == NULL ) r16 = NULL; else {
		r16 = hl_alloc_dynamic(&t$hl_urho3d_scene_node_ptr);
		r16->v.ptr = r15;
	}
	haxe_ds_ObjectMap_set(r13,r16,((vdynamic*)r17));
	r34 = urho3d_Node_get_parent(r17);
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 ) goto label$6714240_5_219;
	r46 = NULL;
	goto label$6714240_5_223;
	label$6714240_5_219:
	r46 = r45->f$1;
	if( r46 ) goto label$6714240_5_223;
	r46 = hl_to_virtual(&t$vrt_b840ca7,(vdynamic*)r45);
	r45->f$1 = r46;
	label$6714240_5_223:
	r12 = r17->abstractNode;
	if( !r12 ) goto label$6714240_5_242;
	r8 = r17->_name;
	if( r8 ) goto label$6714240_5_240;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r12 = r17->abstractNode;
	r47 = Urho3D__scene_node_get_name(r6,r12);
	if( r47 ) goto label$6714240_5_234;
	r48 = NULL;
	goto label$6714240_5_239;
	label$6714240_5_234:
	r48 = (String)hl_alloc_obj(&t$String);
	r48->bytes = r47;
	r9 = 0;
	r9 = hl_ucs2length(r47,r9);
	r48->length = r9;
	label$6714240_5_239:
	r17->_name = r48;
	label$6714240_5_240:
	r48 = r17->_name;
	goto label$6714240_5_243;
	label$6714240_5_242:
	r48 = (String)s$;
	label$6714240_5_243:
	r45 = (haxe__ds__StringMap)hl_dyn_castp(&r46,&t$vrt_b840ca7,&t$haxe_ds_StringMap);
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_set(r45,r48,((vdynamic*)r17));
	label$6714240_5_246:
	r44 = -0.5;
	r35 = hl_alloc_dynamic(&t$_f64);
	r35->v.d = r44;
	r44 = 0.5;
	r36 = hl_alloc_dynamic(&t$_f64);
	r36->v.d = r44;
	r44 = urho3d_LogicComponent_Random(((urho3d__LogicComponent)r0),r35,r36);
	r43 = r33 + r44;
	r20 = (float)r43;
	r9 = 0;
	r21 = (float)r9;
	r22 = (float)r37;
	r18 = Urho3D__math_vector3_create(r20,r21,r22);
	r23 = Urho3D__math_tvector3_cast_from_vector3(r18);
	r12 = r5->abstractNode;
	if( !r12 ) goto label$6714240_5_264;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r12 = r5->abstractNode;
	Urho3D__scene_node_set_position(r6,r12,r23);
	label$6714240_5_264:
	r44 = 3.;
	r43 = r37 + r44;
	r37 = r43;
	goto label$6714240_5_195;
	label$6714240_5_268:
	r44 = 2.600000000000000089;
	r43 = r33 + r44;
	r33 = r43;
	goto label$6714240_5_192;
	label$6714240_5_272:
	if( r17 == NULL ) hl_null_access();
	r4 = r17->abstractNode;
	r12 = NULL;
	if( r4 != r12 ) goto label$6714240_5_278;
	r11 = false;
	goto label$6714240_5_279;
	label$6714240_5_278:
	r11 = true;
	label$6714240_5_279:
	r50 = true;
	if( r11 != r50 ) goto label$6714240_5_1191;
	r5 = r17->_parent;
	if( !r5 ) goto label$6714240_5_765;
	r5 = r17->_parent;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->abstractNode;
	r12 = NULL;
	if( r4 != r12 ) goto label$6714240_5_290;
	r11 = false;
	goto label$6714240_5_291;
	label$6714240_5_290:
	r11 = true;
	label$6714240_5_291:
	r50 = true;
	if( r11 != r50 ) goto label$6714240_5_764;
	r4 = r17->abstractNode;
	r12 = NULL;
	if( r4 != r12 ) goto label$6714240_5_298;
	r11 = false;
	goto label$6714240_5_299;
	label$6714240_5_298:
	r11 = true;
	label$6714240_5_299:
	r50 = true;
	if( r11 != r50 ) goto label$6714240_5_764;
	r13 = r5->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r15 = urho3d_Node_get_pointer(r17);
	if( r15 == NULL ) r16 = NULL; else {
		r16 = hl_alloc_dynamic(&t$hl_urho3d_scene_node_ptr);
		r16->v.ptr = r15;
	}
	r11 = haxe_ds_ObjectMap_remove(r13,r16);
	r45 = r5->children_name_map;
	if( r45 ) goto label$6714240_5_310;
	r46 = NULL;
	goto label$6714240_5_314;
	label$6714240_5_310:
	r46 = r45->f$1;
	if( r46 ) goto label$6714240_5_314;
	r46 = hl_to_virtual(&t$vrt_b840ca7,(vdynamic*)r45);
	r45->f$1 = r46;
	label$6714240_5_314:
	r4 = r17->abstractNode;
	if( !r4 ) goto label$6714240_5_333;
	r8 = r17->_name;
	if( r8 ) goto label$6714240_5_331;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r17->abstractNode;
	r47 = Urho3D__scene_node_get_name(r6,r4);
	if( r47 ) goto label$6714240_5_325;
	r48 = NULL;
	goto label$6714240_5_330;
	label$6714240_5_325:
	r48 = (String)hl_alloc_obj(&t$String);
	r48->bytes = r47;
	r9 = 0;
	r9 = hl_ucs2length(r47,r9);
	r48->length = r9;
	label$6714240_5_330:
	r17->_name = r48;
	label$6714240_5_331:
	r48 = r17->_name;
	goto label$6714240_5_334;
	label$6714240_5_333:
	r48 = (String)s$;
	label$6714240_5_334:
	r45 = (haxe__ds__StringMap)hl_dyn_castp(&r46,&t$vrt_b840ca7,&t$haxe_ds_StringMap);
	if( r45 == NULL ) hl_null_access();
	r11 = haxe_ds_StringMap_remove(r45,r48);
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r5->abstractNode;
	r12 = r17->abstractNode;
	Urho3D__scene_node_remove_child(r6,r4,r12);
	r13 = r17->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r52 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_346:
	if( r52 == NULL ) hl_null_access();
	if( hl_vfields(r52)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r52)[0])(r52->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r52->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_495;
	if( hl_vfields(r52)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r52)[1])(r52->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r52->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_356:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_365;
	if( hl_vfields(r53)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	r11 = false;
	r11 = urho3d_Node_set_valid(r49,r11);
	goto label$6714240_5_356;
	label$6714240_5_365:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_370:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_379;
	if( hl_vfields(r53)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	r11 = false;
	r11 = urho3d_Node_set_valid(r49,r11);
	goto label$6714240_5_370;
	label$6714240_5_379:
	if( r34 == NULL ) hl_null_access();
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_384:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_429;
	if( hl_vfields(r53)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	r13 = r49->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_394:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_402;
	if( hl_vfields(r54)[1] ) r55 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r55 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r55 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r55);
	goto label$6714240_5_394;
	label$6714240_5_402:
	if( r49 == NULL ) hl_null_access();
	r45 = r49->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_407:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_415;
	if( hl_vfields(r54)[1] ) r55 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r55 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r55 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r55);
	goto label$6714240_5_407;
	label$6714240_5_415:
	if( r49 == NULL ) hl_null_access();
	r45 = r49->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r49->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r49->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r49->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	goto label$6714240_5_384;
	label$6714240_5_429:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_434:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_479;
	if( hl_vfields(r53)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	r13 = r49->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_444:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_452;
	if( hl_vfields(r54)[1] ) r55 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r55 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r55 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r55);
	goto label$6714240_5_444;
	label$6714240_5_452:
	if( r49 == NULL ) hl_null_access();
	r45 = r49->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_457:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_465;
	if( hl_vfields(r54)[1] ) r55 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r55 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r55 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r55);
	goto label$6714240_5_457;
	label$6714240_5_465:
	if( r49 == NULL ) hl_null_access();
	r45 = r49->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r49->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r49->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r49->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	goto label$6714240_5_434;
	label$6714240_5_479:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r34->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r4 = NULL;
	r34->abstractNode = r4;
	goto label$6714240_5_346;
	label$6714240_5_495:
	if( r17 == NULL ) hl_null_access();
	r45 = r17->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r52 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_500:
	if( r52 == NULL ) hl_null_access();
	if( hl_vfields(r52)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r52)[0])(r52->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r52->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_649;
	if( hl_vfields(r52)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r52)[1])(r52->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r52->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_510:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_519;
	if( hl_vfields(r53)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	r11 = false;
	r11 = urho3d_Node_set_valid(r49,r11);
	goto label$6714240_5_510;
	label$6714240_5_519:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_524:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_533;
	if( hl_vfields(r53)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	r11 = false;
	r11 = urho3d_Node_set_valid(r49,r11);
	goto label$6714240_5_524;
	label$6714240_5_533:
	if( r34 == NULL ) hl_null_access();
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_538:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_583;
	if( hl_vfields(r53)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	r13 = r49->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_548:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_556;
	if( hl_vfields(r54)[1] ) r55 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r55 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r55 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r55);
	goto label$6714240_5_548;
	label$6714240_5_556:
	if( r49 == NULL ) hl_null_access();
	r45 = r49->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_561:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_569;
	if( hl_vfields(r54)[1] ) r55 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r55 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r55 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r55);
	goto label$6714240_5_561;
	label$6714240_5_569:
	if( r49 == NULL ) hl_null_access();
	r45 = r49->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r49->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r49->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r49->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	goto label$6714240_5_538;
	label$6714240_5_583:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_588:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_633;
	if( hl_vfields(r53)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	r13 = r49->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_598:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_606;
	if( hl_vfields(r54)[1] ) r55 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r55 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r55 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r55);
	goto label$6714240_5_598;
	label$6714240_5_606:
	if( r49 == NULL ) hl_null_access();
	r45 = r49->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_611:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_619;
	if( hl_vfields(r54)[1] ) r55 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r55 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r55 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r55);
	goto label$6714240_5_611;
	label$6714240_5_619:
	if( r49 == NULL ) hl_null_access();
	r45 = r49->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r49->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r49->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r49->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	goto label$6714240_5_588;
	label$6714240_5_633:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r34->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r4 = NULL;
	r34->abstractNode = r4;
	goto label$6714240_5_500;
	label$6714240_5_649:
	if( r17 == NULL ) hl_null_access();
	r13 = r17->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r52 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_654:
	if( r52 == NULL ) hl_null_access();
	if( hl_vfields(r52)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r52)[0])(r52->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r52->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_699;
	if( hl_vfields(r52)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r52)[1])(r52->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r52->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_664:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_672;
	if( hl_vfields(r53)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r49);
	goto label$6714240_5_664;
	label$6714240_5_672:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_677:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_685;
	if( hl_vfields(r53)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r49);
	goto label$6714240_5_677;
	label$6714240_5_685:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r34->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	goto label$6714240_5_654;
	label$6714240_5_699:
	if( r17 == NULL ) hl_null_access();
	r45 = r17->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r52 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_704:
	if( r52 == NULL ) hl_null_access();
	if( hl_vfields(r52)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r52)[0])(r52->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r52->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_749;
	if( hl_vfields(r52)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r52)[1])(r52->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r52->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_714:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_722;
	if( hl_vfields(r53)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r49);
	goto label$6714240_5_714;
	label$6714240_5_722:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_727:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_735;
	if( hl_vfields(r53)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r49);
	goto label$6714240_5_727;
	label$6714240_5_735:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r34->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	goto label$6714240_5_704;
	label$6714240_5_749:
	if( r17 == NULL ) hl_null_access();
	r45 = r17->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r17->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r17->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r17->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r4 = NULL;
	r17->abstractNode = r4;
	label$6714240_5_764:
	goto label$6714240_5_1191;
	label$6714240_5_765:
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r17->abstractNode;
	Urho3D__scene_node_remove(r6,r4);
	r13 = r17->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r52 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_773:
	if( r52 == NULL ) hl_null_access();
	if( hl_vfields(r52)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r52)[0])(r52->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r52->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_922;
	if( hl_vfields(r52)[1] ) r5 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r52)[1])(r52->value); else {
		r5 = (urho3d__Node)hl_dyn_call_obj(r52->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r5 == NULL ) hl_null_access();
	r13 = r5->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_783:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_792;
	if( hl_vfields(r53)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	r11 = false;
	r11 = urho3d_Node_set_valid(r34,r11);
	goto label$6714240_5_783;
	label$6714240_5_792:
	if( r5 == NULL ) hl_null_access();
	r45 = r5->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_797:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_806;
	if( hl_vfields(r53)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	r11 = false;
	r11 = urho3d_Node_set_valid(r34,r11);
	goto label$6714240_5_797;
	label$6714240_5_806:
	if( r5 == NULL ) hl_null_access();
	r13 = r5->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_811:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_856;
	if( hl_vfields(r53)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_821:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_829;
	if( hl_vfields(r54)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r49);
	goto label$6714240_5_821;
	label$6714240_5_829:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_834:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_842;
	if( hl_vfields(r54)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r49);
	goto label$6714240_5_834;
	label$6714240_5_842:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r34->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	goto label$6714240_5_811;
	label$6714240_5_856:
	if( r5 == NULL ) hl_null_access();
	r45 = r5->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_861:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_906;
	if( hl_vfields(r53)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_871:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_879;
	if( hl_vfields(r54)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r49);
	goto label$6714240_5_871;
	label$6714240_5_879:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_884:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_892;
	if( hl_vfields(r54)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r49);
	goto label$6714240_5_884;
	label$6714240_5_892:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r34->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	goto label$6714240_5_861;
	label$6714240_5_906:
	if( r5 == NULL ) hl_null_access();
	r45 = r5->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r5->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r5->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r5->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r4 = NULL;
	r5->abstractNode = r4;
	goto label$6714240_5_773;
	label$6714240_5_922:
	if( r17 == NULL ) hl_null_access();
	r45 = r17->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r52 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_927:
	if( r52 == NULL ) hl_null_access();
	if( hl_vfields(r52)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r52)[0])(r52->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r52->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_1076;
	if( hl_vfields(r52)[1] ) r5 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r52)[1])(r52->value); else {
		r5 = (urho3d__Node)hl_dyn_call_obj(r52->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r5 == NULL ) hl_null_access();
	r13 = r5->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_937:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_946;
	if( hl_vfields(r53)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	r11 = false;
	r11 = urho3d_Node_set_valid(r34,r11);
	goto label$6714240_5_937;
	label$6714240_5_946:
	if( r5 == NULL ) hl_null_access();
	r45 = r5->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_951:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_960;
	if( hl_vfields(r53)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	r11 = false;
	r11 = urho3d_Node_set_valid(r34,r11);
	goto label$6714240_5_951;
	label$6714240_5_960:
	if( r5 == NULL ) hl_null_access();
	r13 = r5->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_965:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_1010;
	if( hl_vfields(r53)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_975:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_983;
	if( hl_vfields(r54)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r49);
	goto label$6714240_5_975;
	label$6714240_5_983:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_988:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_996;
	if( hl_vfields(r54)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r49);
	goto label$6714240_5_988;
	label$6714240_5_996:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r34->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	goto label$6714240_5_965;
	label$6714240_5_1010:
	if( r5 == NULL ) hl_null_access();
	r45 = r5->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_1015:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_1060;
	if( hl_vfields(r53)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_1025:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_1033;
	if( hl_vfields(r54)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r49);
	goto label$6714240_5_1025;
	label$6714240_5_1033:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r54 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_1038:
	if( r54 == NULL ) hl_null_access();
	if( hl_vfields(r54)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r54)[0])(r54->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r54->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_1046;
	if( hl_vfields(r54)[1] ) r49 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r54)[1])(r54->value); else {
		r49 = (urho3d__Node)hl_dyn_call_obj(r54->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r49 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r49);
	goto label$6714240_5_1038;
	label$6714240_5_1046:
	if( r34 == NULL ) hl_null_access();
	r45 = r34->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r34->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r34->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	goto label$6714240_5_1015;
	label$6714240_5_1060:
	if( r5 == NULL ) hl_null_access();
	r45 = r5->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r5->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r5->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r5->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r4 = NULL;
	r5->abstractNode = r4;
	goto label$6714240_5_927;
	label$6714240_5_1076:
	if( r17 == NULL ) hl_null_access();
	r13 = r17->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r52 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_1081:
	if( r52 == NULL ) hl_null_access();
	if( hl_vfields(r52)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r52)[0])(r52->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r52->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_1126;
	if( hl_vfields(r52)[1] ) r5 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r52)[1])(r52->value); else {
		r5 = (urho3d__Node)hl_dyn_call_obj(r52->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r5 == NULL ) hl_null_access();
	r13 = r5->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_1091:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_1099;
	if( hl_vfields(r53)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r34);
	goto label$6714240_5_1091;
	label$6714240_5_1099:
	if( r5 == NULL ) hl_null_access();
	r45 = r5->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_1104:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_1112;
	if( hl_vfields(r53)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r34);
	goto label$6714240_5_1104;
	label$6714240_5_1112:
	if( r5 == NULL ) hl_null_access();
	r45 = r5->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r5->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r5->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r5->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	goto label$6714240_5_1081;
	label$6714240_5_1126:
	if( r17 == NULL ) hl_null_access();
	r45 = r17->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r52 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_1131:
	if( r52 == NULL ) hl_null_access();
	if( hl_vfields(r52)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r52)[0])(r52->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r52->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_1176;
	if( hl_vfields(r52)[1] ) r5 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r52)[1])(r52->value); else {
		r5 = (urho3d__Node)hl_dyn_call_obj(r52->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r5 == NULL ) hl_null_access();
	r13 = r5->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	r51 = haxe_ds_ObjectMap_iterator(r13);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_1141:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_1149;
	if( hl_vfields(r53)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r34);
	goto label$6714240_5_1141;
	label$6714240_5_1149:
	if( r5 == NULL ) hl_null_access();
	r45 = r5->children_name_map;
	if( r45 == NULL ) hl_null_access();
	r51 = haxe_ds_StringMap_iterator(r45);
	r53 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r51);
	label$6714240_5_1154:
	if( r53 == NULL ) hl_null_access();
	if( hl_vfields(r53)[0] ) r11 = ((bool (*)(vdynamic*))hl_vfields(r53)[0])(r53->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r53->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r11 = (bool)ret.v.i;
	}
	if( !r11 ) goto label$6714240_5_1162;
	if( hl_vfields(r53)[1] ) r34 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r53)[1])(r53->value); else {
		r34 = (urho3d__Node)hl_dyn_call_obj(r53->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r34 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r34);
	goto label$6714240_5_1154;
	label$6714240_5_1162:
	if( r5 == NULL ) hl_null_access();
	r45 = r5->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r5->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r5->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r5->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	goto label$6714240_5_1131;
	label$6714240_5_1176:
	if( r17 == NULL ) hl_null_access();
	r45 = r17->children_name_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r17->components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r45 = r17->logic_components_map;
	if( r45 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r45);
	r13 = r17->children_pointers_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r13);
	r4 = NULL;
	r17->abstractNode = r4;
	label$6714240_5_1191:
	r37 = 270.;
	r43 = r0->BackgroundRotationX;
	r37 = r37 + r43;
	r23 = NULL;
	if( !r23 ) goto label$6714240_5_1199;
	r20 = (float)r37;
	r38 = Urho3D__math_quaternion_create_fv(r20,r23);
	goto label$6714240_5_1205;
	label$6714240_5_1199:
	r20 = (float)r37;
	r9 = 0;
	r21 = (float)r9;
	r9 = 0;
	r22 = (float)r9;
	r38 = Urho3D__math_quaternion_create(r20,r21,r22);
	label$6714240_5_1205:
	r39 = Urho3D__math_t_quaternion_cast_from_quaternion(r38);
	if( r14 == NULL ) hl_null_access();
	r4 = r14->abstractNode;
	if( !r4 ) goto label$6714240_5_1214;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r14->abstractNode;
	r9 = 0;
	Urho3D__scene_node_rotate(r6,r4,r39,r9);
	label$6714240_5_1214:
	r9 = 0;
	r20 = (float)r9;
	r9 = 0;
	r21 = (float)r9;
	r9 = 0;
	r22 = (float)r9;
	r18 = Urho3D__math_vector3_create(r20,r21,r22);
	r23 = Urho3D__math_tvector3_cast_from_vector3(r18);
	r37 = r0->BackgroundRotationY;
	r24 = NULL;
	if( !r24 ) goto label$6714240_5_1229;
	r9 = 0;
	r20 = (float)r9;
	r38 = Urho3D__math_quaternion_create_fv(r20,r24);
	goto label$6714240_5_1235;
	label$6714240_5_1229:
	r9 = 0;
	r20 = (float)r9;
	r21 = (float)r37;
	r9 = 0;
	r22 = (float)r9;
	r38 = Urho3D__math_quaternion_create(r20,r21,r22);
	label$6714240_5_1235:
	r39 = Urho3D__math_t_quaternion_cast_from_quaternion(r38);
	r4 = r14->abstractNode;
	if( !r4 ) goto label$6714240_5_1243;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r14->abstractNode;
	r9 = 0;
	Urho3D__scene_node_rotate_around(r6,r4,r23,r39,r9);
	label$6714240_5_1243:
	r37 = r0->BackgroundScale;
	r43 = 90.;
	r44 = r0->BackgroundRotationX;
	r43 = r43 - r44;
	r56 = (urho3d__$Math)g$_urho3d_Math;
	r44 = r56->_DEGTORAD_;
	r43 = r43 * r44;
	r43 = hl_math_sin(r43);
	r37 = r37 * r43;
	r43 = r0->BackgroundScale;
	r44 = r0->BackgroundRotationX;
	r56 = (urho3d__$Math)g$_urho3d_Math;
	r57 = r56->_DEGTORAD_;
	r44 = r44 * r57;
	r44 = hl_math_sin(r44);
	r43 = r43 * r44;
	r9 = 0;
	r20 = (float)r9;
	r57 = 0.01000000000000000021;
	r44 = r37 + r57;
	r57 = (double)r1;
	r44 = r44 * r57;
	r21 = (float)r44;
	r57 = (double)r1;
	r44 = r43 * r57;
	r57 = r0->FlightHeight;
	r44 = r44 + r57;
	r22 = (float)r44;
	r18 = Urho3D__math_vector3_create(r20,r21,r22);
	r23 = Urho3D__math_tvector3_cast_from_vector3(r18);
	r4 = r14->abstractNode;
	if( !r4 ) goto label$6714240_5_1279;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r4 = r14->abstractNode;
	Urho3D__scene_node_set_position(r6,r4,r23);
	label$6714240_5_1279:
	return r14;
}

void samplygame_Background_new(samplygame__Background r0,vdynamic* r1) {
	urho3d__Node r7;
	hl_urho3d_math_vector3 *r2;
	float r4, r5, r6;
	double r3;
	r3 = 0.;
	r4 = (float)r3;
	r3 = 0.;
	r5 = (float)r3;
	r3 = 0.;
	r6 = (float)r3;
	r2 = Urho3D__math_vector3_create(r4,r5,r6);
	r0->rearTilePos = r2;
	r3 = 0.;
	r4 = (float)r3;
	r3 = 0.;
	r5 = (float)r3;
	r3 = 0.;
	r6 = (float)r3;
	r2 = Urho3D__math_vector3_create(r4,r5,r6);
	r0->frontTilePos = r2;
	r3 = 10.;
	r0->FlightHeight = r3;
	r3 = 0.05000000000000000278;
	r0->BackgroundSpeed = r3;
	r3 = 40.;
	r0->BackgroundScale = r3;
	r3 = 15.;
	r0->BackgroundRotationY = r3;
	r3 = 45.;
	r0->BackgroundRotationX = r3;
	r7 = NULL;
	r0->rearTile = r7;
	r7 = NULL;
	r0->frontTile = r7;
	urho3d_LogicComponent_new(((urho3d__LogicComponent)r0),r1);
	return;
}

