// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <samplygame/Player.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
#include <urho3d/StaticModel.h>
#include <haxe/ds/ObjectMap.h>
#include <urho3d/actions/ActionDef.h>
#include <urho3d/actions/RepeatForever.h>
#include <urho3d/actions/RotateBy.h>
#include <urho3d/actions/FiniteTimeActionState.h>
#include <samplygame/MachineGun.h>
#include <haxe/ds/StringMap.h>
#include <hl/types/ArrayDyn.h>
#include <hl/types/ArrayObj.h>
#include <samplygame/Missile.h>
#include <urho3d/actions/EaseOut.h>
#include <urho3d/actions/MoveBy.h>
#include <urho3d/actions/Sequence.h>
#include <urho3d/actions/EaseBackInOut.h>
#include <urho3d/actions/DelayTime.h>
#include <urho3d/actions/FiniteTimeAction.h>
urho3d__Node urho3d_Component_get_node(urho3d__Component);
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
extern String s$StaticModel;
extern hl_type t$urho3d_StaticModel;
void urho3d_StaticModel_new(urho3d__StaticModel,hl_urho3d_graphics_staticmodel*);
extern String s$Models_Player_mdl;
hl_urho3d_graphics_model* urho3d_StaticModel_set_model(urho3d__StaticModel,hl_urho3d_graphics_model*);
extern String s$Materials_Player_xml;
hl_urho3d_graphics_material* urho3d_StaticModel_set_material(urho3d__StaticModel,hl_urho3d_graphics_material*);
extern String s$;
extern hl_type t$urho3d_Node;
void urho3d_Node_new(urho3d__Node,hl_urho3d_scene_node*);
hl_urho3d_scene_node_ptr* urho3d_Node_get_pointer(urho3d__Node);
extern hl_type t$hl_urho3d_scene_node_ptr;
void haxe_ds_ObjectMap_set(haxe__ds__ObjectMap,vdynamic*,vdynamic*);
extern String s$Models_Box_mdl;
extern String s$Materials_Black_xml;
extern hl_type t$urho3d_actions_RepeatForever;
extern hl_type t$urho3d_actions_RotateBy;
extern hl_type t$_f64;
void urho3d_actions_RotateBy_new(urho3d__actions__RotateBy,double,double,vdynamic*,vdynamic*);
void urho3d_actions_RepeatForever_new(urho3d__actions__RepeatForever,urho3d__actions__FiniteTimeAction);
urho3d__actions__ActionID urho3d_actions_ActionManager_AddAction(urho3d__actions__ActionDef,urho3d__actions__FiniteTimeAction,urho3d__Node,urho3d__actions__FiniteTimeActionState,vclosure*);
extern hl_type t$samplygame_MachineGun;
void samplygame_MachineGun_new(samplygame__MachineGun);
extern hl_type t$urho3d_Component;
hl_urho3d_scene_component_ptr* urho3d_Component_get_pointer(urho3d__Component);
extern hl_type t$hl_urho3d_scene_component_ptr;
urho3d__Node urho3d_Component_set_node(urho3d__Component,urho3d__Node);
extern hl_type t$_dyn;
extern hl_type t$hl_urho3d_scene_component;
String Std_string(vdynamic*);
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
extern hl_type t$hl_types_ArrayDyn;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
#include <hl/types/ArrayBase.h>
hl__types__ArrayDyn hl_types_ArrayDyn_alloc(hl__types__ArrayBase,bool*);
void haxe_ds_StringMap_set(haxe__ds__StringMap,String,vdynamic*);
int hl_types_ArrayDyn_push(hl__types__ArrayDyn,vdynamic*);
extern hl_type t$samplygame_Missile;
void samplygame_Missile_new(samplygame__Missile);
extern hl_type t$urho3d_actions_EaseOut;
extern hl_type t$urho3d_actions_MoveBy;
void urho3d_actions_MoveBy_new(urho3d__actions__MoveBy,double,hl_urho3d_math_vector3*);
void urho3d_actions_EaseOut_new(urho3d__actions__EaseOut,urho3d__actions__FiniteTimeAction,double);
extern hl_type t$urho3d_actions_Sequence;
extern hl_type t$urho3d_actions_EaseBackInOut;
void urho3d_actions_EaseBackInOut_new(urho3d__actions__EaseBackInOut,urho3d__actions__FiniteTimeAction);
extern hl_type t$urho3d_actions_DelayTime;
void urho3d_actions_DelayTime_new(urho3d__actions__DelayTime,double);
void urho3d_actions_Sequence_new(urho3d__actions__Sequence,urho3d__actions__FiniteTimeAction,urho3d__actions__FiniteTimeAction,hl__types__ArrayObj);
void samplygame_Player_MoveRandomly(samplygame__Player);
#include <urho3d/Renderer.h>
#include <samplygame/Weapon.h>
#include <urho3d/_Vector3/Vector3_Impl_.h>
bool samplygame_Aircraft_IsAlive(samplygame__Aircraft);
int urho3d_Input_get_numTouches(void);
hl_urho3d_math_tintvector2* urho3d__TouchState_TouchState_Impl__get_position(hl_urho3d_input_touch_state*);
hl_urho3d_math_tintvector2* urho3d_Input_get_mousePosition(void);
extern urho3d__$Renderer g$_urho3d_Renderer;
hl_urho3d_math_tvector3* urho3d__Viewport_Viewport_Impl__ScreenToWorldPoint(hl_urho3d_graphics_viewport*,int,int,double);
extern samplygame__$Weapon g$_samplygame_Weapon;
extern hl_type t$_bool;
int hl_types_ArrayDyn_get_length(hl__types__ArrayDyn);
extern urho3d___Vector3__$Vector3_Impl_ g$_urho3d__Vector3_Vector3_Impl_;
double urho3d_LogicComponent_Random(urho3d__LogicComponent,vdynamic*,vdynamic*);
void samplygame_Player_RandmoMoveDone(samplygame__Player,urho3d__actions__ActionID);
extern hl_type t$fun_1e14212;
#include <urho3d/ParticleEmitter2D.h>
void urho3d_actions_ActionManager_RemoveAllActions(urho3d__Node);
bool haxe_ds_ObjectMap_remove(haxe__ds__ObjectMap,vdynamic*);
extern hl_type t$vrt_b840ca7;
extern hl_type t$String;
extern hl_type t$haxe_ds_StringMap;
bool haxe_ds_StringMap_remove(haxe__ds__StringMap,String);
vvirtual* haxe_ds_ObjectMap_iterator(haxe__ds__ObjectMap);
extern hl_type t$vrt_1cffe76;
extern hl_type t$fun_bf7849e;
extern hl_type t$fun_d937e10;
bool urho3d_Node_set_valid(urho3d__Node,bool);
vvirtual* haxe_ds_StringMap_iterator(haxe__ds__StringMap);
void urho3d_Node_CleanChildData(urho3d__Node);
void haxe_ds_StringMap_clear(haxe__ds__StringMap);
void haxe_ds_ObjectMap_clear(haxe__ds__ObjectMap);
extern String s$ParticleEmitter2D;
extern hl_type t$urho3d_ParticleEmitter2D;
void urho3d_ParticleEmitter2D_new(urho3d__ParticleEmitter2D,hl_urho3d_urho2d_particle_emitter2d*);
extern String s$Particles_PlayerExplosion_pex;
hl_urho3d_urho2d_particle_effect2d* urho3d_ParticleEmitter2D_set_effect(urho3d__ParticleEmitter2D,hl_urho3d_urho2d_particle_effect2d*);
#include <samplygame/SamplyGame.h>
extern samplygame__$SamplyGame g$_samplygame_SamplyGame;
extern hl_type t$_i32;
void samplygame_SamplyGame_OnPlayerHealthUpdate(samplygame__SamplyGame,double);
void samplygame_Aircraft_new(samplygame__Aircraft,vdynamic*);
extern String s$Player;

void samplygame_Player_Init(samplygame__Player r0) {
	bool *r54;
	String r8;
	samplygame__MachineGun r45;
	urho3d__actions__EaseBackInOut r59;
	hl_urho3d_scene_node_ptr *r28;
	hl_urho3d_scene_component *r5;
	urho3d__actions__EaseOut r56;
	urho3d__actions__FiniteTimeActionState r43;
	bool r26;
	urho3d__StaticModel r12, r31;
	urho3d__actions__MoveBy r57;
	hl_urho3d_math_vector3 *r25;
	hl_urho3d_math_quaternion *r23;
	urho3d__Node r2, r4, r22, r30, r34;
	hl_urho3d_math_tquaternion *r24;
	urho3d__Component r47;
	hl_urho3d_graphics_material *r15, *r16, *r33;
	urho3d__actions__FiniteTimeAction r61, r62;
	urho3d_context *r6;
	hl_urho3d_scene_component_ptr *r48;
	vclosure *r44;
	urho3d__actions__DelayTime r60;
	urho3d__actions__RotateBy r38;
	vdynamic *r29, *r41, *r42, *r46;
	urho3d__actions__ActionID r35;
	hl_urho3d_graphics_model *r13, *r14, *r32;
	int r9, r10;
	urho3d__actions__Sequence r58;
	haxe__ds__ObjectMap r27;
	hl__types__ArrayObj r53;
	haxe__ds__StringMap r49;
	urho3d__actions__RepeatForever r37;
	hl_type *r52;
	urho3d__actions__ActionDef r36;
	urho3d___Context__$Context_Impl_ r7;
	samplygame__Missile r55;
	float r19, r20, r21;
	hl_urho3d_scene_node *r3;
	hl__types__ArrayDyn r50;
	double r18, r39, r40;
	hl_urho3d_graphics_staticmodel *r11;
	hl_urho3d_math_tvector3 *r17;
	varray *r51;
	r2 = urho3d_Component_get_node(((urho3d__Component)r0));
	if( r2 == NULL ) hl_null_access();
	r3 = r2->abstractNode;
	if( !r3 ) goto label$defaeaf_1_12;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r3 = r2->abstractNode;
	r8 = (String)s$StaticModel;
	r9 = 0;
	r10 = 0;
	r5 = Urho3D__scene_node_create_component(r6,r3,r8,r9,r10);
	goto label$defaeaf_1_13;
	label$defaeaf_1_12:
	r5 = NULL;
	label$defaeaf_1_13:
	if( !r5 ) goto label$defaeaf_1_20;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r11 = Urho3D__graphics_staticmodel_cast_from_component(r6,r5);
	r12 = (urho3d__StaticModel)hl_alloc_obj(&t$urho3d_StaticModel);
	urho3d_StaticModel_new(r12,r11);
	goto label$defaeaf_1_21;
	label$defaeaf_1_20:
	r12 = NULL;
	label$defaeaf_1_21:
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r8 = (String)s$Models_Player_mdl;
	r13 = Urho3D__graphics_model_create(r6,r8);
	if( r12 == NULL ) hl_null_access();
	r14 = urho3d_StaticModel_set_model(r12,r13);
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r8 = (String)s$Materials_Player_xml;
	r15 = Urho3D__graphics_material_create(r6,r8);
	r16 = urho3d_StaticModel_set_material(r12,r15);
	r4 = urho3d_Component_get_node(((urho3d__Component)r0));
	r18 = 0.4500000000000000111;
	r19 = (float)r18;
	r18 = 0.4500000000000000111;
	r20 = (float)r18;
	r18 = 0.4500000000000000111;
	r21 = (float)r18;
	r17 = Urho3D__math_tvector3_create(r19,r20,r21);
	if( r4 == NULL ) hl_null_access();
	r3 = r4->abstractNode;
	if( !r3 ) goto label$defaeaf_1_47;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r3 = r4->abstractNode;
	Urho3D__scene_node_set_scale(r6,r3,r17);
	label$defaeaf_1_47:
	r4 = urho3d_Component_get_node(((urho3d__Component)r0));
	r17 = NULL;
	if( !r17 ) goto label$defaeaf_1_54;
	r9 = -40;
	r19 = (float)r9;
	r23 = Urho3D__math_quaternion_create_fv(r19,r17);
	goto label$defaeaf_1_61;
	label$defaeaf_1_54:
	r9 = -40;
	r19 = (float)r9;
	r9 = 0;
	r20 = (float)r9;
	r9 = 0;
	r21 = (float)r9;
	r23 = Urho3D__math_quaternion_create(r19,r20,r21);
	label$defaeaf_1_61:
	r24 = Urho3D__math_t_quaternion_cast_from_quaternion(r23);
	if( r4 == NULL ) hl_null_access();
	r3 = r4->abstractNode;
	if( !r3 ) goto label$defaeaf_1_69;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r3 = r4->abstractNode;
	Urho3D__scene_node_set_rotation(r6,r3,r24);
	label$defaeaf_1_69:
	r4 = urho3d_Component_get_node(((urho3d__Component)r0));
	r18 = 0.;
	r19 = (float)r18;
	r18 = -6.;
	r20 = (float)r18;
	r18 = 0.;
	r21 = (float)r18;
	r25 = Urho3D__math_vector3_create(r19,r20,r21);
	r17 = Urho3D__math_tvector3_cast_from_vector3(r25);
	if( r4 == NULL ) hl_null_access();
	r3 = r4->abstractNode;
	if( !r3 ) goto label$defaeaf_1_85;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r3 = r4->abstractNode;
	Urho3D__scene_node_set_position(r6,r3,r17);
	label$defaeaf_1_85:
	r4 = urho3d_Component_get_node(((urho3d__Component)r0));
	if( r4 == NULL ) hl_null_access();
	r3 = r4->abstractNode;
	if( !r3 ) goto label$defaeaf_1_106;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r3 = r4->abstractNode;
	r8 = (String)s$;
	r9 = 0;
	r10 = 0;
	r26 = false;
	r3 = Urho3D__scene_node_create_child(r6,r3,r8,r9,r10,r26);
	r22 = (urho3d__Node)hl_alloc_obj(&t$urho3d_Node);
	urho3d_Node_new(r22,r3);
	r27 = r4->children_pointers_map;
	if( r27 == NULL ) hl_null_access();
	r28 = urho3d_Node_get_pointer(r22);
	if( r28 == NULL ) r29 = NULL; else {
		r29 = hl_alloc_dynamic(&t$hl_urho3d_scene_node_ptr);
		r29->v.ptr = r28;
	}
	haxe_ds_ObjectMap_set(r27,r29,((vdynamic*)r22));
	r22->_parent = r4;
	goto label$defaeaf_1_107;
	label$defaeaf_1_106:
	r22 = NULL;
	label$defaeaf_1_107:
	r0->rotor = r22;
	r22 = r0->rotor;
	if( r22 == NULL ) hl_null_access();
	r3 = r22->abstractNode;
	if( !r3 ) goto label$defaeaf_1_120;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r3 = r22->abstractNode;
	r8 = (String)s$StaticModel;
	r9 = 0;
	r10 = 0;
	r5 = Urho3D__scene_node_create_component(r6,r3,r8,r9,r10);
	goto label$defaeaf_1_121;
	label$defaeaf_1_120:
	r5 = NULL;
	label$defaeaf_1_121:
	if( !r5 ) goto label$defaeaf_1_128;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r11 = Urho3D__graphics_staticmodel_cast_from_component(r6,r5);
	r31 = (urho3d__StaticModel)hl_alloc_obj(&t$urho3d_StaticModel);
	urho3d_StaticModel_new(r31,r11);
	goto label$defaeaf_1_129;
	label$defaeaf_1_128:
	r31 = NULL;
	label$defaeaf_1_129:
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r8 = (String)s$Models_Box_mdl;
	r14 = Urho3D__graphics_model_create(r6,r8);
	if( r31 == NULL ) hl_null_access();
	r32 = urho3d_StaticModel_set_model(r31,r14);
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r8 = (String)s$Materials_Black_xml;
	r16 = Urho3D__graphics_material_create(r6,r8);
	r33 = urho3d_StaticModel_set_material(r31,r16);
	r30 = r0->rotor;
	r18 = 0.1000000000000000056;
	r19 = (float)r18;
	r18 = 1.399999999999999911;
	r20 = (float)r18;
	r18 = 0.1000000000000000056;
	r21 = (float)r18;
	r25 = Urho3D__math_vector3_create(r19,r20,r21);
	r17 = Urho3D__math_tvector3_cast_from_vector3(r25);
	if( r30 == NULL ) hl_null_access();
	r3 = r30->abstractNode;
	if( !r3 ) goto label$defaeaf_1_156;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r3 = r30->abstractNode;
	Urho3D__scene_node_set_scale(r6,r3,r17);
	label$defaeaf_1_156:
	r30 = r0->rotor;
	r17 = NULL;
	if( !r17 ) goto label$defaeaf_1_163;
	r9 = 0;
	r19 = (float)r9;
	r23 = Urho3D__math_quaternion_create_fv(r19,r17);
	goto label$defaeaf_1_170;
	label$defaeaf_1_163:
	r9 = 0;
	r19 = (float)r9;
	r9 = 0;
	r20 = (float)r9;
	r9 = 0;
	r21 = (float)r9;
	r23 = Urho3D__math_quaternion_create(r19,r20,r21);
	label$defaeaf_1_170:
	r24 = Urho3D__math_t_quaternion_cast_from_quaternion(r23);
	if( r30 == NULL ) hl_null_access();
	r3 = r30->abstractNode;
	if( !r3 ) goto label$defaeaf_1_178;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r3 = r30->abstractNode;
	Urho3D__scene_node_set_rotation(r6,r3,r24);
	label$defaeaf_1_178:
	r30 = r0->rotor;
	r9 = 0;
	r19 = (float)r9;
	r18 = -0.1499999999999999944;
	r20 = (float)r18;
	r18 = 1.199999999999999956;
	r21 = (float)r18;
	r25 = Urho3D__math_vector3_create(r19,r20,r21);
	r17 = Urho3D__math_tvector3_cast_from_vector3(r25);
	if( r30 == NULL ) hl_null_access();
	r3 = r30->abstractNode;
	if( !r3 ) goto label$defaeaf_1_194;
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r3 = r30->abstractNode;
	Urho3D__scene_node_set_position(r6,r3,r17);
	label$defaeaf_1_194:
	r36 = NULL;
	r37 = (urho3d__actions__RepeatForever)hl_alloc_obj(&t$urho3d_actions_RepeatForever);
	r38 = (urho3d__actions__RotateBy)hl_alloc_obj(&t$urho3d_actions_RotateBy);
	r18 = 1.;
	r39 = 0.;
	r9 = 0;
	r40 = (double)r9;
	r41 = hl_alloc_dynamic(&t$_f64);
	r41->v.d = r40;
	r40 = 1440.;
	r42 = hl_alloc_dynamic(&t$_f64);
	r42->v.d = r40;
	urho3d_actions_RotateBy_new(r38,r18,r39,r41,r42);
	urho3d_actions_RepeatForever_new(r37,((urho3d__actions__FiniteTimeAction)r38));
	r30 = r0->rotor;
	r43 = NULL;
	r44 = NULL;
	r35 = urho3d_actions_ActionManager_AddAction(r36,((urho3d__actions__FiniteTimeAction)r37),r30,r43,r44);
	r30 = urho3d_Component_get_node(((urho3d__Component)r0));
	r45 = (samplygame__MachineGun)hl_alloc_obj(&t$samplygame_MachineGun);
	samplygame_MachineGun_new(r45);
	if( r30 == NULL ) hl_null_access();
	r3 = r30->abstractNode;
	if( !r3 ) goto label$defaeaf_1_256;
	r47 = (urho3d__Component)hl_dyn_castp(&r45,&t$samplygame_MachineGun,&t$urho3d_Component);
	r27 = r30->components_map;
	if( r27 == NULL ) hl_null_access();
	if( r47 == NULL ) hl_null_access();
	r48 = urho3d_Component_get_pointer(r47);
	if( r48 == NULL ) r46 = NULL; else {
		r46 = hl_alloc_dynamic(&t$hl_urho3d_scene_component_ptr);
		r46->v.ptr = r48;
	}
	haxe_ds_ObjectMap_set(r27,r46,((vdynamic*)r47));
	r34 = urho3d_Component_set_node(r47,r30);
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r3 = r30->abstractNode;
	r46 = (vdynamic*)hl_dyn_getp((vdynamic*)r45,-460463503/*abstractComponent*/,&t$_dyn);
	r5 = (hl_urho3d_scene_component*)hl_dyn_castp(&r46,&t$_dyn,&t$hl_urho3d_scene_component);
	r9 = 0;
	r10 = 0;
	Urho3D__scene_node_add_component(r6,r3,r5,r9,r10);
	r49 = r30->logic_components_map;
	if( r49 == NULL ) hl_null_access();
	r8 = Std_string(((vdynamic*)r45));
	r46 = haxe_ds_StringMap_get(r49,r8);
	r50 = (hl__types__ArrayDyn)hl_dyn_castp(&r46,&t$_dyn,&t$hl_types_ArrayDyn);
	if( r50 ) goto label$defaeaf_1_249;
	r52 = &t$_dyn;
	r9 = 0;
	r51 = hl_alloc_array(r52,r9);
	r53 = hl_types_ArrayObj_alloc(r51);
	r26 = true;
	r54 = &r26;
	r50 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r53),r54);
	r49 = r30->logic_components_map;
	if( r49 == NULL ) hl_null_access();
	r8 = Std_string(((vdynamic*)r45));
	haxe_ds_StringMap_set(r49,r8,((vdynamic*)r50));
	label$defaeaf_1_249:
	r49 = r30->logic_components_map;
	if( r49 == NULL ) hl_null_access();
	r8 = Std_string(((vdynamic*)r45));
	r46 = haxe_ds_StringMap_get(r49,r8);
	r50 = (hl__types__ArrayDyn)hl_dyn_castp(&r46,&t$_dyn,&t$hl_types_ArrayDyn);
	if( r50 == NULL ) hl_null_access();
	r9 = hl_types_ArrayDyn_push(r50,((vdynamic*)r45));
	label$defaeaf_1_256:
	r30 = urho3d_Component_get_node(((urho3d__Component)r0));
	r55 = (samplygame__Missile)hl_alloc_obj(&t$samplygame_Missile);
	samplygame_Missile_new(r55);
	if( r30 == NULL ) hl_null_access();
	r3 = r30->abstractNode;
	if( !r3 ) goto label$defaeaf_1_302;
	r47 = (urho3d__Component)hl_dyn_castp(&r55,&t$samplygame_Missile,&t$urho3d_Component);
	r27 = r30->components_map;
	if( r27 == NULL ) hl_null_access();
	if( r47 == NULL ) hl_null_access();
	r48 = urho3d_Component_get_pointer(r47);
	if( r48 == NULL ) r46 = NULL; else {
		r46 = hl_alloc_dynamic(&t$hl_urho3d_scene_component_ptr);
		r46->v.ptr = r48;
	}
	haxe_ds_ObjectMap_set(r27,r46,((vdynamic*)r47));
	r34 = urho3d_Component_set_node(r47,r30);
	r7 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r6 = r7->context;
	r3 = r30->abstractNode;
	r46 = (vdynamic*)hl_dyn_getp((vdynamic*)r55,-460463503/*abstractComponent*/,&t$_dyn);
	r5 = (hl_urho3d_scene_component*)hl_dyn_castp(&r46,&t$_dyn,&t$hl_urho3d_scene_component);
	r9 = 0;
	r10 = 0;
	Urho3D__scene_node_add_component(r6,r3,r5,r9,r10);
	r49 = r30->logic_components_map;
	if( r49 == NULL ) hl_null_access();
	r8 = Std_string(((vdynamic*)r55));
	r46 = haxe_ds_StringMap_get(r49,r8);
	r50 = (hl__types__ArrayDyn)hl_dyn_castp(&r46,&t$_dyn,&t$hl_types_ArrayDyn);
	if( r50 ) goto label$defaeaf_1_295;
	r52 = &t$_dyn;
	r9 = 0;
	r51 = hl_alloc_array(r52,r9);
	r53 = hl_types_ArrayObj_alloc(r51);
	r26 = true;
	r54 = &r26;
	r50 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r53),r54);
	r49 = r30->logic_components_map;
	if( r49 == NULL ) hl_null_access();
	r8 = Std_string(((vdynamic*)r55));
	haxe_ds_StringMap_set(r49,r8,((vdynamic*)r50));
	label$defaeaf_1_295:
	r49 = r30->logic_components_map;
	if( r49 == NULL ) hl_null_access();
	r8 = Std_string(((vdynamic*)r55));
	r46 = haxe_ds_StringMap_get(r49,r8);
	r50 = (hl__types__ArrayDyn)hl_dyn_castp(&r46,&t$_dyn,&t$hl_types_ArrayDyn);
	if( r50 == NULL ) hl_null_access();
	r9 = hl_types_ArrayDyn_push(r50,((vdynamic*)r55));
	label$defaeaf_1_302:
	r9 = 0;
	r19 = (float)r9;
	r9 = 3;
	r20 = (float)r9;
	r9 = 0;
	r21 = (float)r9;
	r25 = Urho3D__math_vector3_create(r19,r20,r21);
	r36 = NULL;
	r56 = (urho3d__actions__EaseOut)hl_alloc_obj(&t$urho3d_actions_EaseOut);
	r57 = (urho3d__actions__MoveBy)hl_alloc_obj(&t$urho3d_actions_MoveBy);
	r18 = 0.5;
	urho3d_actions_MoveBy_new(r57,r18,r25);
	r18 = 2.;
	urho3d_actions_EaseOut_new(r56,((urho3d__actions__FiniteTimeAction)r57),r18);
	r30 = urho3d_Component_get_node(((urho3d__Component)r0));
	r43 = NULL;
	r44 = NULL;
	r35 = urho3d_actions_ActionManager_AddAction(r36,((urho3d__actions__FiniteTimeAction)r56),r30,r43,r44);
	r58 = (urho3d__actions__Sequence)hl_alloc_obj(&t$urho3d_actions_Sequence);
	r59 = (urho3d__actions__EaseBackInOut)hl_alloc_obj(&t$urho3d_actions_EaseBackInOut);
	r38 = (urho3d__actions__RotateBy)hl_alloc_obj(&t$urho3d_actions_RotateBy);
	r18 = 1.;
	r39 = 0.;
	r40 = 0.;
	r41 = hl_alloc_dynamic(&t$_f64);
	r41->v.d = r40;
	r40 = 360.;
	r42 = hl_alloc_dynamic(&t$_f64);
	r42->v.d = r40;
	urho3d_actions_RotateBy_new(r38,r18,r39,r41,r42);
	urho3d_actions_EaseBackInOut_new(r59,((urho3d__actions__FiniteTimeAction)r38));
	r60 = (urho3d__actions__DelayTime)hl_alloc_obj(&t$urho3d_actions_DelayTime);
	r18 = 5.;
	urho3d_actions_DelayTime_new(r60,r18);
	r53 = NULL;
	urho3d_actions_Sequence_new(r58,((urho3d__actions__FiniteTimeAction)r59),((urho3d__actions__FiniteTimeAction)r60),r53);
	r61 = ((urho3d__actions__FiniteTimeAction)r58);
	r58 = (urho3d__actions__Sequence)hl_alloc_obj(&t$urho3d_actions_Sequence);
	r59 = (urho3d__actions__EaseBackInOut)hl_alloc_obj(&t$urho3d_actions_EaseBackInOut);
	r38 = (urho3d__actions__RotateBy)hl_alloc_obj(&t$urho3d_actions_RotateBy);
	r18 = 1.;
	r39 = 0.;
	r40 = 0.;
	r41 = hl_alloc_dynamic(&t$_f64);
	r41->v.d = r40;
	r40 = -360.;
	r42 = hl_alloc_dynamic(&t$_f64);
	r42->v.d = r40;
	urho3d_actions_RotateBy_new(r38,r18,r39,r41,r42);
	urho3d_actions_EaseBackInOut_new(r59,((urho3d__actions__FiniteTimeAction)r38));
	r60 = (urho3d__actions__DelayTime)hl_alloc_obj(&t$urho3d_actions_DelayTime);
	r18 = 5.;
	urho3d_actions_DelayTime_new(r60,r18);
	r53 = NULL;
	urho3d_actions_Sequence_new(r58,((urho3d__actions__FiniteTimeAction)r59),((urho3d__actions__FiniteTimeAction)r60),r53);
	r62 = ((urho3d__actions__FiniteTimeAction)r58);
	r36 = NULL;
	r37 = (urho3d__actions__RepeatForever)hl_alloc_obj(&t$urho3d_actions_RepeatForever);
	r58 = (urho3d__actions__Sequence)hl_alloc_obj(&t$urho3d_actions_Sequence);
	r53 = NULL;
	urho3d_actions_Sequence_new(r58,r61,r62,r53);
	urho3d_actions_RepeatForever_new(r37,((urho3d__actions__FiniteTimeAction)r58));
	r30 = urho3d_Component_get_node(((urho3d__Component)r0));
	r43 = NULL;
	r44 = NULL;
	r35 = urho3d_actions_ActionManager_AddAction(r36,((urho3d__actions__FiniteTimeAction)r37),r30,r43,r44);
	samplygame_Player_MoveRandomly(r0);
	return;
}

void samplygame_Player_Update(samplygame__Player r0,double r1) {
	bool *r36;
	samplygame__$Weapon r28;
	hl__types__ArrayObj r35;
	hl_type *r34;
	urho3d___Vector3__$Vector3_Impl_ r45;
	bool r3, r12, r31;
	hl_urho3d_math_vector3 *r44;
	urho3d__Node r20, r21;
	urho3d__$Renderer r14;
	hl_urho3d_math_tintvector2 *r11;
	urho3d___Context__$Context_Impl_ r10;
	hl_urho3d_scene_node *r22;
	float r18, r24, r25;
	hl_urho3d_graphics_viewport *r13, *r16;
	urho3d_context *r9;
	hl_urho3d_input_touch_state *r8;
	hl__types__ArrayDyn r32, r41;
	double r17, r27;
	vdynamic *r29, *r39, *r40, *r42;
	hl_urho3d_math_tvector3 *r15, *r19, *r23, *r26, *r43;
	varray *r30, *r33;
	int r4, r5, r6, r7, r37, r38;
	r3 = samplygame_Aircraft_IsAlive(((samplygame__Aircraft)r0));
	if( !r3 ) goto label$defaeaf_2_201;
	r4 = 0;
	r5 = 0;
	r3 = false;
	r6 = urho3d_Input_get_numTouches();
	r7 = 0;
	if( r7 >= r6 ) goto label$defaeaf_2_21;
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r6 = 0;
	r8 = Urho3D__input_touch_state_get(r9,r6);
	r11 = urho3d__TouchState_TouchState_Impl__get_position(r8);
	r6 = Urho3D__math_tintvector2_get_x(r11);
	r4 = r6;
	r6 = Urho3D__math_tintvector2_get_y(r11);
	r7 = r0->offsetY;
	r6 = r6 + r7;
	r5 = r6;
	r12 = true;
	r3 = r12;
	label$defaeaf_2_21:
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r6 = 1;
	r12 = Urho3D__input_get_mouse_button_down(r9,r6);
	if( !r12 ) goto label$defaeaf_2_35;
	r11 = urho3d_Input_get_mousePosition();
	r6 = Urho3D__math_tintvector2_get_x(r11);
	r4 = r6;
	r6 = Urho3D__math_tintvector2_get_y(r11);
	r7 = r0->offsetY;
	r6 = r6 + r7;
	r5 = r6;
	r12 = true;
	r3 = r12;
	label$defaeaf_2_35:
	if( !r3 ) goto label$defaeaf_2_153;
	r14 = (urho3d__$Renderer)g$_urho3d_Renderer;
	r13 = r14->viewports;
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r6 = 0;
	r16 = Urho3D__graphics_renderer_get_viewport(r9,r6);
	r17 = 10.;
	r15 = urho3d__Viewport_Viewport_Impl__ScreenToWorldPoint(r16,r4,r5,r17);
	r6 = 0;
	r18 = (float)r6;
	r18 = Urho3D__math_tvector3_set_z(r15,r18);
	r20 = urho3d_Component_get_node(((urho3d__Component)r0));
	r21 = urho3d_Component_get_node(((urho3d__Component)r0));
	if( r21 == NULL ) hl_null_access();
	r22 = r21->abstractNode;
	if( !r22 ) goto label$defaeaf_2_58;
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r22 = r21->abstractNode;
	r23 = Urho3D__scene_node_get_world_position(r9,r22);
	r19 = r23;
	goto label$defaeaf_2_66;
	label$defaeaf_2_58:
	r17 = 0.;
	r18 = (float)r17;
	r17 = 0.;
	r24 = (float)r17;
	r17 = 0.;
	r25 = (float)r17;
	r23 = Urho3D__math_tvector3_create(r18,r24,r25);
	r19 = r23;
	label$defaeaf_2_66:
	r18 = Urho3D__math_tvector3_get_x(r15);
	r17 = (double)r18;
	r18 = Urho3D__math_tvector3_get_x(r19);
	r27 = (double)r18;
	r17 = r17 - r27;
	r18 = (float)r17;
	r24 = Urho3D__math_tvector3_get_y(r15);
	r17 = (double)r24;
	r24 = Urho3D__math_tvector3_get_y(r19);
	r27 = (double)r24;
	r17 = r17 - r27;
	r24 = (float)r17;
	r25 = Urho3D__math_tvector3_get_z(r15);
	r17 = (double)r25;
	r25 = Urho3D__math_tvector3_get_z(r19);
	r27 = (double)r25;
	r17 = r17 - r27;
	r25 = (float)r17;
	r23 = Urho3D__math_tvector3_create(r18,r24,r25);
	if( r20 == NULL ) hl_null_access();
	r22 = r20->abstractNode;
	if( !r22 ) goto label$defaeaf_2_93;
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r22 = r20->abstractNode;
	r6 = 2;
	Urho3D__scene_node_translate(r9,r22,r23,r6);
	label$defaeaf_2_93:
	r20 = urho3d_Component_get_node(((urho3d__Component)r0));
	r28 = (samplygame__$Weapon)g$_samplygame_Weapon;
	r29 = ((vdynamic*)r28);
	r12 = true;
	if( r20 == NULL ) hl_null_access();
	r22 = r20->abstractNode;
	if( !r22 ) goto label$defaeaf_2_131;
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r22 = r20->abstractNode;
	r30 = Urho3D__scene_node_get_all_logic_components(r9,r22,r12);
	r34 = &t$_dyn;
	r6 = 0;
	r33 = hl_alloc_array(r34,r6);
	r35 = hl_types_ArrayObj_alloc(r33);
	r31 = true;
	r36 = &r31;
	r32 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r35),r36);
	if( !r30 ) goto label$defaeaf_2_129;
	r6 = 0;
	r7 = r30->size;
	label$defaeaf_2_114:
	if( r6 >= r7 ) goto label$defaeaf_2_129;
	r37 = r6;
	++r6;
	r39 = ((vdynamic**)(r30 + 1))[r37];
	if( r39 == NULL ) hl_null_access();
	r39 = (vdynamic*)hl_dyn_getp((vdynamic*)r39,3655927/*IsA*/,&t$_dyn);
	if( r39 == NULL ) hl_null_access();
	{
		vdynamic *args[] = {r29};
		r39 = (vdynamic*)hl_dyn_call((vclosure*)r39,args,1);
	}
	r31 = (bool)hl_dyn_casti(&r39,&t$_dyn,&t$_bool);
	if( !r31 ) goto label$defaeaf_2_128;
	if( r32 == NULL ) hl_null_access();
	r39 = ((vdynamic**)(r30 + 1))[r37];
	r38 = hl_types_ArrayDyn_push(r32,r39);
	label$defaeaf_2_128:
	goto label$defaeaf_2_114;
	label$defaeaf_2_129:
	r41 = r32;
	goto label$defaeaf_2_139;
	label$defaeaf_2_131:
	r34 = &t$_dyn;
	r6 = 0;
	r30 = hl_alloc_array(r34,r6);
	r35 = hl_types_ArrayObj_alloc(r30);
	r31 = true;
	r36 = &r31;
	r32 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r35),r36);
	r41 = r32;
	label$defaeaf_2_139:
	r6 = 0;
	label$defaeaf_2_140:
	if( r41 == NULL ) hl_null_access();
	r37 = hl_types_ArrayDyn_get_length(r41);
	if( r6 >= r37 ) goto label$defaeaf_2_153;
	r39 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r41->$type->vobj_proto[0])(r41,r6);
	++r6;
	if( r39 == NULL ) hl_null_access();
	r40 = (vdynamic*)hl_dyn_getp((vdynamic*)r39,-474396927/*FireAsync*/,&t$_dyn);
	if( r40 == NULL ) hl_null_access();
	r31 = true;
	r42 = hl_alloc_dynbool(r31);
	{
		vdynamic *args[] = {r42};
		r40 = (vdynamic*)hl_dyn_call((vclosure*)r40,args,1);
	}
	goto label$defaeaf_2_140;
	label$defaeaf_2_153:
	r20 = urho3d_Component_get_node(((urho3d__Component)r0));
	r21 = urho3d_Component_get_node(((urho3d__Component)r0));
	if( r21 == NULL ) hl_null_access();
	r22 = r21->abstractNode;
	if( !r22 ) goto label$defaeaf_2_163;
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r22 = r21->abstractNode;
	r19 = Urho3D__scene_node_get_world_position(r9,r22);
	goto label$defaeaf_2_170;
	label$defaeaf_2_163:
	r17 = 0.;
	r18 = (float)r17;
	r17 = 0.;
	r24 = (float)r17;
	r17 = 0.;
	r25 = (float)r17;
	r19 = Urho3D__math_tvector3_create(r18,r24,r25);
	label$defaeaf_2_170:
	r6 = 0;
	r18 = (float)r6;
	r24 = Urho3D__math_tvector3_get_y(r19);
	r17 = (double)r24;
	r27 = 10.;
	r17 = r17 + r27;
	r24 = (float)r17;
	r6 = 10;
	r25 = (float)r6;
	r19 = Urho3D__math_tvector3_create(r18,r24,r25);
	r6 = 0;
	r18 = (float)r6;
	r6 = 1;
	r24 = (float)r6;
	r6 = -1;
	r25 = (float)r6;
	r23 = Urho3D__math_tvector3_create(r18,r24,r25);
	r26 = r23;
	if( r20 == NULL ) hl_null_access();
	r22 = r20->abstractNode;
	if( !r22 ) goto label$defaeaf_2_201;
	if( r23 ) goto label$defaeaf_2_196;
	r45 = (urho3d___Vector3__$Vector3_Impl_)g$_urho3d__Vector3_Vector3_Impl_;
	r44 = r45->UP;
	r43 = Urho3D__math_tvector3_cast_from_vector3(r44);
	r26 = r43;
	label$defaeaf_2_196:
	r10 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r9 = r10->context;
	r22 = r20->abstractNode;
	r6 = 2;
	r12 = Urho3D__scene_node_look_at(r9,r22,r19,r26,r6);
	label$defaeaf_2_201:
	return;
}

void samplygame_Player_MoveRandomly(samplygame__Player r0) {
	urho3d__actions__Sequence r14;
	hl__types__ArrayObj r16;
	urho3d__actions__ActionDef r13;
	urho3d__actions__FiniteTimeActionState r18;
	bool r2;
	urho3d__Node r17;
	urho3d__actions__MoveBy r11;
	hl_urho3d_math_vector3 *r3;
	urho3d__actions__FiniteTimeAction r15;
	float r7, r8, r10;
	vclosure *r19;
	double r4;
	vdynamic *r5, *r6;
	urho3d__actions__ActionID r12;
	int r9;
	r2 = samplygame_Aircraft_IsAlive(((samplygame__Aircraft)r0));
	if( !r2 ) goto label$defaeaf_3_29;
	r4 = -0.4000000000000000222;
	r5 = hl_alloc_dynamic(&t$_f64);
	r5->v.d = r4;
	r4 = 0.4000000000000000222;
	r6 = hl_alloc_dynamic(&t$_f64);
	r6->v.d = r4;
	r4 = urho3d_LogicComponent_Random(((urho3d__LogicComponent)r0),r5,r6);
	r7 = (float)r4;
	r4 = -0.4000000000000000222;
	r5 = hl_alloc_dynamic(&t$_f64);
	r5->v.d = r4;
	r4 = 0.4000000000000000222;
	r6 = hl_alloc_dynamic(&t$_f64);
	r6->v.d = r4;
	r4 = urho3d_LogicComponent_Random(((urho3d__LogicComponent)r0),r5,r6);
	r8 = (float)r4;
	r9 = 0;
	r10 = (float)r9;
	r3 = Urho3D__math_vector3_create(r7,r8,r10);
	r11 = (urho3d__actions__MoveBy)hl_alloc_obj(&t$urho3d_actions_MoveBy);
	r4 = 0.75;
	urho3d_actions_MoveBy_new(r11,r4,r3);
	r13 = NULL;
	r14 = (urho3d__actions__Sequence)hl_alloc_obj(&t$urho3d_actions_Sequence);
	r15 = ((urho3d__actions__FiniteTimeAction (*)(urho3d__actions__MoveBy))r11->$type->vobj_proto[0])(r11);
	r16 = NULL;
	urho3d_actions_Sequence_new(r14,((urho3d__actions__FiniteTimeAction)r11),r15,r16);
	r17 = urho3d_Component_get_node(((urho3d__Component)r0));
	r18 = NULL;
	r19 = hl_alloc_closure_ptr(&t$fun_1e14212,samplygame_Player_RandmoMoveDone,r0);
	r12 = urho3d_actions_ActionManager_AddAction(r13,((urho3d__actions__FiniteTimeAction)r14),r17,r18,r19);
	label$defaeaf_3_29:
	return;
}

void samplygame_Player_RandmoMoveDone(samplygame__Player r0,urho3d__actions__ActionID r1) {
	urho3d__actions__Sequence r15;
	hl__types__ArrayObj r17;
	urho3d__actions__ActionDef r14;
	urho3d__actions__FiniteTimeActionState r19;
	bool r3;
	urho3d__Node r18;
	urho3d__actions__MoveBy r12;
	hl_urho3d_math_vector3 *r4;
	urho3d__actions__FiniteTimeAction r16;
	float r8, r9, r11;
	vclosure *r20;
	double r5;
	vdynamic *r6, *r7;
	urho3d__actions__ActionID r13;
	int r10;
	r3 = samplygame_Aircraft_IsAlive(((samplygame__Aircraft)r0));
	if( !r3 ) goto label$defaeaf_4_29;
	r5 = -0.4000000000000000222;
	r6 = hl_alloc_dynamic(&t$_f64);
	r6->v.d = r5;
	r5 = 0.4000000000000000222;
	r7 = hl_alloc_dynamic(&t$_f64);
	r7->v.d = r5;
	r5 = urho3d_LogicComponent_Random(((urho3d__LogicComponent)r0),r6,r7);
	r8 = (float)r5;
	r5 = -0.4000000000000000222;
	r6 = hl_alloc_dynamic(&t$_f64);
	r6->v.d = r5;
	r5 = 0.4000000000000000222;
	r7 = hl_alloc_dynamic(&t$_f64);
	r7->v.d = r5;
	r5 = urho3d_LogicComponent_Random(((urho3d__LogicComponent)r0),r6,r7);
	r9 = (float)r5;
	r10 = 0;
	r11 = (float)r10;
	r4 = Urho3D__math_vector3_create(r8,r9,r11);
	r12 = (urho3d__actions__MoveBy)hl_alloc_obj(&t$urho3d_actions_MoveBy);
	r5 = 0.75;
	urho3d_actions_MoveBy_new(r12,r5,r4);
	r14 = NULL;
	r15 = (urho3d__actions__Sequence)hl_alloc_obj(&t$urho3d_actions_Sequence);
	r16 = ((urho3d__actions__FiniteTimeAction (*)(urho3d__actions__MoveBy))r12->$type->vobj_proto[0])(r12);
	r17 = NULL;
	urho3d_actions_Sequence_new(r15,((urho3d__actions__FiniteTimeAction)r12),r16,r17);
	r18 = urho3d_Component_get_node(((urho3d__Component)r0));
	r19 = NULL;
	r20 = hl_alloc_closure_ptr(&t$fun_1e14212,samplygame_Player_RandmoMoveDone,r0);
	r13 = urho3d_actions_ActionManager_AddAction(r14,((urho3d__actions__FiniteTimeAction)r15),r18,r19,r20);
	label$defaeaf_4_29:
	return;
}

void samplygame_Player_OnExplode(samplygame__Player r0,urho3d__Node r1) {
	hl_urho3d_urho2d_particle_effect2d *r36, *r37;
	String r15, r19;
	urho3d__ParticleEmitter2D r35;
	haxe__ds__ObjectMap r10;
	vvirtual *r14, *r21, *r22, *r23, *r25;
	haxe__ds__StringMap r13;
	hl_urho3d_scene_component *r32;
	hl_urho3d_scene_node_ptr *r11;
	hl_urho3d_urho2d_particle_emitter2d *r34;
	bool r4, r8;
	urho3d__Node r3, r6, r9, r24, r26;
	urho3d___Context__$Context_Impl_ r18;
	float r29, r30, r31;
	urho3d_context *r17;
	hl_urho3d_scene_node *r5, *r7;
	double r28;
	hl_urho3d_math_tvector3 *r27;
	vdynamic *r12;
	int r20, r33;
	vbyte *r16;
	r3 = r0->rotor;
	urho3d_actions_ActionManager_RemoveAllActions(r3);
	r3 = r0->rotor;
	if( r3 == NULL ) hl_null_access();
	r5 = r3->abstractNode;
	r7 = NULL;
	if( r5 != r7 ) goto label$defaeaf_5_9;
	r4 = false;
	goto label$defaeaf_5_10;
	label$defaeaf_5_9:
	r4 = true;
	label$defaeaf_5_10:
	r8 = true;
	if( r4 != r8 ) goto label$defaeaf_5_922;
	r6 = r3->_parent;
	if( !r6 ) goto label$defaeaf_5_496;
	r6 = r3->_parent;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->abstractNode;
	r7 = NULL;
	if( r5 != r7 ) goto label$defaeaf_5_21;
	r4 = false;
	goto label$defaeaf_5_22;
	label$defaeaf_5_21:
	r4 = true;
	label$defaeaf_5_22:
	r8 = true;
	if( r4 != r8 ) goto label$defaeaf_5_495;
	r5 = r3->abstractNode;
	r7 = NULL;
	if( r5 != r7 ) goto label$defaeaf_5_29;
	r4 = false;
	goto label$defaeaf_5_30;
	label$defaeaf_5_29:
	r4 = true;
	label$defaeaf_5_30:
	r8 = true;
	if( r4 != r8 ) goto label$defaeaf_5_495;
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r11 = urho3d_Node_get_pointer(r3);
	if( r11 == NULL ) r12 = NULL; else {
		r12 = hl_alloc_dynamic(&t$hl_urho3d_scene_node_ptr);
		r12->v.ptr = r11;
	}
	r4 = haxe_ds_ObjectMap_remove(r10,r12);
	r13 = r6->children_name_map;
	if( r13 ) goto label$defaeaf_5_41;
	r14 = NULL;
	goto label$defaeaf_5_45;
	label$defaeaf_5_41:
	r14 = r13->f$1;
	if( r14 ) goto label$defaeaf_5_45;
	r14 = hl_to_virtual(&t$vrt_b840ca7,(vdynamic*)r13);
	r13->f$1 = r14;
	label$defaeaf_5_45:
	r5 = r3->abstractNode;
	if( !r5 ) goto label$defaeaf_5_64;
	r15 = r3->_name;
	if( r15 ) goto label$defaeaf_5_62;
	r18 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r17 = r18->context;
	r5 = r3->abstractNode;
	r16 = Urho3D__scene_node_get_name(r17,r5);
	if( r16 ) goto label$defaeaf_5_56;
	r19 = NULL;
	goto label$defaeaf_5_61;
	label$defaeaf_5_56:
	r19 = (String)hl_alloc_obj(&t$String);
	r19->bytes = r16;
	r20 = 0;
	r20 = hl_ucs2length(r16,r20);
	r19->length = r20;
	label$defaeaf_5_61:
	r3->_name = r19;
	label$defaeaf_5_62:
	r19 = r3->_name;
	goto label$defaeaf_5_65;
	label$defaeaf_5_64:
	r19 = (String)s$;
	label$defaeaf_5_65:
	r13 = (haxe__ds__StringMap)hl_dyn_castp(&r14,&t$vrt_b840ca7,&t$haxe_ds_StringMap);
	if( r13 == NULL ) hl_null_access();
	r4 = haxe_ds_StringMap_remove(r13,r19);
	r18 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r17 = r18->context;
	r5 = r6->abstractNode;
	r7 = r3->abstractNode;
	Urho3D__scene_node_remove_child(r17,r5,r7);
	r10 = r3->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_77:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_226;
	if( hl_vfields(r22)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_87:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_96;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r4 = false;
	r4 = urho3d_Node_set_valid(r24,r4);
	goto label$defaeaf_5_87;
	label$defaeaf_5_96:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_101:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_110;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r4 = false;
	r4 = urho3d_Node_set_valid(r24,r4);
	goto label$defaeaf_5_101;
	label$defaeaf_5_110:
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_115:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_160;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_125:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_133;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$defaeaf_5_125;
	label$defaeaf_5_133:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_138:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_146;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$defaeaf_5_138;
	label$defaeaf_5_146:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r24->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$defaeaf_5_115;
	label$defaeaf_5_160:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_165:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_210;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_175:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_183;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$defaeaf_5_175;
	label$defaeaf_5_183:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_188:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_196;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$defaeaf_5_188;
	label$defaeaf_5_196:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r24->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$defaeaf_5_165;
	label$defaeaf_5_210:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r5 = NULL;
	r9->abstractNode = r5;
	goto label$defaeaf_5_77;
	label$defaeaf_5_226:
	if( r3 == NULL ) hl_null_access();
	r13 = r3->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_231:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_380;
	if( hl_vfields(r22)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_241:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_250;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r4 = false;
	r4 = urho3d_Node_set_valid(r24,r4);
	goto label$defaeaf_5_241;
	label$defaeaf_5_250:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_255:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_264;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r4 = false;
	r4 = urho3d_Node_set_valid(r24,r4);
	goto label$defaeaf_5_255;
	label$defaeaf_5_264:
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_269:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_314;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_279:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_287;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$defaeaf_5_279;
	label$defaeaf_5_287:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_292:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_300;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$defaeaf_5_292;
	label$defaeaf_5_300:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r24->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$defaeaf_5_269;
	label$defaeaf_5_314:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_319:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_364;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_329:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_337;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$defaeaf_5_329;
	label$defaeaf_5_337:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_342:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_350;
	if( hl_vfields(r25)[1] ) r26 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r26 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r26 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r26);
	goto label$defaeaf_5_342;
	label$defaeaf_5_350:
	if( r24 == NULL ) hl_null_access();
	r13 = r24->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r24->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r24->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$defaeaf_5_319;
	label$defaeaf_5_364:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r5 = NULL;
	r9->abstractNode = r5;
	goto label$defaeaf_5_231;
	label$defaeaf_5_380:
	if( r3 == NULL ) hl_null_access();
	r10 = r3->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_385:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_430;
	if( hl_vfields(r22)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_395:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_403;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$defaeaf_5_395;
	label$defaeaf_5_403:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_408:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_416;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$defaeaf_5_408;
	label$defaeaf_5_416:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$defaeaf_5_385;
	label$defaeaf_5_430:
	if( r3 == NULL ) hl_null_access();
	r13 = r3->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_435:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_480;
	if( hl_vfields(r22)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_445:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_453;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$defaeaf_5_445;
	label$defaeaf_5_453:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_458:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_466;
	if( hl_vfields(r23)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$defaeaf_5_458;
	label$defaeaf_5_466:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$defaeaf_5_435;
	label$defaeaf_5_480:
	if( r3 == NULL ) hl_null_access();
	r13 = r3->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r3->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r3->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r3->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r5 = NULL;
	r3->abstractNode = r5;
	label$defaeaf_5_495:
	goto label$defaeaf_5_922;
	label$defaeaf_5_496:
	r18 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r17 = r18->context;
	r5 = r3->abstractNode;
	Urho3D__scene_node_remove(r17,r5);
	r10 = r3->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_504:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_653;
	if( hl_vfields(r22)[1] ) r6 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r6 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r6 == NULL ) hl_null_access();
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_514:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_523;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r4 = false;
	r4 = urho3d_Node_set_valid(r9,r4);
	goto label$defaeaf_5_514;
	label$defaeaf_5_523:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_528:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_537;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r4 = false;
	r4 = urho3d_Node_set_valid(r9,r4);
	goto label$defaeaf_5_528;
	label$defaeaf_5_537:
	if( r6 == NULL ) hl_null_access();
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_542:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_587;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_552:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_560;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$defaeaf_5_552;
	label$defaeaf_5_560:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_565:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_573;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$defaeaf_5_565;
	label$defaeaf_5_573:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$defaeaf_5_542;
	label$defaeaf_5_587:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_592:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_637;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_602:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_610;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$defaeaf_5_602;
	label$defaeaf_5_610:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_615:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_623;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$defaeaf_5_615;
	label$defaeaf_5_623:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$defaeaf_5_592;
	label$defaeaf_5_637:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r6->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r5 = NULL;
	r6->abstractNode = r5;
	goto label$defaeaf_5_504;
	label$defaeaf_5_653:
	if( r3 == NULL ) hl_null_access();
	r13 = r3->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_658:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_807;
	if( hl_vfields(r22)[1] ) r6 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r6 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r6 == NULL ) hl_null_access();
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_668:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_677;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r4 = false;
	r4 = urho3d_Node_set_valid(r9,r4);
	goto label$defaeaf_5_668;
	label$defaeaf_5_677:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_682:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_691;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r4 = false;
	r4 = urho3d_Node_set_valid(r9,r4);
	goto label$defaeaf_5_682;
	label$defaeaf_5_691:
	if( r6 == NULL ) hl_null_access();
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_696:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_741;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_706:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_714;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$defaeaf_5_706;
	label$defaeaf_5_714:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_719:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_727;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$defaeaf_5_719;
	label$defaeaf_5_727:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$defaeaf_5_696;
	label$defaeaf_5_741:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_746:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_791;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_756:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_764;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$defaeaf_5_756;
	label$defaeaf_5_764:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r25 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_769:
	if( r25 == NULL ) hl_null_access();
	if( hl_vfields(r25)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r25)[0])(r25->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r25->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_777;
	if( hl_vfields(r25)[1] ) r24 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r25)[1])(r25->value); else {
		r24 = (urho3d__Node)hl_dyn_call_obj(r25->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r24 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r24);
	goto label$defaeaf_5_769;
	label$defaeaf_5_777:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r9->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r9->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$defaeaf_5_746;
	label$defaeaf_5_791:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r6->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r5 = NULL;
	r6->abstractNode = r5;
	goto label$defaeaf_5_658;
	label$defaeaf_5_807:
	if( r3 == NULL ) hl_null_access();
	r10 = r3->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_812:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_857;
	if( hl_vfields(r22)[1] ) r6 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r6 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r6 == NULL ) hl_null_access();
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_822:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_830;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r9);
	goto label$defaeaf_5_822;
	label$defaeaf_5_830:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_835:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_843;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r9);
	goto label$defaeaf_5_835;
	label$defaeaf_5_843:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r6->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$defaeaf_5_812;
	label$defaeaf_5_857:
	if( r3 == NULL ) hl_null_access();
	r13 = r3->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r22 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_862:
	if( r22 == NULL ) hl_null_access();
	if( hl_vfields(r22)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r22)[0])(r22->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r22->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_907;
	if( hl_vfields(r22)[1] ) r6 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r22)[1])(r22->value); else {
		r6 = (urho3d__Node)hl_dyn_call_obj(r22->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r6 == NULL ) hl_null_access();
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	r21 = haxe_ds_ObjectMap_iterator(r10);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_872:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_880;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r9);
	goto label$defaeaf_5_872;
	label$defaeaf_5_880:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_iterator(r13);
	r23 = hl_to_virtual(&t$vrt_1cffe76,(vdynamic*)r21);
	label$defaeaf_5_885:
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$defaeaf_5_893;
	if( hl_vfields(r23)[1] ) r9 = ((urho3d__Node (*)(vdynamic*))hl_vfields(r23)[1])(r23->value); else {
		r9 = (urho3d__Node)hl_dyn_call_obj(r23->value,&t$fun_d937e10,151160317/*next*/,NULL,NULL);
	}
	if( r9 == NULL ) hl_null_access();
	urho3d_Node_CleanChildData(r9);
	goto label$defaeaf_5_885;
	label$defaeaf_5_893:
	if( r6 == NULL ) hl_null_access();
	r13 = r6->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r6->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r6->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	goto label$defaeaf_5_862;
	label$defaeaf_5_907:
	if( r3 == NULL ) hl_null_access();
	r13 = r3->children_name_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r3->components_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r13 = r3->logic_components_map;
	if( r13 == NULL ) hl_null_access();
	haxe_ds_StringMap_clear(r13);
	r10 = r3->children_pointers_map;
	if( r10 == NULL ) hl_null_access();
	haxe_ds_ObjectMap_clear(r10);
	r5 = NULL;
	r3->abstractNode = r5;
	label$defaeaf_5_922:
	r28 = 1.5;
	r29 = (float)r28;
	r28 = 1.5;
	r30 = (float)r28;
	r28 = 1.5;
	r31 = (float)r28;
	r27 = Urho3D__math_tvector3_create(r29,r30,r31);
	if( r1 == NULL ) hl_null_access();
	r5 = r1->abstractNode;
	if( !r5 ) goto label$defaeaf_5_936;
	r18 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r17 = r18->context;
	r5 = r1->abstractNode;
	Urho3D__scene_node_set_scale(r17,r5,r27);
	label$defaeaf_5_936:
	r5 = r1->abstractNode;
	if( !r5 ) goto label$defaeaf_5_946;
	r18 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r17 = r18->context;
	r5 = r1->abstractNode;
	r15 = (String)s$ParticleEmitter2D;
	r20 = 0;
	r33 = 0;
	r32 = Urho3D__scene_node_create_component(r17,r5,r15,r20,r33);
	goto label$defaeaf_5_947;
	label$defaeaf_5_946:
	r32 = NULL;
	label$defaeaf_5_947:
	if( !r32 ) goto label$defaeaf_5_957;
	r18 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r17 = r18->context;
	r34 = Urho3D__urho2d_particle_emitter2d_cast_from_component(r17,r32);
	if( !r34 ) goto label$defaeaf_5_955;
	r35 = (urho3d__ParticleEmitter2D)hl_alloc_obj(&t$urho3d_ParticleEmitter2D);
	urho3d_ParticleEmitter2D_new(r35,r34);
	goto label$defaeaf_5_956;
	label$defaeaf_5_955:
	r35 = NULL;
	label$defaeaf_5_956:
	goto label$defaeaf_5_958;
	label$defaeaf_5_957:
	r35 = NULL;
	label$defaeaf_5_958:
	r18 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r17 = r18->context;
	r15 = (String)s$Particles_PlayerExplosion_pex;
	r36 = Urho3D__urho2d_particle_effect2d_create(r17,r15);
	if( r35 == NULL ) hl_null_access();
	r37 = urho3d_ParticleEmitter2D_set_effect(r35,r36);
	return;
}

void samplygame_Player_SendHealthUpdateToSamplyGame(samplygame__Player r0) {
	samplygame__SamplyGame r2;
	double r4, r6, r7;
	int r5;
	samplygame__$SamplyGame r3;
	r3 = (samplygame__$SamplyGame)g$_samplygame_SamplyGame;
	r2 = r3->mainGame;
	if( !r2 ) goto label$defaeaf_6_14;
	r5 = r0->Health;
	r4 = (double)hl_dyn_castd(&r5,&t$_i32);
	r5 = r0->MaxHealth;
	r6 = (double)r5;
	r4 = r4 / r6;
	r7 = 100.;
	r6 = r4 * r7;
	r3 = (samplygame__$SamplyGame)g$_samplygame_SamplyGame;
	r2 = r3->mainGame;
	if( r2 == NULL ) hl_null_access();
	samplygame_SamplyGame_OnPlayerHealthUpdate(r2,r6);
	label$defaeaf_6_14:
	return;
}

void samplygame_Player_new(samplygame__Player r0,vdynamic* r1) {
	String r4;
	hl_urho3d_math_vector3 *r5;
	float r7, r8, r9;
	double r6;
	int r2;
	r2 = -50;
	r0->offsetY = r2;
	samplygame_Aircraft_new(((samplygame__Aircraft)r0),r1);
	r4 = (String)s$Player;
	r0->name = r4;
	r2 = 2;
	r0->CollisionLayer = r2;
	r6 = 2.399999999999999911;
	r7 = (float)r6;
	r6 = 1.199999999999999956;
	r8 = (float)r6;
	r6 = 1.199999999999999956;
	r9 = (float)r6;
	r5 = Urho3D__math_vector3_create(r7,r8,r9);
	r0->CollisionShapeSize = r5;
	r2 = 300;
	r0->MaxHealth = r2;
	return;
}

