// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_Texture2D/Texture2D_Impl_.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
String urho3d__Texture2D_Texture2D_Impl__GetName(hl_urho3d_texture2d*);
String String_fromUTF8(vbyte*);

hl_urho3d_texture2d* urho3d__Texture2D_Texture2D_Impl___new(String r0) {
	hl_urho3d_texture2d *r1;
	urho3d___Context__$Context_Impl_ r3;
	urho3d_context *r2;
	if( r0 ) goto label$2d438e6_1_5;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_texture2d_create_empty(r2);
	goto label$2d438e6_1_8;
	label$2d438e6_1_5:
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_texture2d_create(r2,r0);
	label$2d438e6_1_8:
	return r1;
}

bool urho3d__Texture2D_Texture2D_Impl__SetSize(hl_urho3d_texture2d* r0,int r1,int r2,int r3,int* r4,int* r5,bool* r6) {
	bool r9, r10;
	urho3d___Context__$Context_Impl_ r12;
	urho3d_context *r11;
	int r7, r8;
	if( r4 ) goto label$2d438e6_2_3;
	r7 = 0;
	goto label$2d438e6_2_4;
	label$2d438e6_2_3:
	r7 = *r4;
	label$2d438e6_2_4:
	if( r5 ) goto label$2d438e6_2_7;
	r8 = 1;
	goto label$2d438e6_2_8;
	label$2d438e6_2_7:
	r8 = *r5;
	label$2d438e6_2_8:
	if( r6 ) goto label$2d438e6_2_11;
	r9 = true;
	goto label$2d438e6_2_12;
	label$2d438e6_2_11:
	r9 = *r6;
	label$2d438e6_2_12:
	r12 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r11 = r12->context;
	r10 = Urho3D__graphics_texture2d_set_size(r11,r0,r1,r2,r3,r7,r8,r9);
	return r10;
}

String urho3d__Texture2D_Texture2D_Impl__get_name(hl_urho3d_texture2d* r0) {
	String r1;
	r1 = urho3d__Texture2D_Texture2D_Impl__GetName(r0);
	return r1;
}

String urho3d__Texture2D_Texture2D_Impl__GetName(hl_urho3d_texture2d* r0) {
	String r1;
	vbyte *r2;
	r2 = Urho3D__graphics_texture2d_get_name(r0);
	r1 = String_fromUTF8(r2);
	return r1;
}

int urho3d__Texture2D_Texture2D_Impl__set_filterMode(hl_urho3d_texture2d* r0,int r1) {
	urho3d___Context__$Context_Impl_ r4;
	urho3d_context *r3;
	r4 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r3 = r4->context;
	Urho3D__graphics_texture2d_set_filter_mode(r3,r0,r1);
	return r1;
}

int urho3d__Texture2D_Texture2D_Impl__get_filterMode(hl_urho3d_texture2d* r0) {
	urho3d___Context__$Context_Impl_ r3;
	urho3d_context *r2;
	int r1;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_texture2d_get_filter_mode(r2,r0);
	return r1;
}

hl_urho3d_graphics_render_surface* urho3d__Texture2D_Texture2D_Impl__get_renderSurface(hl_urho3d_texture2d* r0) {
	urho3d___Context__$Context_Impl_ r3;
	hl_urho3d_graphics_render_surface *r1;
	urho3d_context *r2;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_texture2d_get_render_surface(r2,r0);
	return r1;
}

hl_urho3d_graphics_texture* urho3d__Texture2D_Texture2D_Impl__toTexture(hl_urho3d_texture2d* r0) {
	urho3d___Context__$Context_Impl_ r3;
	hl_urho3d_graphics_texture *r1;
	urho3d_context *r2;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_texture2d_cast_to_texture(r2,r0);
	return r1;
}

hl_urho3d_texture2d* urho3d__Texture2D_Texture2D_Impl__fromTexture(hl_urho3d_graphics_texture* r0) {
	hl_urho3d_texture2d *r1;
	urho3d___Context__$Context_Impl_ r3;
	urho3d_context *r2;
	r3 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r2 = r3->context;
	r1 = Urho3D__graphics_texture2d_cast_from_texture(r2,r0);
	return r1;
}

