// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <actions/ExtraAction.h>
void actions_FiniteTimeAction_new(actions__FiniteTimeAction,double*);
extern hl_type t$actions_ExtraAction;
#include <urho3d/Node.h>
#include <actions/ExtraActionState.h>
#include <actions/FiniteTimeActionState.h>
extern hl_type t$actions_ExtraActionState;
void actions_ExtraActionState_new(actions__ExtraActionState,actions__ExtraAction,urho3d__Node);

void actions_ExtraAction_new(actions__ExtraAction r0) {
	double *r2;
	r2 = NULL;
	actions_FiniteTimeAction_new(((actions__FiniteTimeAction)r0),r2);
	return;
}

actions__FiniteTimeAction actions_ExtraAction_Reverse(actions__ExtraAction r0) {
	actions__ExtraAction r1;
	r1 = (actions__ExtraAction)hl_alloc_obj(&t$actions_ExtraAction);
	actions_ExtraAction_new(r1);
	return ((actions__FiniteTimeAction)r1);
}

actions__FiniteTimeActionState actions_ExtraAction_StartAction(actions__ExtraAction r0,urho3d__Node r1) {
	actions__ExtraActionState r2;
	r2 = (actions__ExtraActionState)hl_alloc_obj(&t$actions_ExtraActionState);
	actions_ExtraActionState_new(r2,r0,r1);
	return ((actions__FiniteTimeActionState)r2);
}

