// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/MyApplication.h>
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
#include <hl/natives.h>
extern haxe__$Log g$_haxe_Log;
extern String s$Setup;
extern hl_type t$vrt_329ffa8;
extern String s$src_haxe_Main_hx;
extern hl_type t$String;
extern hl_type t$_i32;
extern String s$MyApplication;
extern hl_type t$vrt_eaa6a3b;
extern String s$Update;
void MyApplication_HandleUpdate(MyApplication,hl_urho3d_stringhash*,hl_urho3d_variantmap*);
extern hl_type t$fun_e268a04;
void urho3d_Application_SubscribeToEvent(urho3d__Application,hl_urho3d_stringhash*,vclosure*);
extern hl_type t$hl_urho3d_stringhash;
extern String s$Start_;
extern hl_type t$_type;
String Std_string(vdynamic*);
String String___add__(String,String);
extern String s$Start;
extern String s$update_hx;
extern String s$HandleUpdate;
void urho3d_Application_new(urho3d__Application);

void MyApplication_Setup(MyApplication r0) {
	hl_urho3d_stringhash *r9;
	String r4, r6;
	vvirtual *r5, *r8;
	haxe__$Log r3;
	vclosure *r2, *r10;
	int r7;
	r3 = (haxe__$Log)g$_haxe_Log;
	r2 = r3->trace;
	if( r2 == NULL ) hl_null_access();
	r4 = (String)s$Setup;
	r5 = hl_alloc_virtual(&t$vrt_329ffa8);
	r6 = (String)s$src_haxe_Main_hx;
	if( hl_vfields(r5)[1] ) *(String*)(hl_vfields(r5)[1]) = (String)r6; else hl_dyn_setp(r5->value,37969014/*fileName*/,&t$String,r6);
	r7 = 41;
	if( hl_vfields(r5)[2] ) *(int*)(hl_vfields(r5)[2]) = (int)r7; else hl_dyn_seti(r5->value,371360620/*lineNumber*/,&t$_i32,r7);
	r6 = (String)s$MyApplication;
	if( hl_vfields(r5)[0] ) *(String*)(hl_vfields(r5)[0]) = (String)r6; else hl_dyn_setp(r5->value,-63073762/*className*/,&t$String,r6);
	r6 = (String)s$Setup;
	if( hl_vfields(r5)[3] ) *(String*)(hl_vfields(r5)[3]) = (String)r6; else hl_dyn_setp(r5->value,302979532/*methodName*/,&t$String,r6);
	r8 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r5);
	r2->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r2->fun)((vdynamic*)r2->value,((vdynamic*)r4),r8) : ((void (*)(vdynamic*,vvirtual*))r2->fun)(((vdynamic*)r4),r8);
	r4 = (String)s$Update;
	r9 = Urho3D__create_stringhash(r4);
	r10 = hl_alloc_closure_ptr(&t$fun_e268a04,MyApplication_HandleUpdate,r0);
	urho3d_Application_SubscribeToEvent(((urho3d__Application)r0),r9,r10);
	return;
}

void MyApplication_Start(MyApplication r0) {
	String r5, r6;
	vvirtual *r8, *r10;
	hl_type *r1;
	haxe__$Log r4;
	vclosure *r3;
	vdynamic *r7;
	int r9;
	r1 = &t$hl_urho3d_stringhash;
	r4 = (haxe__$Log)g$_haxe_Log;
	r3 = r4->trace;
	if( r3 == NULL ) hl_null_access();
	r5 = (String)s$Start_;
	if( r1 == NULL ) r7 = NULL; else {
		r7 = hl_alloc_dynamic(&t$_type);
		r7->v.ptr = r1;
	}
	r6 = Std_string(r7);
	r5 = String___add__(r5,r6);
	r8 = hl_alloc_virtual(&t$vrt_329ffa8);
	r6 = (String)s$src_haxe_Main_hx;
	if( hl_vfields(r8)[1] ) *(String*)(hl_vfields(r8)[1]) = (String)r6; else hl_dyn_setp(r8->value,37969014/*fileName*/,&t$String,r6);
	r9 = 64;
	if( hl_vfields(r8)[2] ) *(int*)(hl_vfields(r8)[2]) = (int)r9; else hl_dyn_seti(r8->value,371360620/*lineNumber*/,&t$_i32,r9);
	r6 = (String)s$MyApplication;
	if( hl_vfields(r8)[0] ) *(String*)(hl_vfields(r8)[0]) = (String)r6; else hl_dyn_setp(r8->value,-63073762/*className*/,&t$String,r6);
	r6 = (String)s$Start;
	if( hl_vfields(r8)[3] ) *(String*)(hl_vfields(r8)[3]) = (String)r6; else hl_dyn_setp(r8->value,302979532/*methodName*/,&t$String,r6);
	r10 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r8);
	r3->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r3->fun)((vdynamic*)r3->value,((vdynamic*)r5),r10) : ((void (*)(vdynamic*,vvirtual*))r3->fun)(((vdynamic*)r5),r10);
	return;
}

void MyApplication_HandleUpdate(MyApplication r0,hl_urho3d_stringhash* r1,hl_urho3d_variantmap* r2) {
	String r6, r8;
	vvirtual *r7, *r10;
	haxe__$Log r5;
	vclosure *r4;
	int r9;
	r5 = (haxe__$Log)g$_haxe_Log;
	r4 = r5->trace;
	if( r4 == NULL ) hl_null_access();
	r6 = (String)s$update_hx;
	r7 = hl_alloc_virtual(&t$vrt_329ffa8);
	r8 = (String)s$src_haxe_Main_hx;
	if( hl_vfields(r7)[1] ) *(String*)(hl_vfields(r7)[1]) = (String)r8; else hl_dyn_setp(r7->value,37969014/*fileName*/,&t$String,r8);
	r9 = 81;
	if( hl_vfields(r7)[2] ) *(int*)(hl_vfields(r7)[2]) = (int)r9; else hl_dyn_seti(r7->value,371360620/*lineNumber*/,&t$_i32,r9);
	r8 = (String)s$MyApplication;
	if( hl_vfields(r7)[0] ) *(String*)(hl_vfields(r7)[0]) = (String)r8; else hl_dyn_setp(r7->value,-63073762/*className*/,&t$String,r8);
	r8 = (String)s$HandleUpdate;
	if( hl_vfields(r7)[3] ) *(String*)(hl_vfields(r7)[3]) = (String)r8; else hl_dyn_setp(r7->value,302979532/*methodName*/,&t$String,r8);
	r10 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r7);
	r4->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r4->fun)((vdynamic*)r4->value,((vdynamic*)r6),r10) : ((void (*)(vdynamic*,vvirtual*))r4->fun)(((vdynamic*)r6),r10);
	return;
}

void MyApplication_new(MyApplication r0) {
	urho3d_Application_new(((urho3d__Application)r0));
	return;
}

