// Generated by HLC 4.1.2 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <urho3d/_Camera/AbstractCamera_Impl_.h>
#include <hl/natives.h>
#include <urho3d/_Context/Context_Impl_.h>
extern urho3d___Context__$Context_Impl_ g$_urho3d__Context_Context_Impl_;
extern hl_type t$urho3d_Camera;
void urho3d_Camera_new(urho3d__Camera,hl_urho3d_graphics_camera*);

hl_urho3d_graphics_camera* urho3d__Camera_AbstractCamera_Impl___new() {
	urho3d___Context__$Context_Impl_ r2;
	hl_urho3d_graphics_camera *r0;
	urho3d_context *r1;
	r2 = (urho3d___Context__$Context_Impl_)g$_urho3d__Context_Context_Impl_;
	r1 = r2->context;
	r0 = Urho3D__graphics_camera_create(r1);
	return r0;
}

urho3d__Camera urho3d__Camera_AbstractCamera_Impl__toCamera(hl_urho3d_graphics_camera* r0) {
	urho3d__Camera r1;
	r1 = (urho3d__Camera)hl_alloc_obj(&t$urho3d_Camera);
	urho3d_Camera_new(r1,r0);
	return r1;
}

